# Auto generated by generator.py. Delete this line if you make modification.

from scraper.spiders.{{spider.detail_module|safe}} import {{spider.detail_class|safe}}
from scraper.storage_spiders import {{spider.name_module|safe}}

class {{spider.spider_class|safe}}({{spider.detail_class|safe}}):

    name = {{spider.name_module|safe}}.name
    allowed_domains = {{spider.name_module|safe}}.allowed_domains
    start_urls = {{spider.name_module|safe}}.start_urls
    tracking_url = {{spider.name_module|safe}}.tracking_url
    sitemap_urls = {{spider.name_module|safe}}.sitemap_urls
    sitemap_rules = {{spider.name_module|safe}}.sitemap_rules
    sitemap_follow = {{spider.name_module|safe}}.sitemap_follow
    rules = {{spider.name_module|safe}}.rules
    
    def __init__(self, files=None):
        {{spider.detail_class|safe}}.__init__(self, {{spider.name_module|safe}}.XPATH, files)
    
