# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div[@class='product-title']/h1",
    'price' : "//div[@class='row']/div[@class='col-lg-6 col-md-6 col-sm-12 col-xs-12']/div[@class='product-price']/span",
    'category' : "",
    'description' : "//div[@id='mota']/div[@class='container-fluid product-description-wrapper']",
    'images' : "//ul[@class='slides']/li[@class='product-thumb']/a/@data-image",
    'canonical' : "//link[@rel='canonical']/@href",
    'base_url' : "",
    'brand' : "",
    'in_stock' : "",
    'guarantee' : "",
    'promotion' : ""
}
name = 'abeyeu.com'
allowed_domains = ['abeyeu.com']
start_urls = ['http://abeyeu.com/']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = ['']
rules = [
    Rule(LinkExtractor(allow=['/products/[a-zA-Z0-9-]+$']), 'parse_item'),
    Rule(LinkExtractor(allow=['/collections/[a-zA-Z0-9-]+($|\?page=\d+$)']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
