# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//h1[@class='title']",
    'price' : "//div[@class='gia-ban-ct']/strong | //div[@class='cot-2']/div[@class='gia-ban-ct']",
    'category' : "//div[@class='breadcrumb']/a",
    'description' : "//div[@class='field-content']",
    'images' : "//div[@class='field-content']/p//img/@src",
    'canonical' : "//link[@rel='canonical']/@href",
    'base_url' : "",
    'brand' : ""
}
name = 'aboss.vn'
allowed_domains = ['aboss.vn']
start_urls = ['http://aboss.vn/']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow=['/[a-zA-Z0-9-]+-\d+$']), 'parse_item'),
    Rule(LinkExtractor(allow=['/[a-zA-Z-]+($|\?page=\d+)']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
