# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div[@id='Para']/div[@id='pTitleD']/h1/a",
    'price' : "//tr/td[@class='MdetailPri']/a",
    'category' : "//div[@class='breadcrumbs']/div[@class='breadcrumbs']/a/span",
    'description' : "//div[@id='mainContent']/div[@id='ParaLeft']/div[@id='Para']/div[@id='pContent']",
    'images' : "//div[@class='oneByOne1']/div[@id='banner']/div[@class='oneByOne_item']/img/@src",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = 'achaumobile.com'
allowed_domains = ['achaumobile.com']
start_urls = ['http://achaumobile.com']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow=['']), 'parse_item'),
    Rule(LinkExtractor(allow=['']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
