# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div[@class='row']/div[@class='column small-12']/div[@class='summary entry-summary']/h2[@class='product_title entry-title']",
    'price' : "//div[@class='summary entry-summary']/div/p[@class='price']/span[@class='amount']",
    'category' : "//div[@class='row']/div[@class='small-12 column']/nav[@class='woocommerce-breadcrumb alignright']/a[@class='home']",
    'description' : "//div[@class='woocommerce-tabs']/div[@id='tab-description']",
    'images' : "//div[@class='relative-positioned']/div[@class='images']/a/@href",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = 'adongbeauty.com.vn'
allowed_domains = ['adongbeauty.com.vn']
start_urls = ['http://adongbeauty.com.vn']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow=['/[a-zA-Z0-9-]+/+$']), 'parse_item'),
    Rule(LinkExtractor(allow=['/danh-muc/'], deny=['\?']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
