# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div[@class='module item-content-header']/p",
    'price' : "//ul[@class='ict-right-bottom-price']/li[@class='row']/div/p[@class='price']",
    'category' : "",
    'description' : "//div[@class='tab-content my-tab-content']",
    'images' : "//div[@class='tab-content my-tab-content']/div/img/@src",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = 'alimama.vn'
allowed_domains = ['alimama.vn']
start_urls = ['http://alimama.vn/']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow=['/san-pham+-[a-zA-Z0-9-]+i+\d+$'], deny=['xyz']), 'parse_item'),
    Rule(LinkExtractor(deny=['/bai-viet/','/lien-he','atts=','/alias/','/tim-kiem/','/default','/author/'], allow=['/[a-zA-Z-]+$']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
