# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div[@class='head-node']/div[@class='head-center-node']/h1",
    'price' : "//div[@class='gia-node']/div[@class='gia-moi']",
    'category' : "//div[@class='breadcrumb']/a",
    'description' : "//div[@class='views-field views-field-body']/div[@class='field-content']",
    'images' : "//div[@class='image']/ul[@class='image-list']/li/img/@src",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = 'allphone.vn'
allowed_domains = ['allphone.vn']
start_urls = ['http://allphone.vn']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(), 'parse_item'),
    Rule(LinkExtractor(), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
