# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div[@class='pro-detail']/h1",
    'price' : "//div[@class='over-price-number img_full_price']",
    'category' : "//div[@class='cate_path']/a",
    'description' : "//div[@id='pro_detail_info']/div[@class='tab_content_detail']/p",
    'images' : "//div[@class='pro-image']/div/a/@href",
    'canonical' : "//link[@rel='canonical']/@href",
    'base_url' : "",
    'brand' : ""
}
name = 'amazi.vn'
allowed_domains = ['amazi.vn']
start_urls = ['http://amazi.vn/']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    #Rule(LinkExtractor(), 'parse_item'),
    #Rule(LinkExtractor(), 'parse'),
    Rule(LinkExtractor(allow=['/[a-zA-Z0-9-]+\.html($|page=\d+$)']), 'parse_item_and_links'),
]
