# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div[@id='primary_block']/h2",
    'price' : "//span[@class='our_price_display']/span[@id='our_price_display'] | //span[@id='old_price_display']",
    'category' : "//div[@id='center_column']/div[@class='breadcrumb']/a",
    'description' : "//span[@class='hasCaption']",
    'images' : "//img[@id='bigpic']/@src",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = 'ankacenter.com'
allowed_domains = ['ankacenter.com']
start_urls = ['http://ankacenter.com']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow=['/\d+-[a-zA-Z0-9-]+\.html']), 'parse_item'),
    Rule(LinkExtractor(allow=['/\d+-[a-zA-Z0-9-]+$']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
