# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div[@id='main']/div[@id='title']/div[@class='mid']",
    'price' : "//div[@class='thongtin']/p[@class='giaban']",
    'category' : "//div[@class='pathway']/a",
    'description' : "//div[@id='first']/div[@class='wrapx']/p/span | //div[@class='wrapx']/div/p[@class='MsoNormal']/span",
    'images' : "//div[@id='product-slides']/img/@src",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = 'anshop.net.vn'
allowed_domains = ['anshop.net.vn']
start_urls = ['http://anshop.net.vn']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow=['/[a-zA-Z0-9-_]+p+\d+\.html']), 'parse_item'),
    Rule(LinkExtractor(allow=['/[a-zA-Z0-9-_]+c+\d+\.html']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
