# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//span[@class='product_title']",
    'price' : "//span[@class='price']/b",
    'category' : "//div[@class='links']/table[2]//tr/td/table//tr/td[3]/table[1]//tr/td",
    'description' : "//div[@id='tabc_1']/table//tr/td/img/@src",
    'images' : "//table[2]/tbody/tr/td/div/img/@src",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = 'aodoitinhyeu.vn'
allowed_domains = ['aodoitinhyeu.vn']
start_urls = ['http://aodoitinhyeu.vn']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow=['/[a-zA-Z0-9-]+\.htm'], deny=['Channel=News']), 'parse_item'),
    Rule(LinkExtractor(allow=['/danh-muc-san-pham/']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
