# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div[@class='detail']/h1",
    'price' : "//div[@class='group-bottom']/p[@class='price']",
    'category' : "//div[@class='inner breadcrumbs']/a",
    'description' : "//div[@class='tabbed_area']/div",
    'images' : "//div[@class='img-product']/div[@class='img br']/a/@href",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = 'applestorevn.com.vn'
allowed_domains = ['applestorevn.com.vn']
start_urls = ['http://applestorevn.com.vn']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(deny=['/p+\d+/.*']), 'parse_item'),
    Rule(LinkExtractor(allow=['/category/']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
