# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div[@id='product_name']/h1",
    'price' : "//div[@class='mb8 mt10']/span[@class='price mr5'] | //div[@id='pd_info_box']/div[@class='mb15']/span",
    'category' : "//div[@id='navigation']/a",
    'description' : "//div[@id='tab2']/div[@class='product_content']",
    'images' : "//div[@id='product_detail']/div/div[@id='pd_img_box']/a/@href",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = 'aqualaptop.com'
allowed_domains = ['aqualaptop.com']
start_urls = ['http://aqualaptop.com']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(deny=['news.html','contact-us.html','map.html','job.html'], allow=['/p+\d+/']), 'parse_item'),
    Rule(LinkExtractor(allow=['/c+\d+/'], deny=['filter','D=']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
