# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div[@class='content']/div[@class='detail_content_top']/div[@class='detail_top_info']/h1[@class='detail_title']",
    'price' : "//div[@class='detail_info detail_info_buy']/div[@class='detail_info_buy_left']/div/span[@class='detail_price']",
    'category' : "//div[@class='wrap']/div[@class='content']/div[@class='content_link']/a",
    'description' : "",
    'images' : "//div[@class='detail_content_top']/div[@class='detail_top_images']/div[@id='detail_images']/a/@href",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = 'asin.com.vn'
allowed_domains = ['asin.com.vn']
start_urls = ['http://asin.com.vn']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow=['']), 'parse_item'),
    Rule(LinkExtractor(allow=['']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
