# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//h1[@class='none_tag bdetail_title']",
    'price' : "//span[@class='bd_price']",
    'category' : "//div[@class='pw_title']/a/span",
    'description' : "//div[@class='bdetail_tab_content']/div[@class='td_tab_content'][1]",
    'images' : "//div[@class='bd_sale_flag']/img/@src | //div[@class='bdt_img']/img/@src",
    'canonical' : "//link[@rel='canonical']/@href",
    'base_url' : "",
    'brand' : ""
}
name = 'atlazbooks.com'
allowed_domains = ['atlazbooks.com']
start_urls = ['http://www.atlazbooks.com']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow=['/[a-zA-Z0-9_-]+\.html']), 'parse_item'),
    Rule(LinkExtractor(allow = ['/page+_\d+\.html'], deny=['/news/']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
