# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//h1[@itemprop='name']",
    'price' : "//div[@itemprop='offers']/p[@class='price']",
    'category' : "//div[@class='product_meta']/span[@class='posted_in']/a[1]",
    'description' : "//div[@class='thongtin']/div[@class='thongtinsanpham']/p",
    'images' : "//div[@class='images']/a[@itemprop='image']/@href",
    'canonical' : "",
    'base_url' : "",
    'brand' : "",
    'in_stock' : "",
    'guarantee' : ""
}
name = 'avenevietnam.com'
allowed_domains = ['avenevietnam.com']
start_urls = ['http://avenevietnam.com/']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = ['']
rules = [
    Rule(LinkExtractor(allow=['/san-pham/'], deny=['/danh-muc/']), 'parse_item'),
    Rule(LinkExtractor(allow=['/danh-muc/san-pham/']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
