# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//h1[@class='thread-details-title']",
    'price' : "//div[@class='lf f50']/div[@class='thread-details-giamoi']",
    'category' : "//div[@class='w90']/a",
    'description' : "//div[@class='div-dieukien-noibat thread-details-content']",
    'images' : "//div[@class='thread-details-avt']/img/@src",
    'canonical' : "",
    'base_url' : "//base/@href",
    'brand' : ""
}
name = 'azbay.vn'
allowed_domains = ['azbay.vn']
start_urls = ['http://azbay.vn/']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow=['/[a-zA-Z0-9-]+-p\d+/$']), 'parse_item'),
    Rule(LinkExtractor(allow=['/c\d+-[a-zA-Z0-9-]+/','/actions/thread.cid=\d+.p=\d+']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
