# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div[@class='product-shop-wrapper ']/div[@class='product-name']/h1",
    'price' : "//div[@class='product-data']/div[@class='price-box']/span/span[@class='price']",
    'category' : "//div[@class='breadcrumbs']/ul/li/a",
    'description' : "//div[@id='pr-desc']/div[@class='std']/p",
    'images' : "//div[@class='more-views none-slider-more-views']/ul/li/a/@href | //div[@class='product-img-box']/p//img/@src",
    'canonical' : "//link[@rel='canonical']/@href",
    'base_url' : "",
    'brand' : ""
}
name = 'babimart.com'
allowed_domains = ['babimart.com']
start_urls = ['http://babimart.com']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(), 'parse_item'),
    Rule(LinkExtractor(), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
