# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div[@class='short_desc']/div/a",
    'price' : "//div[@class='description_value']",
    'category' : "//div[@class='breadcrum']/div/a[@class='sub_breadcrum']",
    'description' : "",
    'images' : "//div[@class='img_view']/div[@class='main_img']/a/@href",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = 'babycute.com.vn'
allowed_domains = ['babycute.com.vn']
start_urls = ['http://babycute.com.vn']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow=['/Products+/[a-zA-Z0-9-_,]+\.html']), 'parse_item'),
    Rule(LinkExtractor(deny=['/News/','/login.html','/register.html','http://babycute.com.vn/order.html']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
