# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div[@class='product-name']/h1/font/font",
    'price' : "//div[@class='price-box']/span/span[@class='price']/font/font",
    'category' : "",
    'description' : "",
    'images' : "//div[@class='MagicToolboxContainer']/div/a/img/@src",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = 'bacdep.com.vn'
allowed_domains = ['bacdep.com.vn']
start_urls = ['http://bacdep.com.vn']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(), 'parse_item'),
    Rule(LinkExtractor(), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
