# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div[@class='info_detail right']/h3[@class='pd_title']",
    'price' : "//div[@class='col_left']/form[@id='buy_info']/span[@class='price']",
    'category' : "//div[@class='mainblock right']/ul/li",
    'description' : "//div[@class='page_pd_detail']/div[3]",
    'images' : "//div[@class='img_detail_big']/a/@href",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = 'bachhoaso.com'
allowed_domains = ['bachhoaso.com']
start_urls = ['http://bachhoaso.com']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow=['/san-pham/']), 'parse_item'),
    Rule(LinkExtractor(allow=['/danh-muc-san-pham/']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
