# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div[@class='box_mid']/div[@class='mid-title']/div[@class='titleL']/h1",
    'price' : "//tr/td/div[@class='prod_dt_price']/span",
    'category' : "//div[@id='vnt-wrapper']/div[@id='vnt-container']/div[@class='navation']/a",
    'description' : "//td/div[@id='tblOption']",
    'images' : "//div[@class='ad-image']/a/@href",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = 'bachlong.vn'
allowed_domains = ['bachlong.vn']
start_urls = ['http://www.bachlong.vn']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow=['/san-pham+/\d+/[a-zA-Z0-9-]+\.html']), 'parse_item'),
    Rule(LinkExtractor(allow=['/san-pham+/[a-zA-Z0-9-]+\.html']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
