# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//header[@class='header-product']/h1[@class='product-title']",
    'price' : "//li[@class='purchase']/p[@class='product-price']/span[@class='price']",
    'category' : "//div[@id='primary']/div[@class='breadcrumb clearfix']/span/a",
    'description' : "//div[@class='product-content entry-content clearfix']/p",
    'images' : "//div[@class='product-slider']/div/div/img/@src",
    'canonical' : "//link[@rel='canonical']/@href",
    'base_url' : "",
    'brand' : "",
    'in_stock' : "",
    'guarantee' : "",
    'promotion' : ""
}
name = 'balance.com.vn'
allowed_domains = ['balance.com.vn']
start_urls = ['http://balance.com.vn/']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = ['']
rules = [
    Rule(LinkExtractor(allow=['/products/']), 'parse_item'),
    Rule(LinkExtractor(allow=['/collections/'], deny=['/products/']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
