# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//span[@class='detail_ten']/div/h1",
    'price' : "//span[@class='detail_ten']/div[2]/font[2]",
    'category' : "//div[@class='bacerum']/span/a",
    'description' : "//div/div[@class='detail_noidung']",
    'images' : "//div[@class='detail_thongtin']/span[@class='detail_img']/p/img/@src",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = 'banlegiare.net'
allowed_domains = ['banlegiare.net']
start_urls = ['http://banlegiare.net']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow=['/chi-tiet/+[a-zA-Z0-9-]+\.html']), 'parse_item'),
    Rule(LinkExtractor(allow=['/[a-zA-Z0-9-]+-sp']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
