# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div[@class='cf']/h3",
    'price' : "//div[@class='deal-buy']/p[@class='deal-price']/strong|//table[@class='deal-discount']//tr[1]/td/span",
    'category' : "",
    'description' : "//div[@class='main']/div[@class='blk detail']",
    'images' : "//div[@class='mid']/ul/li/img/@src",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = 'banre123.vn'
allowed_domains = ['banre123.vn']
start_urls = ['http://banre123.vn/']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = ['']
rules = [
    #Rule(LinkExtractor(), 'parse_item'),
    #Rule(LinkExtractor(), 'parse'),
    Rule(LinkExtractor(allow=['/[a-zA-Z0-9-]+-\d+\.html($|\?page=\d+$)']), 'parse_item_and_links'),
]
