# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div[@class='content-content']/div/div[1]",
    'price' : "//span[@style='color:#FF0000; font-size:14px;'][1]",
    'category' : "//div[@class='mainContent']/a",
    'description' : "//div[@class='content-content']/div/div[3]",
    'images' : "//table/tbody/tr/td/p[@id='imgs']/img/@src | //img[@id='imgMain']/@src",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = 'baongoclaptop.com'
allowed_domains = ['baongoclaptop.com']
start_urls = ['http://baongoclaptop.com/']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow=['/san-pham']), 'parse_item'),
    Rule(LinkExtractor(allow=['/danh-muc']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
