# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div[@class='producttt']",
    'price' : "//div[@class='progia pi_price']/span[@class='pip_price']",
    'category' : "//div[@id='breadcrumb']/ul/li[@class='bc_next']/a",
    'description' : "//div[@class='middle listpro']/div[@id='tab_kythuat']",
    'images' : "//div[@class='image']/a/@href",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = 'baotuyetmobile.vn'
allowed_domains = ['baotuyetmobile.vn']
start_urls = ['http://baotuyetmobile.vn']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow=['/product/+\d+/[a-zA-Z0-9-]+\.html']), 'parse_item'),
    Rule(LinkExtractor(allow=['/catproducts/+\d+/[a-zA-Z0-9-]+\.html']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
