# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div[@id='base']/div[@class='info-inner']/h1[@id='title-product']",
    'price' : "//dl[@class='clearfix'][3]/dd/div[@class='price']/span[@id='sub_price'] | //dl[@class='clearfix'][2]/dd/div[@class='price']/span[@id='sub_price']",
    'category' : "//div[@class='breadcrumb']/ul[@class='breadcrumb-nav clearfix']/li/a",
    'description' : "//div[@class='detail-desc']/div[@id='tab2']",
    'images' : "//div[@class='image-item']/img[@id='image-lag']/@src | //div[@class='detail-desc']/div[@id='tab2']/p//img/@src",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = 'bayban.vn'
allowed_domains = ['bayban.vn']
start_urls = ['http://www.bayban.vn']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow=['/chi-tiet/']), 'parse_item'),
    Rule(LinkExtractor(allow=['/[a-zA-Z0-9-]+$']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
