# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div[@class='product-info']/div/div/h1",
    'price' : "//div[@class='description']/div[@class='price']/text()",
    'category' : "//div[@class='breadcrumb']/a",
    'description' : "//div[@class='wrapper']/div[@id='tab-description'] | //div[@class='wrapper']/div/p/img/@src",
    'images' : "//div[@class='image']/div/a/img/@src",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = 'bbmobile.vn'
allowed_domains = ['bbmobile.vn']
start_urls = ['http://bbmobile.vn']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(), 'parse_item'),
    Rule(LinkExtractor(), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
