# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div[@class='product-name hidden-xs']/h1[@itemprop='name']",
    'price' : "//meta[@property='og:price:amount'][1]/@content",
    'category' : "//div[@class='container']/div[@class='row']/ul/li/a",
    'description' : "//div[@class='product-collateral']/div[@class='tab-content']",
    'images' : "//meta[@property='og:image'][1]/@content",
    'canonical' : "//link[@rel='canonical']/@href",
    'base_url' : "",
    'brand' : "",
    'in_stock' : "",
    'guarantee' : "",
    'promotion' : ""
}
name = 'beemart.vn'
allowed_domains = ['beemart.vn']
start_urls = ['http://beemart.vn']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = ['']
rules = [
    #Rule(LinkExtractor(), 'parse_item'),
    #Rule(LinkExtractor(), 'parse'),
    Rule(LinkExtractor(allow=['/[a-zA-Z0-9-]+($|\?page=\d+$)']), 'parse_item_and_links'),
]
