# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//section/article[@class='productdetail']/div[@class='topright']/h1",
    'price' : "//div[@id='price-info']/ul/li/strong[@class='price']",
    'category' : "//div[@class='breadcrumb clearfix']/ul/li/a",
    'description' : "//article[@class='productdetail']/aside[@class='detail']/div[@class='content']/article[@class='bodycontent']",
    'images' : "//article[@class='productdetail']/div[@class='topleft']/div[@class='main-gallery']/img/@src",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = 'benmobile.vn'
allowed_domains = ['benmobile.vn']
start_urls = ['http://benmobile.vn']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow=['']), 'parse_item'),
    Rule(LinkExtractor(allow=['']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
