# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div[@class='boxgiua_wrap']/div/div/h2/span/label",
    'price' : "//div/span[@class='giavnd']",
    'category' : "",
    'description' : "//div[@class='boxgiua_lop2']/ul/li/span",
    'images' : "//div[@class='zoomPad']/img[@id='anh_chitiet_sanpham']/@src",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = 'bep123.vn'
allowed_domains = ['bep123.vn']
start_urls = ['http://bep123.vn']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(), 'parse_item'),
    Rule(LinkExtractor(), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
