# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div[@class='box-info-sp']/div[@class='info-sp']/p/a/b",
    'price' : "//div[@class='info-sp']/p/span[@class='rate']",
    'category' : "//div[@id='body-home']/div[@class='breadcrumb']/a",
    'description' : "//div[@class='product-content']/div[@id='tabs']/div[@id='tab-1']/p",
    'images' : "//div[@class='mod-images pull-left']/a/@href",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = 'bepluahong.com'
allowed_domains = ['bepluahong.com']
start_urls = ['http://bepluahong.com']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    #Rule(LinkExtractor(), 'parse_item'),
    #Rule(LinkExtractor(), 'parse'),
    Rule(LinkExtractor(allow=['/[a-zA-Z0-9-]+($|\?page=\d+$)']), 'parse_item_and_links'),
]
