# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div[@class='box_gioithieu rieng04']/h1",
    'price' : "//div[@class='thongtin_chitiet']/div[@class='giaKM']/span",
    'category' : "//div[@class='beadcrum']/h3/a/span",
    'description' : "//div[@class='info fl']/ul[@class='contenttab']",
    'images' : "//div[@id='vZoomMagnifier']/img/@src | //div[@class='list_other galery fl']/a/@href",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = 'bepnamduong.com.vn'
allowed_domains = ['bepnamduong.com.vn']
start_urls = ['http://bepnamduong.com.vn/']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(), 'parse_item'),
    Rule(LinkExtractor(), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
