# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div[@class='vs_product_detail_title']/h1",
    'price' : "//div[@class='vs_product_detail_price']",
    'category' : "//div[@class='vs_center_tab_text']/a",
    'description' : "//div[@class='TabbedPanelsContent TabbedPanelsContentVisible content_table']|//div[@class='vs_product_detail_brief']",
    'images' : "//div[@id='large_img_div0']/a/@href",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = 'bepvuson.vn'
allowed_domains = ['bepvuson.vn']
start_urls = ['http://bepvuson.vn/']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow=['/[a-zA-Z0-9-]+\d+.*\.html$']), 'parse_item'),
    Rule(LinkExtractor(allow=['/[a-zA-Z-]+\.html']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
