# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div[@class='container']/div[@class='row details_page']/div/h1",
    'price' : "//div[contains(@class,'box-price')]/span[@class='price price_sku']",
    'category' : "//li/span[@class='top_breadcrumb']/a/span[1]",
    'description' : "//div[@class='background_main background_list_product']/div[@class='container']/div[@class='row']/div[@class='col-md-16 col-sm-24 col-xs-24 content-infomation']",
    'images' : "//img[@class='etalage_source_image']/@src",
    'canonical' : "",
    'base_url' : "",
    'brand' : "",
    'in_stock' : "",
    'guarantee' : "",
    'promotion' : ""
}
name = 'bibomart.com.vn'
allowed_domains = ['bibomart.com.vn']
start_urls = ['https://bibomart.com.vn']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = ['']
rules = [
    Rule(LinkExtractor(allow=['/[a-zA-Z0-9-]+-p+\d+\.html$']), 'parse_item'),
    Rule(LinkExtractor(allow=['/[a-zA-Z0-9-]+-c+\d+\.html($|\?Product_page=\d+$)']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
