# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//h1",
    'price' : "//div[@class='product-info']//div[@class='price']/span[@class='price-new']",
    'category' : "//div[@class='breadcrumb']/a[position()<last()]",
    'description' : "//div[@class='wrap-product']/div[@class='tab-content']",
    'images' : "//div[@class='myspan5 product-img-box']/div[@class='image']//img/@src",
    'canonical' : "//link[@rel='canonical']/@href",
    'base_url' : "//base/@href",
    'brand' : ""
}
name = 'bigdream.vn'
allowed_domains = ['bigdream.vn']
start_urls = ['http://bigdream.vn/']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    #Rule(LinkExtractor(allow=['/[a-zA-Z0-9-]+\.html$']), 'parse_item'),
    #Rule(LinkExtractor(allow=['/[a-zA-Z0-9-]+($|\?page=\d+$)']), 'parse'),
    Rule(LinkExtractor(allow=['']), 'parse_item_and_links'),
]
