# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//h1[@class='name clearfix']",
    'price' : "//input[@id='pricePro']/@value",
    'category' : "//div[@class='breadcrumb clearfix']/a",
    'description' : "//div[@id='pb-right-column']/div[@class='clear']",
    'images' : "//img[@class='img-responsive']/@src",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = 'bkc.vn'
allowed_domains = ['bkc.vn']
start_urls = ['http://www.bkc.vn/']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = ['']
rules = [
    #Rule(LinkExtractor(), 'parse_item'),
    #Rule(LinkExtractor(), 'parse'),
    Rule(LinkExtractor(allow=['/[a-zA-Z0-9-]+-\d+\.html'], deny=['so-sanh']), 'parse_item_and_links'),
]
