# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div[@id='short_description_block']/h1",
    'price' : "//div[@class='price']/p[@class='our_price_display']/span[@id='our_price_display']",
    'category' : "//div[@class='breadcrumb']/ul/li/a[@itemprop='url']/span[@itemprop='title']",
    'description' : "//div[@class='left_detail_pro']/div[@class='tabs']/ul[@class='product-content']",
    'images' : "//div[@id='pb-right-column']/div/a/@href",
    'canonical' : "",
    'base_url' : "",
    'brand' : "",
    'in_stock' : "//div[@class='actions']/a[@class='btn-circle first-bg']/strong",
    'guarantee' : "",
    'promotion' : ""
}
name = 'bluestar-vn.com'
allowed_domains = ['bluestar-vn.com']
start_urls = ['http://bluestar-vn.com/']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = ['']
rules = [
    Rule(LinkExtractor(allow=['\.html']), 'parse_item'),
    Rule(LinkExtractor(allow=['/san-pham/'], deny=['\.html']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
