# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div[@class='header_layer_2']/h2/span/label",
    'price' : "//div[@class='boxgiua_lop2']/table//tr/td/div/span[@class='giavnd']",
    'category' : "",
    'description' : "//div[@class='boxgiua_lop2']/pre/span",
    'images' : "//div[@class='div_anh_chi_tiet']/a/div[@class='zoomPad']/img/@src",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = 'bovangshop.mov.mn'
allowed_domains = ['bovangshop.mov.mn']
start_urls = ['http://bovangshop.mov.mn']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow=['/ct/chi-tiet/+\d+/[a-zA-Z0-9-]+\.html']), 'parse_item'),
    Rule(LinkExtractor(allow=['/sp/danh-sach/+\d+/v=0+/[a-zA-Z0-9-]+\.html']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
