# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div[@class='summary']/span[@class='title product_title entry-title']",
    'price' : "//div[@class='summary']/span[@class='price']/font/ins/span",
    'category' : "//div[@class='content-inner']/div[@id='breadcrumb']/a",
    'description' : "//div[@class='text-info']/div/span[@class='description']",
    'images' : "//div[@id='exposure']/div/a/img/@src | //div[@class='product-gallery float-left images']/div/ul/li/img/@src",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = 'buffalohn.com'
allowed_domains = ['buffalohn.com']
start_urls = ['http://buffalohn.com']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow=['/[a-zA-Z0-9-]+/']), 'parse_item'),
    Rule(LinkExtractor(deny=['/khuyen-mai/','/ho-tro/','lien-he','/gioi-thieu/']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
