# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//tr/td[@class='p_title']",
    'price' : "//td[@class='pdetal_pricebtf']/b",
    'category' : "//td[@class='title_cat_list_detail']/a",
    'description' : "//div[@class='nanotabs']/div[@id='spe']",
    'images' : "//ul[@class='thumbelina']/li/img[@class='cloudzoom-gallery']/@src",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = 'butterfly.vn'
allowed_domains = ['butterfly.vn']
start_urls = ['http://butterfly.vn/']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow=['/[a-zA-Z0-9-]+/+$']), 'parse_item'),
    Rule(LinkExtractor(allow=['/products/']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
