# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div[@class='productdetail_title']/h1",
    'price' : "//div[@class='shortcontent-info']/ul/li/div[@class='pricesale dt']",
    'category' : "//div[@class='left_content_home']/div/a",
    'description' : "//div[@class='contents marginbot']/div[@id='content1']/div",
    'images' : "//div[@class='inner-img-detail zoom-thumb-detail']/div/a/img/@src | //div[@class='thumb-detail']/a/img[@class='img-thumb']/@src",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = 'buyon.vn'
allowed_domains = ['buyon.vn']
start_urls = ['http://buyon.vn']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(), 'parse_item'),
    Rule(LinkExtractor(), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
