# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div[@class='table-product']/h3[@class='title']",
    'price' : "//div[@class='table-product']/div/div[@class='so ']",
    'category' : "",
    'description' : "//div[@id='tabs1']/table[@class='table_technical']//tr/td",
    'images' : "//div[@class='content-detail']/div/a/img/@src",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = 'caplaptop.com'
allowed_domains = ['caplaptop.com']
start_urls = ['http://caplaptop.com']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow=['/detail/product/']), 'parse_item'),
    Rule(LinkExtractor(allow=['/cat/san-pham/','/manu/san-pham/']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
