# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div[@class='atdetail_title']/h1",
    'price' : "//div[@class='box_detail_price']/div[@class='detail_team_price'] | //div[@class='box_detail_price']/div[@class='detail_market_price']",
    'category' : "//div[@class='atbreadcrum']/a",
    'description' : "//div[@class='tabbed_area']/div[@class='atboxinfocoment']",
    'images' : "//div[@id='atdetail_slider']/div[@id='at_slider']/img/@src",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = 'cheapdeal.vn'
allowed_domains = ['cheapdeal.vn']
start_urls = ['http://cheapdeal.vn/']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow = ['/[a-zA-Z0-9-]+\d+\.html'], deny=['/ve-cheapdeal.html','/hop-tac-voi-cheap-deal.html']), 'parse_item'),
    Rule(LinkExtractor(deny=['/account/']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
