# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div[@class='thongtin_sp fl']/h2",
    'price' : "//div[@class='khoi_c']/span[@class='giaban']",
    'category' : "//div[@class='tieude_c']/a",
    'description' : "//div[@class='sanpham_c fl']/div",
    'images' : "//div/span/img/@src",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = 'chego.vn'
allowed_domains = ['chego.vn']
start_urls = ['http://chego.vn']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow=['']), 'parse_item'),
    Rule(LinkExtractor(allow=['']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
