# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div[@id='centerid']/table//tr/td[@id='contentid']/div/div/div/div/h1",
    'price' : "//div[@id='centerid']/table//tr/td/div/div/div/table//tr[1]/td[2]/font",
    'category' : "//div[@id='yarnball']/ul/li/a",
    'description' : "//div[@id='centerid']/table//tr/td[@id='contentid']/table[2]/tbody/tr/td/table//tr/td/table",
    'images' : "//div[@id='centerid']/table//tr/td/div/div[1]/div/table//tr/td/img/@src",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = 'chicomot.com'
allowed_domains = ['chicomot.com']
start_urls = ['http://chicomot.com']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow=['/San-pham/+\d+/\d+/[a-zA-Z0-9-_]+\.html']), 'parse_item'),
    Rule(LinkExtractor(allow=['/San-pham/[a-zA-Z0-9-]+/[a-zA-Z0-9-_]+\.html']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
