# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div[@class='tengiasp_cc_l_tl']",
    'price' : "//div[@class='tengiasp_cc_r_giasanpham_cc_lin1_c_1_cc']",
    'category' : "//div[@class='tengiasp_cc_l']/div/a",
    'description' : "//div[@id='list_thongsosanpham']",
    'images' : "//div[@class='tengiasp_cc_l_imgm_c']/img/@src | //div[@class='tengiasp_cc_l_imgli_fufr_e']/img/@src",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = 'chipchipshop.com'
allowed_domains = ['chipchipshop.com']
start_urls = ['http://www.chipchipshop.com/Default.aspx']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow = ['/p+\d+$','/san-pham/']), 'parse_item'),
    Rule(LinkExtractor(allow = ['/[a-zA-Z0-9-]+/g\d+']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
