# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//h1",
    'price' : "//div[@class='p-row p-buynow clearfix']/p[@class='price text-danger']/strong/span",
    'category' : "//ol[@class='breadcrumb']/li/a",
    'description' : "//div[@class='pt-tabinner'][1]/div[@class='maincontent']/p",
    'images' : "//meta[@property='og:image']/@content",
    'canonical' : "//link[@rel='canonical']/@href",
    'base_url' : "",
    'brand' : "",
    'in_stock' : "",
    'guarantee' : "",
    'promotion' : ""
}
name = 'chodientu.vn'
allowed_domains = ['chodientu.vn']
start_urls = ['https://www.chodientu.vn/']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = ['']
rules = [
    Rule(LinkExtractor(allow=['/[a-zA-Z0-9-]+-\d+$']), 'parse_item'),
    Rule(LinkExtractor(allow=['/[a-zA-Z0-9-]+($|\?trang=\d+$)'], deny=['/[a-zA-Z0-9-]+-\d+$']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
