# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//title",
    'price' : "//aside[@class='righttext']/strong[@class='pricesell']",
    'category' : "",
    'description' : "//div[@class='container lconte']/div[@class='chi-tiet']",
    'images' : "//div[@class='carousel slide carousel-title']/div[@class='carousel-inner']/div/img/@src",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = 'chonhabep.com'
allowed_domains = ['chonhabep.com']
start_urls = ['http://chonhabep.com/']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow=['/san-pham/']), 'parse_item'),
    Rule(LinkExtractor(allow=['/[a-zA-Z0-9-]+($|\?page=\d+.per-page=\d+)']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
