# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div[@class='thread-details']/div/div/div/div/h1",
    'price' : "//div[@class='thread-details-buy']/div[@class='thread-details-giamoi']/span | //div[@class='thread-details-buy']/div[@class='thread-details-giaban']",
    'category' : "//div[@class='thread-details thread-details-tohome']/a",
    'description' : "//div[@id='uiThreadDetails']/div[@class='thread-details'][3]/div",
    'images' : "//div[@class='thread-details-avt']/img/@src | //div[@id='export_img_product']/img/@src",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = 'chungnhom.vn'
allowed_domains = ['chungnhom.vn']
start_urls = ['http://chungnhom.vn']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow=['/muachung+-\d+/[a-zA-Z0-9-]+\.html']), 'parse_item'),
    Rule(LinkExtractor(allow=['/cid+-\d+/[a-zA-Z0-9-]+\.html']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
