# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div[@id='ProductDetail']/div/h1[@class='translated']",
    'price' : "//div[@class='DetailRow clearfix']/label/em/span/b",
    'category' : "//div[@class='breadcrumb clearfix']/ul/li/a",
    'description' : "//div[@class='tab-container fix_img']/div[@id='tabs1']",
    'images' : "//div[@class='ProductThumb']/div[@class='ProductThumbImage']/a/img/@src | //div[@class='ProductThumb']/div[@id='slideShow']/div[@class='carousel listImages']/ul/li/a/img/@src",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = 'chuyenhangduc.com'
allowed_domains = ['chuyenhangduc.com']
start_urls = ['http://chuyenhangduc.com']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow=['/san-pham+-p+\d+/[a-zA-Z0-9-_]+\.html']), 'parse_item'),
    Rule(LinkExtractor(allow=['/san-pham+-c+\d+/[a-zA-Z0-9-_]+\.html'], deny=['/tin-tuc.html','/Gioi-thieu.html','lien-he.html']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
