# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div[@id='content']/h1",
    'price' : "//div[@class='price']/span[@class='price-new']",
    'category' : "//div[@class='breadcrumb']/span/a/span",
    'description' : "//div[@id='tab-description']/p/text()",
    'images' : "//div[@class='image']//a/@href",
    'canonical' : "//link[@rel='canonical']/@href",
    'base_url' : "//base/@href",
    'brand' : ""
}
name = 'coupletx.com'
allowed_domains = ['coupletx.com']
start_urls = ['http://www.coupletx.com']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow = ['/[a-z0-9-]+-\d+.html'], deny=['/news-']), 'parse_item'),
    Rule(LinkExtractor(allow = ['/[a-zA-Z0-9-]+.html'], deny = ['/news-','gio-hang', 'huong-dan', 'lien-he', 'ban-si', 'gioi-thieu', 'tin-tuc', 'dieu-khoan', 'tuyen-dung', 'hoi-dap', 'sitemap']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
