# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div[@class='product-title']/h1",
    'price' : "//div[@id='wrapper-detail']/div[@class='row']/div/div[@class='product-price']/span",
    'category' : "//ol[@class='breadcrumb breadcrumb-arrow hidden-sm hidden-xs']/li/a",
    'description' : "//div[@id='wrapper-detail']/div[@class='row']/div/form[@class='variants clearfix']/p",
    'images' : "//div[@id='surround']/img[@class='product-image-feature']/@src",
    'canonical' : "//link[@rel='canonical']/@href",
    'base_url' : "",
    'brand' : "",
    'in_stock' : "",
    'guarantee' : "",
    'promotion' : ""
}
name = 'dacsandatphu.com'
allowed_domains = ['dacsandatphu.com']
start_urls = ['http://dacsandatphu.com/']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = ['']
rules = [
    Rule(LinkExtractor(allow=['/products/']), 'parse_item'),
    Rule(LinkExtractor(allow=['/collections/[a-zA-Z0-9-]+($|\?page=\d+$)']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
