# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div[@class='top1']/h1",
    'price' : "//div[@class='price-tranfer']//font/span[@class='price-sale']",
    'category' : "//div[@class='breadcrum']/a",
    'description' : "//div[@class='hdSudDetail'][1]/p",
    'images' : "//div[@class='cloud-zoom-first']/a/img/@src",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = 'dangdep247.com'
allowed_domains = ['dangdep247.com']
start_urls = ['http://dangdep247.com/']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow=['/[a-zA-Z0-9-]+\.html$']), 'parse_item'),
    Rule(LinkExtractor(allow=['/[a-zA-Z-0-9]+/$']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
