# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//h1[@class='product_title entry-title']",
    'price' : "//div[@class='summary entry-summary']/div/p[@class='price']/span[@class='amount']",
    'category' : "",
    'description' : "//div/div[@class='summary entry-summary']/div",
    'images' : "//div/div[@class='images']/a/img/@src",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = 'dartchocolate.com'
allowed_domains = ['dartchocolate.com']
start_urls = ['http://dartchocolate.com']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow=['/product/']), 'parse_item'),
    Rule(LinkExtractor(allow=['']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
