# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div[@class='top']/div[@class='center']/h1",
    'price' : "//div[@class='middle']/div[1]/table//tr/td[2]/table//tr[1]/td[2]",
    'category' : "",
    'description' : "//div[@class='middle']/div[@id='tab_description']",
    'images' : "//div[@class='middle']/div[1]/table//tr/td/a[@class='thickbox']/img[@id='image']/@src",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = 'dcshop.vn'
allowed_domains = ['dcshop.vn']
start_urls = ['http://dcshop.vn']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow=['/product+\&+path=+\d+\&+product_id=+\d+$']), 'parse_item'),
    Rule(LinkExtractor(allow=['/category+\&+path=+\d+$']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
