# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div[@class='pd_detail_top']/div[@class='info_detail right']/h3[@class='pd_title']",
    'price' : "//div[@class='pd_price']/span[@class='price_sale'] | //div[@class='pd_price']/span[@class='price']",
    'category' : "//div[@class='mainblock right']/ul[@class='menupage']/li[@class='current']/a",
    'description' : "//div[@class='page_pd_detail']/div[3]",
    'images' : "//div[@class='img_detail_big']/a/@href",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = 'dealhangmy.net'
allowed_domains = ['dealhangmy.net']
start_urls = ['http://dealhangmy.net']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow=['/san-pham/+\d+/']), 'parse_item'),
    Rule(LinkExtractor(allow=['/danh-muc-san-pham/']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
