# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//h1[@class='product_title']/a[2]",
    'price' : "//div[@id='product_desc']/span[@class='product_price'][1]",
    'category' : "//ul[@class='breadcrumb'][last()]/li[@class='list_breadcrumb']/a",
    'description' : "//div[@class='row']/div[@class='col-md-6'][1]",
    'images' : "//ul[@class='slides']/li/img/@src",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = 'deal18.vn'
allowed_domains = ['deal18.vn']
start_urls = ['http://deal18.vn/']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow = ['/deal/[a-zA-Z0-9-]+/\d+.html$']), 'parse_item'),
    Rule(LinkExtractor(allow = ['/deal/giam-gia/[a-zA-Z0-9-]+_\d+.html($|\?page=\d+$)'], deny=['color=','keyword=']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
