# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div[@class='sanpham-cnt']/span[@class='text18Bold']/h1",
    'price' : "//div/div[@class='sanpham-cnt-greenBox']/span[@class='sp-giaKM'] | //div[@class='sanpham-cnt-greenBox']/div[@id='div_don_gia_san_pham']/span[@class='sp-giaKM']",
    'category' : "//div/a/span",
    'description' : "//div[@class='content']/div[@class='content-info']/div[@class='pad10']",
    'images' : "//meta[@property='og:image']/@content | //div[@class='current_thumbnail']/div/a/@href",
    'canonical' : "//link[@rel='canonical']/@href",
    'base_url' : "",
    'brand' : ""
}
name = 'deca.vn'
allowed_domains = ['deca.vn']
start_urls = ['http://deca.vn']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow=['/[a-zA-Z0-9-]+-sp+[a-zA-Z0-9]+\.html']), 'parse_item'),
    Rule(LinkExtractor(allow=['/[a-zA-Z0-9-]+$']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
