# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div[@class='goodsCenter']/h1",
    'price' : "//div[@class='marketBox']/span[@id='ECS_SHOPPRICE']",
    'category' : "//div[@class='ur']/div[@class='ur_1']/a",
    'description' : "//div[@class='otherbox product-detail']",
    'images' : "//div[@class='goodImg']/center/a/@href",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = 'denlong.com'
allowed_domains = ['denlong.com']
start_urls = ['http://denlong.com/']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow=['/\d+/[a-zA-Z0-9-]+\.html$']), 'parse_item'),
    Rule(LinkExtractor(allow=['/\d+-b0/']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
