# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div[@class='product-right-info']/div[@class='name-product-detail']/span",
    'price' : "//div[@class='original-price']/span[@class='ori'] | //div[@class='price-timermart']/span[@id='price3']",
    'category' : "//div[@id='module2']/div[@class='pathway-category']/ul/li/a",
    'description' : "//div[@class='default-detail']/div[@id='product-info-related']",
    'images' : "//div[@id='product-detail']/div[@class='detail-cover']/table//tr/td[1]/div/div/div/a/img/@src",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = 'dep123.vn'
allowed_domains = ['dep123.vn']
start_urls = ['http://dep123.vn']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow=['/pr/+\d+/\d+/[a-zA-Z0-9-]+\.html']), 'parse_item'),
    Rule(LinkExtractor(allow=['/product/+\d+/+[a-zA-Z0-9-]+\.html']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
