# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div[@class='titleArticle']/h1",
    'price' : "//div[@class='main-price']/p[@class='big-text']/span[1] | //div[@class='productPrice']/span[@class='price_sold']",
    'category' : "//div[@class='nav-new']/ul/li/a",
    'description' : "//div[@id='tabbed_box_1']/div[@class='tabbed_area']",
    'images' : "//a[@class='thumb']/img/@src",
    'canonical' : "//link[@rel='canonical']/@href",
    'base_url' : "",
    'brand' : ""
}
name = 'diadiemvang.net'
allowed_domains = ['diadiemvang.net']
start_urls = ['http://www.diadiemvang.net']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = ['']
rules = [
    Rule(LinkExtractor(allow=['/deal/']), 'parse_item'),
    Rule(LinkExtractor(allow=['/[a-zA-Z0-9-]+\.html','/[a-zA-Z0-9-]+/','/hotdeal/'], deny=['blog.diadiemvang.net']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
