# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div[@class='detail-pro-1 detail-pro-item']/h1[@class='ten-chitiet']",
    'price' : "//div[@class='gia-chitiet']",
    'category' : "//div[@class='location title-detail']/a",
    'description' : "//div[@id='tab_info_detail']/div[@class='content_tab']",
    'images' : "//div[@class='anh-chitiet']/img/@src",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = 'didongmango.com'
allowed_domains = ['didongmango.com']
start_urls = ['http://didongmango.com']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow=['/p+\d+.*']), 'parse_item'),
    Rule(LinkExtractor(allow=['/c+\d+.*'], deny=['filter=']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
