# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div[@class='details-info']/h1",
    'price' : "//div[@class='info']/div[@class='right']/span[@class='price']/span",
    'category' : "//div[@id='RightmasterPageBody']/div[@id='large']/ul[@id='crumbs']/li/a",
    'description' : "//div[@class='tab-product-details']/div[@class='tab_container']",
    'images' : "//div[@class='details-img']/a/@href",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = 'dienmaythienphuc.vn'
allowed_domains = ['dienmaythienphuc.vn']
start_urls = ['http://dienmaythienphuc.vn/home.aspx']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow=['/product.aspx']), 'parse_item'),
    Rule(LinkExtractor(allow=['/home.aspx\?id=\d+']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
