# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div[@class='name']/h1",
    'price' : "//div[@class='vina_price']/p[@class='prod_price jshop_price']/span[@id='block_price']",
    'category' : "//ul[@class='breadcrumb ']/li/a[@class='pathway']",
    'description' : "//div[@class='tab-pane product-description active']/div[@class='tab-content active']",
    'images' : "//div[@class='main_image thumbnail']/img[@class='jshop_thumbnail']/@src",
    'canonical' : "",
    'base_url' : "//base/@href",
    'brand' : "",
    'in_stock' : "",
    'guarantee' : "",
    'promotion' : ""
}
name = 'diengiadung247.com'
allowed_domains = ['diengiadung247.com']
start_urls = ['http://diengiadung247.com/']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = ['']
rules = [
    #Rule(LinkExtractor(), 'parse_item'),
    #Rule(LinkExtractor(), 'parse'),
    Rule(LinkExtractor(allow=['/san-pham/.+\.html($|\?start=\d+$)']), 'parse_item_and_links'),
]
