# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div[@class='detailCont']/h1[@class='title']",
    'price' : "//div[@class='detailInfo']/div[@class='info']/div[@class='price']",
    'category' : "//div[@class='flowBehavior']/a",
    'description' : "//div[@class='overalInfo']/div[@class='wrap']/div[@class='row']/div/p",
    'images' : "//div[@class='detailImage']/img/@src",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = 'dienthoaididong.com'
allowed_domains = ['dienthoaididong.com']
start_urls = ['http://www.dienthoaididong.com/']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(), 'parse_item'),
    Rule(LinkExtractor(), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
