# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div[@class='div_box_center div_box_l_detailpro_center']/div[@class='div_main_product']/div[@class='div_col_right']/h1[@class='h1_title_main_product']",
    'price' : "//div[@class='div_main_product']/div[@class='div_col_right']/p[@class='p_text_main_product']/span[@class='s_price_main_product']",
    'category' : "//ul[@class='ul_path']/li/a/span",
    'description' : "//h2[@class='h2_description']",
    'images' : "//div[@id='carousel']/a/@href",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = 'dienmayviet.com.vn'
allowed_domains = ['dienmayviet.com.vn']
start_urls = ['http://dienmayviet.com.vn/']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = ['']
rules = [
    Rule(LinkExtractor(allow=['/[a-zA-Z0-9-]+-\d+\.html']), 'parse_item'),
    Rule(LinkExtractor(allow=['/[a-zA-Z0-9-]+-\d+s+\.html']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
