# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div[@class='entry-content']/div[@class='cpvg_postview_0_p15_post_id_cpvg_wp_postpage_id_1_container cpvg_field_item_container  cpvg_wp_postpage_id_container cpvg_field_post_ID_container']/div/a",
    'price' : "//div[@class='cpvg_postview_0_p15_postmeta_mp_price_cpvg_multiple_values_array_10_container cpvg_field_item_container  cpvg_multiple_values_array_container cpvg_field_postmeta_mp_price_container']/div",
    'category' : "",
    'description' : "//div[@class='entry-content']/div[@class='cpvg_postview_0_p15_post_post_content_cpvg_text_13_container cpvg_field_item_container  cpvg_text_container cpvg_field_post_post_content_container']/div",
    'images' : "//div[@id='wrap']/a/img/@src | //div[@class='cloud-zoom-gallery-nav']/a/img/@src",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = 'dienthoaiducxu.com'
allowed_domains = ['dienthoaiducxu.com']
start_urls = ['http://dienthoaiducxu.com']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(), 'parse_item'),
    Rule(LinkExtractor(), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
