# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//td/div[@class='tilesanpham']/a/h2",
    'price' : "//tr/td[@class='bovien']/b",
    'category' : "//ul/li/a/span",
    'description' : "//table/tbody/tr/td[@class='bovien']",
    'images' : "//tr/td/div[@class='asplv']/div[@class='targetarea']//img/@src",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = 'dienmaylongviet.vn'
allowed_domains = ['dienmaylongviet.vn']
start_urls = ['http://dienmaylongviet.vn']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow=['/[a-zA-Z0-9-]+-p+\.html']), 'parse_item'),
    Rule(LinkExtractor(allow=['/[a-zA-Z0-9-]+-c+\.html($|\?p=\d+$)']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
