# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div[@class='itemInfoList']/h1/strong",
    'price' : "//div[@class='itemInfoList']/form/ul/li/em[@id='ECS_SHOPPRICE']",
    'category' : "//div[@id='ur_here']/a",
    'description' : "//div[@class='bborder clearfix']/div[@id='com_v']/table//tr/td",
    'images' : "//div[@class='imgInfo']/a/img/@src | //div[@class='gallery']/div[@id='demo']/div[@id='demo1']/ul/li/a/img/@src",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = 'dienthoaihanoi.com'
allowed_domains = ['dienthoaihanoi.com']
start_urls = ['http://dienthoaihanoi.com']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow=['/g+\d+-.*']), 'parse_item'),
    Rule(LinkExtractor(allow=['/c+\d+-.*']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
