# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div[@id='single-top-right']/h1[@class='sgtitle']",
    'price' : "//ul/li/span[@class='price'] | //div[@class='tab_container']/div[1]/p[1]/span[1]",
    'category' : "//div[@id='bread']/div[@id='crumbs']/a",
    'description' : "//div[@id='motachitiet']/div[@id='motachitiet2']",
    'images' : "//div[@id='single-top-left']/div/a/@href | //meta[@property='og:image']/@content",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = 'dienthoaiben.com'
allowed_domains = ['dienthoaiben.com']
start_urls = ['http://dienthoaiben.com/']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow=['/san-pham']), 'parse_item'),
    Rule(LinkExtractor(allow=['/nhom-san-pham']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
