# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//h1",
    'price' : "//div[@class='product-price-pomotion']/p[@class='price-title'] | //div[@class='product-price-pomotion']/p[@class='price']",
    'category' : "//div[@class='product-category-path']/ul/li[2]/a",
    'description' : "//div[@id='content']/div[@class='pfr']/div[@class='pfr-l']",
    'images' : "//div[@class='image-large']/a/@href",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = 'dienmayrenhat.com'
allowed_domains = ['dienmayrenhat.com']
start_urls = ['http://dienmayrenhat.com']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow=['/p_detail/']), 'parse_item'),
    Rule(LinkExtractor(allow=['/p_category/']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
