# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div[@class='detailProduct']/div[@class='infoProduct']/h1",
    'price' : "//div[@class='abc']/div[@class='txPro ui-mark']/span[@id='_giasp']",
    'category' : "//div[@id='breadcum_wp']/ul[@id='bcrumb']/li/a",
    'description' : "//div[@id='thongtinchitiet']/div/div[@class='_mota']",
    'images' : "//div/ul[@id='mycarousel']/li/a/img/@src ",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = 'dienthoaigiagoc.com.vn'
allowed_domains = ['dienthoaigiagoc.com.vn']
start_urls = ['http://dienthoaigiagoc.com.vn']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(), 'parse_item'),
    Rule(LinkExtractor(), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
