# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//tr/td/div[@class='n_title']/font",
    'price' : "//tr/td/div[@class='price']/font",
    'category' : "//tr/td/div[@id='news']",
    'description' : "///tr/td/p",
    'images' : "//p/a/img/@src",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = 'dienhoavietmy.com'
allowed_domains = ['dienhoavietmy.com']
start_urls = ['http://dienhoavietmy.com']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow=['\.+\d+\.html']), 'parse_item'),
    Rule(LinkExtractor(allow=['/Cat']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
