# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//td[@class='product']/h3/strong",
    'price' : "//td[@class='product']/p[2]/span[@class='price']",
    'category' : "//td[@class='stext']",
    'description' : "//table[2]/tbody/tr[4]/td/table/tbody/tr[3]/td | //table/tbody/tr[3]/td/p",
    'images' : "//td[@width='50']/img/@src",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = 'dienmaytantien.vn'
allowed_domains = ['dienmaytantien.vn']
start_urls = ['http://dienmaytantien.vn']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow=['/detail.asp']), 'parse_item'),
    Rule(LinkExtractor(allow=['/category.asp']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
