# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div[@class='infoProduct']/h1[@class='tip']",
    'price' : "//div[@class='txPro ui-mark']/span[@id='_giasp']",
    'category' : "//div[@class='brc_con']/ul[@class='bc-menu']/li/a",
    'description' : "//div[@class='_tab-06 tab_link-02_01 boder_ttct hide']/div[@class='_mota']",
    'images' : "//div[@class='small-img']//img/@src | //div[@class='jcarousel-clip jcarousel-clip-horizontal']/ul[@id='mycarousel']//a/@data-zoom-image",
    'canonical' : "//link[@rel='canonical']/@href",
    'base_url' : "",
    'brand' : ""
}
name = 'dienmaygiahan.com'
allowed_domains = ['dienmaygiahan.com']
start_urls = ['http://dienmaygiahan.com/']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(), 'parse_item'),
    Rule(LinkExtractor(), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
