# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//table[@class='tb_product_detail']//tr/td/div[@id='pro_name_head']/h1",
    'price' : "//div[@class='price_info']/p[@class='price1']/span | //div[@class='price_info']/p[@class='price2']/span",
    'category' : "//div[@class='cent_tit'][1]/a",
    'description' : "//div[@class='block_content']/div[3]/div[3]/div",
    'images' : "//div[@id='productImageBox']/a/img/@src",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = 'dienthoaigiare.vn'
allowed_domains = ['dienthoaigiare.vn']
start_urls = ['http://dienthoaigiare.vn']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(), 'parse_item'),
    Rule(LinkExtractor(), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
