# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div[@class='image-right']/h1[@class='title']",
    'price' : "//div[@class='image-right']/div[@class='chitiet']/span[@class='price']",
    'category' : "//div[@id='product-detail']/div[1]/a",
    'description' : "//div[@class='tabbed_area']/div[@id='Accessories']",
    'images' : "//div[@id='detail-image']/div[@class='image-left']/img/@src",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = 'dienmaytrangia.com.vn'
allowed_domains = ['dienmaytrangia.com.vn']
start_urls = ['http://dienmaytrangia.com.vn']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow=['/san-pham/']), 'parse_item'),
    Rule(LinkExtractor(allow=['/danh-muc+-\d+/'], deny=['www.nhatphuviet.com']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
