# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div[@class='clearfix']/form[@class='cm-disable-empty-files cm-required-form cm-ajax cm-ajax-render-current']/div[@class='product-info']/h1[@class='mainbox-title']",
    'price' : "//p[@class='actual-price']/span/span/span",
    'category' : "//div[@class='grid_12 alpha omega']/div[@id='breadcrumbs_65']/div[@class='breadcrumbs clearfix']/a",
    'description' : "//div[@class='grid_12 alpha omega']/div[@class='product-main-info']/div[@id='tabs_content']/div[@id='content_description']",
    'images' : "//div[@class='clearfix']/form[@class='cm-disable-empty-files cm-required-form cm-ajax cm-ajax-render-current']/div//img/@src",
    'canonical' : "",
    'base_url' : "//base/@href",
    'brand' : ""
}
name = 'dienmaylepham.com'
allowed_domains = ['dienmaylepham.com']
start_urls = ['http://dienmaylepham.com']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow=['/[a-zA-Z0-9-]+\.html']), 'parse_item'),
    Rule(LinkExtractor(allow=['/[a-zA-Z0-9-]+/']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
