# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div[@class='product_detail']/h2",
    'price' : "//p[@class='price_product_black']/span",
    'category' : "",
    'description' : "//div[@class='button_product']/p[2]",
    'images' : "//table[@class='icon_cell']//td/img/@src",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = 'dienhoatructuyen.vn'
allowed_domains = ['dienhoatructuyen.vn']
start_urls = ['http://dienhoatructuyen.vn']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow = ['/items/[a-zA-Z-]+-\d+']), 'parse_item'),
    Rule(LinkExtractor(allow = ['/items/topic/[a-zA-Z-]+']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
