# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//h1[@class='title']/span",
    'price' : "//div[@class='price']/b",
    'category' : "//ul[@class='breadcrumb']/li/a",
    'description' : "//div[@class='product-info clearfix']/div[@class='tab-content']",
    'images' : "//div[@class='image-product span4']/a/img/@src",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = 'digicenter.vn'
allowed_domains = ['digicenter.vn']
start_urls = ['http://digicenter.vn']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow=['/\d+-[a-z-]+/[a-zA-Z0-9-]+\.html']), 'parse_item'),
    Rule(LinkExtractor(allow=['/\d+-[a-z-]+/\d+-[a-zA-Z0-9-]+\.html']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
