# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div[@class='product-detail-content product-detail']/h2[@class='title_content']",
    'price' : "//div[@class='bottom']/div[@class='select']/label/text()",
    'category' : "",
    'description' : "",
    'images' : "//div[@class='top']//img/@src",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = 'dinhcaocongnghe.com'
allowed_domains = ['dinhcaocongnghe.com']
start_urls = ['http://dinhcaocongnghe.com/']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(), 'parse_item'),
    Rule(LinkExtractor(), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
