# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div[@class='wrap-detail']/h1",
    'price' : "//div[@class='wrap-detail']/div[@class='share']/p[10]/span",
    'category' : "",
    'description' : "//div[@class='detail']/div[@class='tabs']/div[@id='first']",
    'images' : "//div[@class='multizoom1 thumbs']/a/img/@src",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = 'dman.vn'
allowed_domains = ['dman.vn']
start_urls = ['http://dman.vn']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(), 'parse_item'),
    Rule(LinkExtractor(), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
