# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div[@id='overview']/h1",
    'price' : "//div[@id='overview']/div[@class='l']/div[@class='price_pro_detail']",
    'category' : "//div[@id='content']/div[@id='location']/a",
    'description' : "//div[@id='content_left']/div[@id='detail_product']/p",
    'images' : "//div[@id='img_product']/ul[@id='img_thumb']/li/a/@href",
    'canonical' : "",
    'base_url' : "",
    'brand' : "",
    'in_stock' : "",
    'guarantee' : "",
    'promotion' : ""
}
name = 'doboihuongdiep.vn'
allowed_domains = ['doboihuongdiep.vn']
start_urls = ['http://doboihuongdiep.vn/']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = ['']
rules = [
    Rule(LinkExtractor(allow=['/p\d+\.html$']), 'parse_item'),
    Rule(LinkExtractor(allow=['/c\d+\.html($|\?page=\d+$)']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
