# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div[@class='product-detailts']/h1",
    'price' : "//div[@class='PricesalesPrice']/span",
    'category' : "",
    'description' : "//div[@class='otcustom-tabs']/div[@class='current']/dd",
    'images' : "//div[@id='large_image_holder']/ul[@id='large_images']/li/a/@href",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = 'dochoivn.com'
allowed_domains = ['dochoivn.com']
start_urls = ['http://dochoivn.com']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(), 'parse_item'),
    Rule(LinkExtractor(), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
