# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//h1",
    'price' : "//span[@class='giabande']",
    'category' : "//div[@class='contentit_trai']/span/a",
    'description' : "//div[@class='khungcarttt']",
    'images' : "//a[@class='jqzoom']/@href",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = 'dogohay.vn'
allowed_domains = ['dogohay.vn']
start_urls = ['http://dogohay.vn/']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow=['/san-pham/']), 'parse_item'),
    Rule(LinkExtractor(allow=['-dm\d+\.html']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
