# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div[@class='product-detail']/div[@class='product-details-inner']/div[@class='product-info-3']/h3",
    'price' : "//div[@class='product-details-inner']/div[@class='product-info-3']/div[@class='price']/span[@class='pro_price']",
    'category' : "//div[@class='title']/ul[@class='breadcrumd']/li/a",
    'description' : "//div[@class='tab-pro-spec tabContent contEditor ']",
    'images' : "//li[@class='current']/a/@href|//div[@class='photos-zoom']/a/@href",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = 'donghohieu24h.com'
allowed_domains = ['donghohieu24h.com']
start_urls = ['https://donghohieu24h.com']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = ['']
rules = [
    Rule(LinkExtractor(allow=['/san-pham/']), 'parse_item'),
    Rule(LinkExtractor(allow=['/product-groups/']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
