# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div[@class='info_pro']/h2",
    'price' : "//div[@class='info_pro']/p[@class='about_sp top_detail']/font",
    'category' : "//div[@class='title_productdetail']/h1/a",
    'description' : "",
    'images' : "//div[@class='images_detail']/img/@src",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = 'donghohungtien.com'
allowed_domains = ['donghohungtien.com']
start_urls = ['http://donghohungtien.com']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow=['/detail/']), 'parse_item'),
    Rule(LinkExtractor(allow=['/san-pham+/\d+/']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
