# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//span[@class='Product_Detail_Name']",
    'price' : "//table//tr[5]/td[2]/span[@class='Product_Detail_Price']",
    'category' : "//div[@itemprop='breadcrumb']/div/a[1]",
    'description' : "//tr[@id='ctl00_cphMain_Detail1_uDetail_trContent']/td",
    'images' : "//div[@class='Product_Detail']/table/tr/td[1]/img/@src",
    'canonical' : "",
    'base_url' : "",
    'brand' : "",
    'in_stock' : "",
    'guarantee' : ""
}
name = 'doremii.vn'
allowed_domains = ['doremii.vn']
start_urls = ['http://doremii.vn/']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = ['']
rules = [
    Rule(LinkExtractor(allow=['/san-pham/[\w-]+/\d+/[\w-]+/$']), 'parse_item'),
    Rule(LinkExtractor(allow=['/san-pham/.+/($|\?pi=\d+$)']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
