# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "",
    'price' : "",
    'category' : "",
    'description' : "",
    'images' : "",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = 'ducvietco.com'
allowed_domains = ['ducvietco.com']
start_urls = ['http://ducvietco.com']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(), 'parse_item'),
    Rule(LinkExtractor(), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
