# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//h1[@class='title']",
    'price' : "//div[@id='listPreItem']//div/span",
    'category' : "//div[@class='breadcrumb']/a",
    'description' : "//div[@class='detailTab'][1]",
    'images' : "//div[@class='view-image']/a[@id='zoom']/@href",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = 'ebest.vn'
allowed_domains = ['ebest.vn']
start_urls = ['http://ebest.vn']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow = ['/san-pham+/p-+\d+/']), 'parse_item'),
    Rule(LinkExtractor(allow = ['/danh-muc/'], deny=['/rss/']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
