# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div[@class='span8']/div[@class='product-shop']/div[@class='product-name']/h1",
    'price' : "//div[@class='product-shop']/div[@class='price-box']/span/span[@class='price']|//div[@class='product-shop']/div[@class='price-box']/p[@class='special-price']/span[@class='price']",
    'category' : "//div[@class='breadcrumbs']/ul/li/a",
    'description' : "//div[@class='product-view']/div[@class='product-collateral']/div[@class='std']/p",
    'images' : "//li/a[@class='cloud-zoom-gallery']/@href",
    'canonical' : "//link[@rel='canonical']/@href",
    'base_url' : "//input[@id='base_url']/@value",
    'brand' : ""
}
name = 'esoop.net'
allowed_domains = ['esoop.net']
start_urls = ['http://esoop.net']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow=['/\w+\d+-[a-zA-Z0-9-]+\.html$']), 'parse_item'),
    Rule(LinkExtractor(allow=['/[a-zA-Z-]+[/a-zA-Z-]*\.html']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
