# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div[@id='product']/h1",
    'price' : "//div[@id='price']/strong[@id='priceValue']",
    'category' : "//div[@id='product']/h4/a",
    'description' : "//div[@id='product']/div[@class='content']",
    'images' : "//img[@id='imgPreview']/@src",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = 'etop.com.vn'
allowed_domains = ['etop.com.vn']
start_urls = ['http://www.etop.com.vn/']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow=['/\?\d+,[a-zA-Z0-9-]+$']), 'parse_item'),
    Rule(LinkExtractor(allow=['/\?[a-zA-Z0-9-]+(,\d+)*'], deny=['gio-hang','&']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
