# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "/html/body/div[@class='fullheader']/div[@id='container']/div[@id='container']/div[@id='content']/div[@class='product-info']/div[@class='right']/div[@class='description']/div[@class='product_title']/h1",
    'price' : "/html/body/div[@class='fullheader']/div[@id='container']/div[@id='container']/div[@id='content']/div[@class='product-info']/div[@class='right']/div[@class='thongtinkhac']/div[@class='thongtinkhac_1']/div[@class='price']/span[@class='price-none']",
    'category' : "/html/body/div[@class='fullheader']/div[@id='container']/div[@id='container']/div[@id='content']/div[@class='breadcrumb']/a",
    'description' : "/html/body/div[@class='fullheader']/div[@id='container']/div[@id='container']/div[@id='content']/div[@id='tab-description']",
    'images' : "/html/body/div[@class='fullheader']/div[@id='container']/div[@id='container']/div[@id='content']/div[@class='product-info']/div[@class='left']/div[@class='image']//a/@href",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = 'eva247.com'
allowed_domains = ['eva247.com']
start_urls = ['http://eva247.com']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow=['']), 'parse_item'),
    Rule(LinkExtractor(allow=['']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
