# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "/html/body/div/div/div/div[@class='content']/div[@class='wrap-page-3'][2]/div[@class='page-content nb4']/div/div[@class='nav-boxDetail']/div[@class='boxlayout-info nb3'][2]/div[@class='info-pr'][2]/span[@class='info-nameN'][2]/h1",
    'price' : "/html/body/div/div/div/div[@class='content']/div[@class='wrap-page-3'][2]/div[@class='page-content nb4']/div/div[@class='nav-boxDetail']/div[@class='boxlayout-info nb3'][2]/div[@class='info-pr'][2]/div[@class='box-ps']/span[@class='info-namePrice']",
    'category' : "/html/body/div/div/div/div[@class='content']/div/div[@class='navigation']/div[@class='crust-out'][2]/a[@class='crust']/span",
    'description' : "/html/body/div/div/div/div[@class='content']/div[@class='wrap-page-3'][2]/div[@class='page-content nb4']/div/div[@class='nav-boxDetail'][2]/div[@class='tab_container']/div",
    'images' : "/html/body/div/div/div/div[@class='content']/div[@class='wrap-page-3'][2]/div[@class='page-content nb4']/div/div[@class='nav-boxDetail']/div[@class='boxlayout-l']/div/div[@class='prd-moreImagesList']/div/ul/li[2]/a/@href",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = 'f24.com.vn'
allowed_domains = ['f24.com.vn']
start_urls = ['http://f24.com.vn']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow=['/[a-zA-Z0-9-]+\.[a-z]']), 'parse_item'),
    Rule(LinkExtractor(allow=['/[a-zA-Z0-9-]+/+$']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
