# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div[@class='product-detail-info']/div[@class='cssName']/h1",
    'price' : "//div[@class='product-detail-info']/div[@class='cssPrice'][1]",
    'category' : "//div[@class='category-path']/a",
    'description' : "//div[@id='pro_content_desc']/p",
    'images' : "//div[@class='prod_img cor']/div[@class='prod_img_in']//img/@src",
    'canonical' : "//link[@rel='canonical']/@href",
    'base_url' : "",
    'brand' : ""
}
name = 'f5pro.vn'
allowed_domains = ['f5pro.vn']
start_urls = ['http://f5pro.vn']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow=['/product+-\d+/']), 'parse_item'),
    Rule(LinkExtractor(allow=['/category+-\d+/']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
