# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//h2[@class='header  headline']/span/label",
    'price' : "//span[@class='giavnd']",
    'category' : "",
    'description' : "//div[@class='mo_ta_sanpham']",
    'images' : "//div[@class='div_anh_chi_tiet']/a/@href",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = 'facioshop.com'
allowed_domains = ['facioshop.com']
start_urls = ['http://facioshop.com']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow=['/ct/+.*']), 'parse_item'),
    Rule(LinkExtractor(allow=['/sp/+.*']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
