# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div[@class='product-name']/h1",
    'price' : "//div[@class='product-img-box col-md-4 col-sm-12 col-sms-12']/div[@class='price-box']/p[@class='special-price']/span[@class='price']",
    'category' : "//ol[@class='breadcrumb']/li/a",
    'description' : "//div[@class='product-shop-inner']/div[@class='short-description']",
    'images' : "//img[@class='fhs-p-img']/@src",
    'canonical' : "//link[@rel='canonical']/@href",
    'base_url' : "",
    'brand' : "",
    'in_stock' : "//div[@class='view-rate']/p[@class='availability in-stock']/span",
    'guarantee' : "",
    'promotion' : ""
}
name = 'fahasa.com'
allowed_domains = ['fahasa.com']
start_urls = ['https://www.fahasa.com/']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = ['']
rules = [
    #Rule(LinkExtractor(allow=['/[a-zA-Z0-9-]+\.html($|\?p=\d+$)']), 'parse_item'),
    #Rule(LinkExtractor(), 'parse'),
    Rule(LinkExtractor(allow=['/[a-zA-Z0-9-]+\.html($|\?p=\d+$)']), 'parse_item_and_links'),
]
