# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//section[@class='Product']/section[@id='Product-Row-1']/div[@class='col-xs-12 col-sm-9 col-md-9 col-lg-9']/span[@class='ProductNameLink']/h1",
    'price' : "//div[@class='col-xs-12 col-sm-9 col-md-9 col-lg-9']/div[@class='row']/div[@id='Product-Midle']/span[@class='ProductPriceNew']",
    'category' : "//ul[@class='col-xs-12']/li[@class='list-unstyled pull-left']/h2/a",
    'description' : "//div[@class='col-xs-12 col-sm-9 col-md-9 col-lg-9']/div[@class='row']/div[@id='Product-Midle']/article[@id='Context']",
    'images' : "//img[@id='thumb']/@src",
    'canonical' : "",
    'base_url' : "//base/@href",
    'brand' : ""
}
name = 'faxpanasonic.com'
allowed_domains = ['faxpanasonic.com']
start_urls = ['http://faxpanasonic.com']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow=['/[a-zA-Z0-9-_]+-\d+\.html']), 'parse_item'),
    Rule(LinkExtractor(allow=['/\.*']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
