# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div[@class='product_name']/h2",
    'price' : "//div[@id='product_price']/p/span[@class='money']",
    'category' : "//ul[@class='breadcrumb']/li/span[@class='page-title']",
    'description' : "//div[@class='product_wrap']/div/p",
    'images' : "//div[@class='product_wrap']//div/img/@src",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = 'fmstyle.com.vn'
allowed_domains = ['fmstyle.com.vn']
start_urls = ['http://fmstyle.com.vn/trang-chu.html']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = ['']
rules = [
    Rule(LinkExtractor(allow=['/[\w\d]+\w[\w\d]+-[a-zA-Z0-9-]+']), 'parse_item'),
    Rule(LinkExtractor(allow=['/\d+-[a-zA-Z0-9-]+']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
