# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div[@class='prod_header_title']/h1[@id='prod_title']",
    'price' : "//div[@class='prod_pricebox_price_final']/span[@id='special_price_box']",
    'category' : "//div[@class='header__breadcrumb__wrapper']/ul/li/h3/a",
    'description' : "//div[@class='product-description__block']/p",
    'images' : "//div[@id='productImageBox']//span/@data-zoom-image",
    'canonical' : "//link[@rel='canonical']/@href",
    'base_url' : "",
    'brand' : ""
}
name = 'fyi.vn'
allowed_domains = ['fyi.vn']
start_urls = ['https://www.fyi.vn']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow=['/[a-zA-Z0-9-]+\.html']), 'parse_item'),
    Rule(LinkExtractor(allow=['/[a-zA-Z0-9-]+/']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
