# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div[@class='f-product-view-name']/h1/span",
    'price' : "//ul[@class='no-margin no-padding']/li[@class='value'][2]/span[@class='price']",
    'category' : "//div[@class='productbreadcrumb']/ol[@class='breadcrumb']/li/a",
    'description' : "//div[@class='f-product-view-tab']/div[@class='f-product-view-tab-body tab-content']",
    'images' : "//div[@class='zoomWrapper']/img/@src",
    'canonical' : "",
    'base_url' : "//base/@href",
    'brand' : "",
    'in_stock' : "",
    'guarantee' : "",
    'promotion' : ""
}
name = 'gagoionline.com'
allowed_domains = ['gagoionline.com']
start_urls = ['http://gagoionline.com/product.html']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = ['']
rules = [
    Rule(LinkExtractor(allow=['/[a-zA-Z0-9-]+-1-1-\d+\.html$']), 'parse_item'),
    Rule(LinkExtractor(allow=['/product(-p\d+)?\.html$']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
