# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//thead/tr/td/h4",
    'price' : "//table[@class='table table-striped product-detail-attribute']//tr[5]/td[@class='text-left'][2]",
    'category' : "",
    'description' : "",
    'images' : "//img[@class='cloudzoom']/@src",
    'canonical' : "//link[@rel='canonical']/@href",
    'base_url' : "//base/@href",
    'brand' : "",
    'in_stock' : "",
    'guarantee' : ""
}
name = 'gal.com.vn'
allowed_domains = ['gal.com.vn']
start_urls = ['http://gal.com.vn/']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = ['']
rules = [
    Rule(LinkExtractor(allow=['/\d+/$']), 'parse_item'),
    Rule(LinkExtractor(allow=['/[\w-]+/$'], deny=['/\d+/$']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
