# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//h1[@class='color2']",
    'price' : "//div[@class='dpt-status'][2]/span[@class='dpt-price'] | //div[@class='dpt-status']/span[@class='dpt-price']",
    'category' : "//div[@id='path-way']/a",
    'description' : "//table/tbody/tr/td",
    'images' : "//div[@id='dp-thumb']//a/@href",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = 'gallewatch.com'
allowed_domains = ['gallewatch.com']
start_urls = ['http://www.gallewatch.com/']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow=['/[^(f0)][a-zA-Z0-9-]+\d+.*\.html$']), 'parse_item'),
    Rule(LinkExtractor(allow = ['/[a-zA-Z-]+\.html($|\?page)']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
