# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div[@id='container']/div[@class='wrapper']/div[@id='wrapper']/div[@id='content']/h2",
    'price' : "//div[@class='field field-type-date field-field-sell-price']/div[@class='field-items']/div[@class='field-item']/span",
    'category' : "//div[@id='breadcrumb']/div[@class='breadcrumb']/b/a",
    'description' : "//div[@class='content clear-block']/div[@class='body_content'] | //div[@class='body_content']/p",
    'images' : "//div[@class='product-image']/a/@href",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = 'gbook.vn'
allowed_domains = ['gbook.vn']
start_urls = ['http://www.gbook.vn']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow=['/node/']), 'parse_item'),
    Rule(LinkExtractor(allow=['/catalog/\d+($|\?page=\d+)']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
