# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//h1",
    'price' : "//div[@id='price-column']/div[@class='product-extra']/div[@class='price']/text()",
    'category' : "//div[@id='breadcrumb']/ol[@class='breadcrumb']/li/a",
    'description' : "//div[@class='description']/p",
    'images' : "//div[@class='product-info']//a/img/@src",
    'canonical' : "//link[@rel='canonical']/@href",
    'base_url' : "//base/@href",
    'brand' : ""
}
name = 'genviet.com'
allowed_domains = ['genviet.com']
start_urls = ['http://genviet.com/']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = ['']
rules = [
    Rule(LinkExtractor(allow=['route=product/product']), 'parse_item'),
    Rule(LinkExtractor(allow=['route=product/category.+path=\d+($|.+page=\d+$)']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
