# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div[@class='content-body']/h1[@class='page-heading']",
    'price' : "//div[@class='price-info']/div[@class='price-wrp']",
    'category' : "//div[@class='breadcrumb']/a",
    'description' : "//div[@id='tab-description']/div",
    'images' : "//div[@class='image-wrp']/div/a/img/@data-zoom-image",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = 'ghengoibet.vn'
allowed_domains = ['ghengoibet.vn']
start_urls = ['http://ghengoibet.vn']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow=['/[a-zA-Z0-9-]+-\d+$']), 'parse_item'),
    Rule(LinkExtractor(allow=['/[a-zA-Z-]+$']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
