# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div[@class='text-ct-product']/h1",
    'price' : "//div[@class='text-ct-product']/span[@class='price-detail-product']",
    'category' : "",
    'description' : "//div[@class='product']/div[@id='thongso-kythuat']",
    'images' : "//div[@class='img-ct-product']/div[@class='image']/img/@src",
    'canonical' : "//link[@rel='canonical']/@href",
    'base_url' : "//base/@href",
    'brand' : ""
}
name = 'ghettre.com'
allowed_domains = ['ghettre.com']
start_urls = ['http://ghettre.com/']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow=['/[a-zA-Z0-9-]+\.html$']), 'parse_item'),
    Rule(LinkExtractor(allow=['dien-thoai','may-tinh-bang','phu-kien','smartwatch']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
