# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div[@id='image']/h1",
    'price' : "//div[@id='image']/font/b",
    'category' : "//div[@class='idx-prod']/h3/a[position()>1]",
    'description' : "//div[@id='detail']/p[1]/span",
    'images' : "//a[@class='preview']/img/@src",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = 'ghexoayvanphong.vn'
allowed_domains = ['ghexoayvanphong.vn']
start_urls = ['http://www.ghexoayvanphong.vn/']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow=['/i\d+-']), 'parse_item'),
    Rule(LinkExtractor(allow=['/c\d+-']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
