# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div/div[@class='product_detail_info right']/div/h1[@class='product_name']",
    'price' : "//div[@class='product_detail_info right']/div/div[@class='price_list_']/span",
    'category' : "//div[@class='path_left clear']/div[@class='breadcrumb']/span[@class='navigation_page']/a",
    'description' : "//div[@id='content_1']/p/span",
    'images' : "//div[@id='gallery']/a/@href | //div[@id='proImageThum']/div/a/img/@src",
    'canonical' : "//link[@rel='canonical']/@href",
    'base_url' : "",
    'brand' : ""
}
name = 'giabaovn.vn'
allowed_domains = ['giabaovn.vn']
start_urls = ['http://giabaovn.vn']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow=['/\d+-[a-zA-Z0-9-]+\.html']), 'parse_item'),
    Rule(LinkExtractor(allow=['/c+\d+/']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
