# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//h2[@class='title-detial-pr']",
    'price' : "//span[@class='price-total']",
    'category' : "//div[@class='breadcrumb']/a/text()",
    'description' : "//div[@id='tab11']",
    'images' : "//a[@class='lightbox']/img/@src",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = 'giamcan24h.com'
allowed_domains = ['giamcan24h.com']
start_urls = ['http://giamcan24h.com']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow = ['/Giam-can/[a-zA-Z-0-9-]+/[a-zA-Z-0-9-]+.aspx']), 'parse_item'),
    Rule(LinkExtractor(allow = ['/Giam-can/[a-zA-Z-0-9-]+.aspx']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
