# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//*[@class='name-produt']",
    'price' : "//table[@class='tbl-product-detail']//tr[4]/td[2] | //table[@class='tbl-product-detail']/tr[3]/td[2]/text()",
    'category' : "",
    'description' : "//table[@class='tbl-product-detail']//tr[5]/td",
    'images' : "//div[@class='cata-border-pro-img-center']/a/@href",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = 'giaycao.com'
allowed_domains = ['giaycao.com']
start_urls = ['http://giaycao.com']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow = ['/san-pham/']), 'parse_item'),
    Rule(LinkExtractor(allow = ['/danh-muc/']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
