# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//h1",
    'price' : "//div[@class='details']/div[@class='product-act']/div[@class='price-box']/p[@class='special-price']/span[@class='price']|//div[@class='details']/div[@class='product-act']/div[@class='price-box']/span[@class='regular-price']/span[@class='price']",
    'category' : "//div[@class='breadcrumbs breadcrums']/ul/li/a",
    'description' : "//div[@id='desc']/div[@class='std']",
    'images' : "//img[@class='media-images']/@src",
    'canonical' : "//link[@rel='canonical']/@href",
    'base_url' : "",
    'brand' : ""
}
name = 'giaytot.com'
allowed_domains = ['giaytot.com']
start_urls = ['http://www.giaytot.com/']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow=['/[a-zA-Z0-9-]+-\d+\.html$']), 'parse_item'),
    Rule(LinkExtractor(allow=['/[a-zA-Z0-9-]+\.html($|\?p=\d+)']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
