# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div[@class='content_detail_right_child1']/h3",
    'price' : "//div[@class='content_detail_right_child2_share'][2]/p[2]/b[2]",
    'category' : "",
    'description' : "//div[@class='content_detail_right_child3_dacdiemnoibat']/ul/li",
    'images' : "//div[@u='slides']//img/@src",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = 'giaydepxinh.com.vn'
allowed_domains = ['giaydepxinh.com.vn']
start_urls = ['http://giaydepxinh.com.vn/']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow=['/san-pham-giam-gia/\d+-.+\.html$']), 'parse_item'),
    Rule(LinkExtractor(allow=['/danh-muc-san-pham/\d+']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
