# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div[@class='col-md-6'][2]/div[@class='title_main']",
    'price' : "//div[@class='row']/div[@class='wrap_detail']/div[@class='price']",
    'category' : "//div[@class='col_right col-md-9']/a",
    'description' : "//div[@class='panel-body']",
    'images' : "//div[@class='item']/a/@href",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = 'giaydimuagiare.com'
allowed_domains = ['giaydimuagiare.com']
start_urls = ['http://giaydimuagiare.com/vn/san-pham/']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow=['/san-pham/details/']), 'parse_item'),
    Rule(LinkExtractor(allow=['/san-pham/[a-zA-Z0-9-]+/($|p/\d+)']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
