# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//h1[@class='pd_title']",
    'price' : "//form[@id='buy_info']/span[@class='price']",
    'category' : "//ul[@class='menupage']/li/a",
    'description' : "//div[@class='pd_sum']/p[@class='pd_sum_ctn']",
    'images' : "//div[@class='img_detail_big']/a/@href",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = 'glenndomanvietnam.com'
allowed_domains = ['glenndomanvietnam.com']
start_urls = ['http://glenndomanvietnam.com/']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(), 'parse_item'),
    Rule(LinkExtractor(), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
