# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//li[@class='active last']",
    'price' : "//div[@class='product-info sell-price']/span[@class='uc-price']",
    'category' : "//div[@class='col-md-9 col-sm-8 content-page']/ol[@class='breadcrumb']/li/a",
    'description' : "//div[@class='tab-content']",
    'images' : "//div[@class='product-color-0 thumbs processed']/div/div/a/@data-large",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = 'gurkha.vn'
allowed_domains = ['gurkha.vn']
start_urls = ['http://gurkha.vn/']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow=['/vi/[a-zA-Z-]+/[a-zA-Z-]+/[a-zA-Z-]+$']), 'parse_item'),
    Rule(LinkExtractor(allow=['/vi/[a-zA-Z-]+/*[a-zA-Z-]*$'], deny=['showroom|chung-toi|g-club|huong-dan|quy-dinh|bao-mat|tu-van-ve-do-da|cau-hoi-thuong-gap']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
