# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div[@class='ty-product-block__left']/form/div[@class='ty-product-block-title'] | //h1[@class='ty-mainbox-title']",
    'price' : "//p[@class='actual-price']/span/span/span[1]",
    'category' : "//div[@class='ty-breadcrumbs clearfix']/a",
    'description' : "//div[@id='content_description']/div | //div[@id='content_description']/ul/li | //div[@id='content_description']/p | //div[@id='content_description']/table",
    'images' : "//div[@class='ty-product-img cm-preview-wrapper']/a/@href",
    'canonical' : "//link[@rel='canonical']/@href",
    'base_url' : "//base/@href",
    'brand' : ""
}
name = 'h2shop.vn'
allowed_domains = ['h2shop.vn']
start_urls = ['http://www.h2shop.vn/']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow = ['/[a-zA-Z0-9-_]+\.html']), 'parse_item'),
    Rule(LinkExtractor(allow = ['/[a-zA-Z0-9-]+/'], deny=['layout=','sort_by=']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
