# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//h1",
    'price' : "//div[@class='product-price-pomotion']/p[@class='price']",
    'category' : "//div[@class='product-category-path']/ul[@class='list-item']/li/a",
    'description' : "//div[@class='pr-l-snv-i active']",
    'images' : "//div[@id='gallery']/a/@href",
    'canonical' : "",
    'base_url' : "",
    'brand' : "",
    'in_stock' : "",
    'guarantee' : ""
}
name = 'haiphongtelecom.com'
allowed_domains = ['haiphongtelecom.com']
start_urls = ['http://haiphongtelecom.com/']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = ['']
rules = [
    #Rule(LinkExtractor(), 'parse_item'),
    #Rule(LinkExtractor(), 'parse'),
    Rule(LinkExtractor(allow=['/[a-zA-Z0-9-]+\.html($|\?page=\d+&sort=goods_id&order=DESC#goods_list$)']), 'parse_item_and_links'),
]
