# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div[@id='title_detail']",
    'price' : "//div[@class='d-price']",
    'category' : "//div[@class='navigate']/div[@class='C']/a",
    'description' : "//div[@id='tabContent']/div[@id='DivContentDetail']/p",
    'images' : "//div[@class='clearfix']/a/@href",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = 'haiphong247.vn'
allowed_domains = ['haiphong247.vn']
start_urls = ['http://haiphong247.vn/']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = ['']
rules = [
    Rule(LinkExtractor(allow=['/san-pham/[a-zA-Z0-9-]+-\d+-\d+$']), 'parse_item'),
    Rule(LinkExtractor(allow=['/danh-muc/[a-zA-Z0-9-]+-\d+']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
