# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div[@class='productDetail']/div[@class='detailRight']/div[@class='detailLeft']/h1",
    'price' : "//ul[@class='otherRoot']/li/span[@class='price']",
    'category' : "//div[@class='lastitem']/a/span",
    'description' : "//div[@class='pITabContent'][1]/div[@class='cf_content']",
    'images' : "//div[@class='gallery_catalog']/div[@class='image_large']/a/@href",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = 'hangnhapmy.com.vn'
allowed_domains = ['hangnhapmy.com.vn']
start_urls = ['http://hangnhapmy.com.vn']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow=['/[a-zA-Z0-9-]+\.htm']), 'parse_item'),
    Rule(LinkExtractor(allow=['/[a-zA-Z0-9-]+-\d+/+$']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
