# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//title",
    'price' : "//ul[@id='chitietsanpham']/li/span[@id='ctl00_ContentPlaceHolder1_lbGiaBan']",
    'category' : "//div[@class='pageHeader']/ul/li/a",
    'description' : "",
    'images' : "//div[@id='slides']/div[@class='slide']/img/@src",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = 'hangnhapkhauthailan.com'
allowed_domains = ['hangnhapkhauthailan.com']
start_urls = ['http://www.hangnhapkhauthailan.com']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow=['/items+/\d+/']), 'parse_item'),
    Rule(LinkExtractor(allow=['/subcat+/\d+/']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
