# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div[@class='section product-single']//div[@class='product-info clearfix']/h4[@class='title']",
    'price' : "//div[@class='section product-single']//div[@class='description']/div[@class='prices']/span[@class='off-price']",
    'category' : "//div[@class='breadcrumbs']/ul[@class='unstyled']/li",
    'description' : "//div[@class='ionTabs']/div[@class='ionTabs__body']//div[@class='contenttext']",
    'images' : "//div[@class='product-album']/ul[@class='unstyled']/li/a/img/@src",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = 'hanoilab.com.vn'
allowed_domains = ['hanoilab.com.vn']
start_urls = ['http://hanoilab.com.vn/']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = ['']
rules = [
    Rule(LinkExtractor(allow=['/laptop/']), 'parse_item'),
    Rule(LinkExtractor(allow=['/danh-muc/']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
