# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//h2[@id='hTitleDeal']/span/p",
    'price' : "//p[@class='pGiaTienID']/strong",
    'category' : "",
    'description' : "//div[@class='div_LBodyHL']",
    'images' : "//ul/li/img/@src",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = 'hcmdeal.com'
allowed_domains = ['hcmdeal.com']
start_urls = ['http://www.hcmdeal.com/']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow = ['/xem-san-pham/[a-z0-9-]+']), 'parse_item'),
    Rule(LinkExtractor(allow = ['/deal-[a-z0-9-]+']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
