# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//h1[@class='product-name']",
    'price' : "//span[@class='special-price']/span|//div[@class='price-box']/span/span[@class='price']",
    'category' : "//div[@class='col-md-12 breadcrumbs']/ul/li/a",
    'description' : "//div[@id='yt_tab_products']",
    'images' : "//div/a/img/@src",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = 'hcplus.vn'
allowed_domains = ['hcplus.vn']
start_urls = ['http://hcplus.vn/']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow = ['/[a-zA-Z-]+/?[a-zA-Z0-9-]+.html$']), 'parse_item'),
    Rule(LinkExtractor(allow = ['vn/[a-zA-Z-]+.html']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
