# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div/div/h1[@class='thread-details-title']/a",
    'price' : "//div/div[@class='thread-details-mua']/div[@class='thread-details-muapadding']/div[@class='thread-details-giaban']",
    'category' : "//body/div[@class='thread-details-tohome']/div[@class='w90']/a",
    'description' : "//div[@class='lf f75']/div[@class='thread-details']/div/div[@id='thread_content_pack']",
    'images' : "//div[@id='rME']/div[@class='thread-details cf']/div[@class='lf f38']/div//img/@src",
    'canonical' : "",
    'base_url' : "//base/@href",
    'brand' : ""
}
name = 'hkshop.vn'
allowed_domains = ['hkshop.vn']
start_urls = ['http://www.hkshop.vn/?rw=now']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow=['/p+\d+/']), 'parse_item'),
    Rule(LinkExtractor(allow=['/fid+-\d+/','/sid+-\d+/']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
