# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div[@id='product-detail']/h2",
    'price' : "//div[@class='price-block ']/span",
    'category' : "//div[@id='nav-middle-block']/h2/a",
    'description' : "//div[@class='product-content']",
    'images' : "//div[@class='thumbnail-block']/img/@src | //div[@class='product-content']/div/a/img/@src | //div[@id='product-detail']/div[@id='boxProduct']//img/@src",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = 'hnammobile.com'
allowed_domains = ['hnammobile.com']
start_urls = ['http://www.hnammobile.com/']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(), 'parse_item'),
    Rule(LinkExtractor(), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
