# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div[@id='product-top']/h1",
    'price' : "//span[@class='PricesalesPrice']",
    'category' : "//span[@class='breadcrumbs']/a",
    'description' : "//div[@class='jwts_tabbertab ']",
    'images' : "//img[@id='medium-image']/@src",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = 'hoaanhdao.vn'
allowed_domains = ['hoaanhdao.vn']
start_urls = ['http://hoaanhdao.vn']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow = ['.*.html'], deny = ['cart.html', 'create-an-account.html', 'qlbh.html', '/blog', '/tag/', 'gioi-thieu.html', 'my-pham-hoa-anh-dao.html', '[0-9]+/[a-z-]+.html', 'lost-password.html', 'lost-user-name','sitemap']), 'parse_item'),
    Rule(LinkExtractor(allow = ['.*.html'], deny = ['cart.html', 'create-an-account.html', 'qlbh.html', '/blog', '/tag/', 'gioi-thieu.html', 'my-pham-hoa-anh-dao.html', '[0-9]+/[a-z-]+.html', 'lost-password.html', 'lost-user-name','sitemap']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
