# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//title",
    'price' : "//div[@class='product-price']/span/span",
    'category' : "//div[@id='breadcrumb']/ul/li/a",
    'description' : "//div[@class='spec-detail-wrapper properties-product clearfix']",
    'images' : "//div[@id='productgallery']/div[@class='main-gallery']/div/a/@href",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = 'hoanggiamobile.com'
allowed_domains = ['hoanggiamobile.com']
start_urls = ['http://hoanggiamobile.com/']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow=['/[a-zA-Z0-9-]+\.html']), 'parse_item'),
    Rule(LinkExtractor(allow=['/\.*']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
