# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//h1[@class='product_title entry-title']",
    'price' : "//header/span[@class='price wpc_sale_price']/span[@class='amount']",
    'category' : "",
    'description' : "//div[@id='tab-description']",
    'images' : "//ul[@class='slides']/li/a/img/@src",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = 'hotmua.vn'
allowed_domains = ['hotmua.vn']
start_urls = ['http://hotmua.vn/']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow = ['/product/']), 'parse_item'),
    Rule(LinkExtractor(allow = ['/danhmuc/']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
