# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div[@class='pro-detail']/h1",
    'price' : "//div[@class='p-price-mediamart img_full_price']",
    'category' : "//div[@class='location']/a",
    'description' : "//div[@class='pro-detail']/div[@class='p-spec']/p",
    'images' : "//div[@class='pro-image']//img/@src",
    'canonical' : "//link[@rel='canonical']/@href",
    'base_url' : "",
    'brand' : ""
}
name = 'hthagiang.vn'
allowed_domains = ['hthagiang.vn']
start_urls = ['http://hthagiang.vn/']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    #Rule(LinkExtractor(), 'parse_item'),
    #Rule(LinkExtractor(), 'parse'),
    Rule(LinkExtractor(allow=['/[a-zA-Z0-9-]+\.html']), 'parse_item_and_links'),
]
