# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//h4",
    'price' : "//span[@id='our_price_display']",
    'category' : "//div[@class='breadcrumb']/div[@class='container']/ul/li/a",
    'description' : "//div[@class='tab-content']",
    'images' : "//div[@id='galleria']/img/@data-image",
    'canonical' : "//link[@rel='canonical']/@href",
    'base_url' : "",
    'brand' : ""
}
name = 'hugoshop.vn'
allowed_domains = ['hugoshop.vn']
start_urls = ['http://hugoshop.vn/']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow=['/products/[a-zA-Z0-9-]+$']), 'parse_item'),
    Rule(LinkExtractor(allow=['/collections/[a-zA-Z0-9-]+($|\?page=\d+)']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
