# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//td/a[@id='ContentPlaceHolder1_ChiTietSanPham1_Grid_ChiTietHangHoa_hplTenHH_0']",
    'price' : "//td/span[@id='ContentPlaceHolder1_ChiTietSanPham1_Grid_ChiTietHangHoa_lblGiaBan_0']",
    'category' : "",
    'description' : "//td/span[@id='ContentPlaceHolder1_ChiTietSanPham1_Grid_ChiTietHangHoa_Label1_0']/p",
    'images' : "//td/img[@id='ContentPlaceHolder1_ChiTietSanPham1_Grid_ChiTietHangHoa_Image1_0']/@src",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = 'intimexplaza.com.vn'
allowed_domains = ['intimexplaza.com.vn']
start_urls = ['http://intimexplaza.com.vn/']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow=['/ChiTietSanPham.aspx']), 'parse_item'),
    Rule(LinkExtractor(allow=['/[a-zA-Z0-9-]+\.aspx']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
