# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div[@id='intro']/h1",
    'price' : "//div[@id='intro']/p[3]/strong",
    'category' : "//div[@class='breadcrumb']/span",
    'description' : "//div[@id='tab-1']/div/p",
    'images' : "//img[@class='top-img']/@src",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = 'intour.com.vn'
allowed_domains = ['intour.com.vn']
start_urls = ['http://www.intour.com.vn/']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow = ['.html'], deny = ['gioi-thieu.html', 'lien-he.html', 'khach-hang.html']), 'parse_item'),
    Rule(LinkExtractor(allow = ['.vn/[a-z-]+/$'], deny = ['dich-vu', 'tin-tuc']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
