# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//h1[@class='title']",
    'price' : "//p[@class='price']/span[@class='price-new']",
    'category' : "//div[@class='row']/ol/li/a",
    'description' : "//div[@class='product-description']/div[@id='home']/div[@class='tab-content']",
    'images' : "//div[@class='img-product']/a/@href",
    'canonical' : "//link[@rel='canonical']/@href",
    'base_url' : "",
    'brand' : ""
}
name = 'iskin.com.vn'
allowed_domains = ['iskin.com.vn']
start_urls = ['http://iskin.com.vn/']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow=['/products/[\w\d-]+$']), 'parse_item'),
    Rule(LinkExtractor(allow=['/collections/[\w\d-]+($|\?page=\d+)']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
