# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div[@class='details']/h3[@class='tieude']",
    'price' : "//div[@class='info_detail']/p[@class='price']",
    'category' : "//ul[@class='breacrum']/li/a",
    'description' : "//div[@class='tech']/div[@class='technology']",
    'images' : "//div[@class='details']/div[@class='images']/a/@href",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = 'khabinh.vn'
allowed_domains = ['khabinh.vn']
start_urls = ['http://khabinh.vn']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow=['/[a-zA-Z0-9-_]+_pro+\d+\.html']), 'parse_item'),
    Rule(LinkExtractor(allow=['/[a-zA-Z0-9-]+-c+\d+\.html', 'page='], deny=['attr=','letter=','/phim/','\?']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
