# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//h1[@class='entry-title']",
    'price' : "//p[@class='price large']/span[@class='amount']",
    'category' : "//h4[@class='breadcrumb']/a",
    'description' : "//div[@class='short-description']/p",
    'images' : "//a[@itemprop='image']/@href",
    'canonical' : "//link[@rel='canonical']/@href",
    'base_url' : "",
    'brand' : ""
}
name = 'khacten.net'
allowed_domains = ['khacten.net']
start_urls = ['https://khacten.net/']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow=['/san-pham/']), 'parse_item'),
    Rule(LinkExtractor(allow=['/danh-muc/[a-zA-Z0-9-/]+/$']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
