# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//tbody/tr/td/span[@class='title_detail']",
    'price' : "//tr/td/div/span[@class='price']",
    'category' : "",
    'description' : "",
    'images' : "//div/a[@id='view_product_main_image']/img/@src",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = 'khanhlong.com'
allowed_domains = ['khanhlong.com']
start_urls = ['http://www.khanhlong.com']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow=['/detail.php']), 'parse_item'),
    Rule(LinkExtractor(allow=['/category.php']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
