# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//h1/span[@id='ctl00_ContentPlaceHolder1_FormView2_lblProductName']",
    'price' : "//div[@class='price-info']/div[@class='inner-price']/ins[@class='pricesell']",
    'category' : "//div[@class='rst_breadcrumb']/ul/li/a",
    'description' : "//div[@class='detail-specifications']/ul/table[@id='ctl00_ContentPlaceHolder1_FormView1']",
    'images' : "//a[@class='pro-image-large']/img[@itemprop='photo']/@src",
    'canonical' : "",
    'base_url' : "",
    'brand' : "",
    'in_stock' : "",
    'guarantee' : "",
    'promotion' : ""
}
name = 'khodogiadung.vn'
allowed_domains = ['khodogiadung.vn']
start_urls = ['http://www.khodogiadung.vn/']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = ['']
rules = [
    Rule(LinkExtractor(allow=['/[a-zA-Z0-9-]+-pr-\d+\.aspx$']), 'parse_item'),
    Rule(LinkExtractor(allow=['/danh-muc-san-pham.aspx\?cid=\d+']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
