# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div[@class='product-title defaultTitle']/h1",
    'price' : "//div[@class='Value']/em[@class='ProductPrice VariationProductPrice']",
    'category' : "//div[@id='Breadcrumb']/ul/li/a",
    'description' : "//div[@id='ProductDescription']/div[@class='ProductDescriptionContainer']/div|//div[@id='ProductDescription']/div[@class='ProductDescriptionContainer']/table[@class='attribute']//td",
    'images' : "//div[@class='ProductThumb']/div[@class='ProductThumbImage']/a/@href",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = 'khomaytinhbang.com'
allowed_domains = ['khomaytinhbang.com']
start_urls = ['http://www.khomaytinhbang.com/san-pham-p7.html']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow=['/[a-z0-9-_]+\d+.html']), 'parse_item'),
    Rule(LinkExtractor(allow=['/\d+.html']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
