# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//section[@class='right_thumb']/h1",
    'price' : "//span[@class='normal_text']",
    'category' : "//div[@class='breadcrumb clearfix']/h2/a",
    'description' : "//div[@class='comment more']",
    'images' : "//ul[@class='slides carousel']/li/img/@src",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = 'kosshop.vn'
allowed_domains = ['kosshop.vn']
start_urls = ['http://www.kosshop.vn/']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow=['/[a-zA-Z-]+\d+.html$']), 'parse_item'),
    Rule(LinkExtractor(allow=['/[a-zA-Z-]+/$'], deny=['/t/']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
