# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div[@class='product-col-desc']/h1[@class='title']",
    'price' : "//div[@class='product-price']/strong[@class='colorh']",
    'category' : "//div[@class='BreadcrumbText']/a",
    'description' : "//div[@class='content-responsive']/div[@class='content news']",
    'images' : "//div[@class='clearfix']/a/@href",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = 'lanopearl.com.vn'
allowed_domains = ['lanopearl.com.vn']
start_urls = ['http://lanopearl.com.vn/']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow=['/san-pham/[a-zA-Z0-9-/]+\.html$']), 'parse_item'),
    Rule(LinkExtractor(allow=['/[a-zA-Z0-9-]+/$']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
