# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//h1[@itemprop='name']",
    'price' : "//div[@class='ctn_format']/p",
    'category' : "//ul[@class='ctn_breadcrumb']/li/a",
    'description' : "//div[@class='ctn_product-detail']/div[@class='str_tab-content']",
    'images' : "//figure[@class='item']/img[@itemprop='image']/@src",
    'canonical' : "//link[@rel='canonical']/@href",
    'base_url' : "",
    'brand' : "",
    'in_stock' : "",
    'guarantee' : ""
}
name = 'larocheposay.vn'
allowed_domains = ['larocheposay.vn']
start_urls = ['http://www.larocheposay.vn/']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = ['']
rules = [
    Rule(LinkExtractor(allow=['-p\d+.aspx$']), 'parse_item'),
    Rule(LinkExtractor(allow=['-[^p]+3440.aspx$']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
