# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//h1[@class='col-md-6 col-sm-6']",
    'price' : "//div[@class='product']/div[@class='col_half col_last product-desc']/div[@class='product-price']/ins",
    'category' : "//ol[@class='breadcrumb col-md-6 col-sm-6 hidden-xs']/li/a",
    'description' : "//table[@class='mce-item-table']//tr",
    'images' : "//div[@class='slider-wrap']/div/a/@href",
    'canonical' : "//link[@rel='canonical']/@href",
    'base_url' : "",
    'brand' : "",
    'in_stock' : "",
    'guarantee' : "",
    'promotion' : ""
}
name = 'latashop.com'
allowed_domains = ['latashop.com']
start_urls = ['http://www.latashop.com/']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = ['']
rules = [
    Rule(LinkExtractor(allow=['/products/']), 'parse_item'),
    Rule(LinkExtractor(allow=['/collections/'], deny=['/products/']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
