# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//h5[@class='name-product-detail']",
    'price' : "//div[@class='div-detail-product-text']/h6[5]/span",
    'category' : "//h2[@id='title-mobile-detail-h2']",
    'description' : "",
    'images' : "//ul/li/a/img/@data-large",
    'canonical' : "",
    'base_url' : "http://www.lazalo.vn/",
    'brand' : ""
}
name = 'lazalo.vn'
allowed_domains = ['lazalo.vn']
start_urls = ['http://www.lazalo.vn/']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow=['/san-pham/[a-zA-Z0-9-]+-\d+\.html$']), 'parse_item'),
    Rule(LinkExtractor(allow=['[/san-pham/[a-zA-Z-]+[/|\.htm$]']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
