# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div/div[@class='sanpham']/div[@class='pro_detail']/h2",
    'price' : "//form/div/div[@class='sanpham']/div[@class='pro_detail']/div[@class='cat'][2]/font",
    'category' : "//div[@class='Content_Center']/div[@class='Left_Center']/div[@class='link_menu']/a",
    'description' : "//div/div[@class='sanpham']/div/p",
    'images' : "//div[@class='img_detail']/a/img/@src",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = 'lehoangjsc.vn'
allowed_domains = ['lehoangjsc.vn']
start_urls = ['http://lehoangjsc.vn']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow=['/detail-product-']), 'parse_item'),
    Rule(LinkExtractor(allow=['/menu-product-']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
