# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div[@class='tovar_view_description']/div[@class='tovar_view_title']",
    'price' : "//div[@class='pull-right']/div[@class='tovar_view_price']",
    'category' : "//div[@class='breadcrumb text_left']/h2/a",
    'description' : "//div[@id='pro_description_']",
    'images' : "//meta[@property='og:image']/@content",
    'canonical' : "//link[@rel='canonical']/@href",
    'base_url' : "",
    'brand' : ""
}
name = 'limeorange.vn'
allowed_domains = ['limeorange.vn']
start_urls = ['http://limeorange.vn/']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow=['/[a-zA-Z0-9-]+-\d+\.html$']), 'parse_item'),
    Rule(LinkExtractor(allow=['/[a-zA-Z0-9-]+-\d+/($|p\d+$)']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
