# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div[@class='detail_product']/h1",
    'price' : "//div[@class='detail_product']/div/p[3]/span",
    'category' : "//div[@class='header']/div[@class='b_h']//a",
    'description' : "//div[@class='product']/div[@class='content_pro']/div[@class='dr']",
    'images' : "//ul[@class='pagination']/li/a/img/@src",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = 'linhkienhtc.net'
allowed_domains = ['linhkienhtc.net']
start_urls = ['http://www.linhkienhtc.net/']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow=['/san-pham/[/a-zA-Z0-9-]+\.html$']), 'parse_item'),
    Rule(LinkExtractor(allow=['[/a-zA-Z0-9-]+$']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
