# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//tr/td/span/h1",
    'price' : "//span[@itemprop='price'] | //table[3]/tbody/tr/td/font/b | //tr[2]/td[3]/font/b/span[1] | //tr[2]/td//span[@itemprop='price']",
    'category' : "//div[@id='breadcrumb']/span/a",
    'description' : "//td[2]/span/div/p | //span/div/p[@class='MsoNormal']",
    'images' : "//tr/td/a[@rel='enlargeimage::mouseover']/@href | //div[@id='loadarea']/img/@src",
    'canonical' : "",
    'base_url' : "",
    'brand' : "",
    'in_stock' : "",
    'guarantee' : "",
    'promotion' : ""
}
name = 'linhperfume.com'
allowed_domains = ['linhperfume.com']
start_urls = ['http://www.linhperfume.com/']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = ['']
rules = [
    Rule(LinkExtractor(allow =['/p\d+-[\w-]+\.html$']), 'parse_item'),
    Rule(LinkExtractor(allow = ['/[a-zA-Z0-9-]+\.html'], deny=['/p\d+-[\w-]+\.html$']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
