# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div[@class='product-information']/h2",
    'price' : "//p[@class='special-price']/span[@class='price']",
    'category' : "",
    'description' : "//div[@class='product-desc rte']/p",
    'images' : "//div[@class='large-image view-product']/a/@href",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = 'linhkienit.net'
allowed_domains = ['linhkienit.net']
start_urls = ['http://linhkienit.net/']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    #Rule(LinkExtractor(), 'parse_item'),
    #Rule(LinkExtractor(), 'parse'),
    Rule(LinkExtractor(allow=['/[a-zA-Z0-9-]+$']), 'parse_item_and_links'),
]
