# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div[@id='contentDetailProduct']/div[@class='contentProduct']/div[@class='titleNews1']/h1[@id='nameProduct']",
    'price' : "//div[@class='contentProduct']/div[@class='content']/p[@id='kichco']/font",
    'category' : "",
    'description' : "//div[@class='clear']/div[@id='contentInfo']/div[@id='pvt_divClick']/div[@class='pvt_content activeDiv']",
    'images' : "//div[@id='content']/div[@class='clearfix']//img/@src",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = 'linhkienlaptopld.com'
allowed_domains = ['linhkienlaptopld.com']
start_urls = ['http://linhkienlaptopld.com']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow=['']), 'parse_item'),
    Rule(LinkExtractor(allow=['']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
