# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div[@class='detail-product']/p[@class='title-product']",
    'price' : "//div[@class='price-picker']/ul[@class='prices']/li[1]",
    'category' : "//div[@id='content']/div[@class='breadcrumb']",
    'description' : "//div[@class='entry-content']/div[@id='product-detail'] | //div[@class='entry-content']/p",
    'images' : "//div[@id='product-mobile-sidebar']/img/@src | //div[@id='product-mobile-sidebar']/a/img/@src",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = 'lohha.com.vn'
allowed_domains = ['lohha.com.vn']
start_urls = ['http://lohha.com.vn/']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow=['/san-pham/']), 'parse_item'),
    Rule(LinkExtractor(allow=['/tpcn/']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
