# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div[@class='titlezone']/h6",
    'price' : "//dd[@class='infopri']",
    'category' : "//div[@class='depth']/span",
    'description' : "//div[@class='infomation']/div",
    'images' : "//div[@class='zoom']/a/@href",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = 'lottedatviet.vn'
allowed_domains = ['lottedatviet.vn']
start_urls = ['http://www.lottedatviet.vn/index.do']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow=['/display/']), 'parse_item'),
    Rule(LinkExtractor(allow=['/category/']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
