# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//h1[@class='pr_name']",
    'price' : "//div[@class='price']/span[@class='alt_font']/span/span",
    'category' : "//div[@class='breadcrumb']/a",
    'description' : "//div[@id='tab-description']",
    'images' : "//a[@id='zoom1']/@href",
    'canonical' : "//link[@rel='canonical']/@href",
    'base_url' : "//base/@href",
    'brand' : ""
}
name = 'luugia.vn'
allowed_domains = ['luugia.vn']
start_urls = ['http://luugia.vn/']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow=['\.html$']), 'parse_item'),
    Rule(LinkExtractor(allow=['/[^\.]+$']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
