# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div[@class='content_data']/div[@class='content_trangcon']/h1",
    'price' : "//div[@class='noidung_sanpham']/div[@id='sanpham']/div[@class='sanpham_mota']/div[@class='giaban_ct']",
    'category' : "",
    'description' : "//div[@class='content_data']/div[@class='content_trangcon']/div[@class='noidung_sanpham']/div",
    'images' : "//div[@class='img_noidung']/div[@id='load_IMG']/img/@src",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = 'luxy.vn'
allowed_domains = ['luxy.vn']
start_urls = ['http://luxy.vn']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow=['/[a-zA-Z0-9-]+\.html']), 'parse_item'),
    Rule(LinkExtractor(allow=['/[a-zA-Z0-9-]+/+$']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
