# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div[@id='ctl00_ctl05_Body']/span/table//tr/td/table//tr/td/h3",
    'price' : "//div[@id='ctl00_SanPhamPanel']/div/div/span/table//tr[1]/td[2]/table//tr[2]/td[@class='price']",
    'category' : "",
    'description' : "//div[@class='bg_guide_content']/div[@class='note']",
    'images' : "//a[@class='MagicZoomPlus']/@href | //div[@id='divContainer']//img/@src",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = 'maiam.vn'
allowed_domains = ['maiam.vn']
start_urls = ['http://maiam.vn']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow=['/View/']), 'parse_item'),
    Rule(LinkExtractor(allow=['/List/']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
