# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//header[@class='prod-detail-title']/h1",
    'price' : "//section[@class='prod-price prod-bt']/p[@class='price']",
    'category' : "//a[@itemprop='url']/span[@itemprop='title']",
    'description' : "",
    'images' : "//div[@class='tab_img_list']/p/a/@href | //ul[@class='slides']/li/img/@src",
    'canonical' : "",
    'base_url' : "",
    'brand' : "",
    'in_stock' : "",
    'guarantee' : "",
    'promotion' : ""
}
name = 'mainguyen.vn'
allowed_domains = ['mainguyen.vn']
start_urls = ['http://www.mainguyen.vn/']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = ['']
rules = [
    Rule(LinkExtractor(allow=['/[a-zA-Z0-9-]+\.html']), 'parse_item'),
    Rule(LinkExtractor(allow=['/[a-zA-Z0-9-,]+$'], deny=['/tin-tuc/','\.html','/\.\./']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
