# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div[@class='product_detail_info right']/h1[@id='config_name']",
    'price' : "//div[@class='price_list_detail']/span[@id='config_price']",
    'category' : "//div[@class='breadcrumb']/a",
    'description' : "//div[@class='boxDetailBorder']/div[@class='paddings']",
    'images' : "//div[@class='product-img-box']/p/div/a/@href | //div[@class='more-views mor-image-control']/ul/li/a/@href",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = 'matic.com.vn'
allowed_domains = ['matic.com.vn']
start_urls = ['http://matic.com.vn']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow=['/\d+-[a-zA-Z0-9-]+\.html']), 'parse_item'),
    Rule(LinkExtractor(allow=['/c+\d+/'], deny=['\?']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
