# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div[@class='info-content']/div[@class='product-description']/div[@class='product-description-content']/h1",
    'price' : "//div[@class='product-description']/div[@class='product-description-content']/div/p[@class='special-price']",
    'category' : "",
    'description' : "//div/div[@class='chitiet']/ul/li",
    'images' : "//div[@class='jszoom-product']/div[@class='zoom-section']/div[@class='zoom-desc']/div[@class='zoom-small-image']//a/@href",
    'canonical' : "",
    'base_url' : "//base/@href",
    'brand' : ""
}
name = 'matkinh.com.vn'
allowed_domains = ['matkinh.com.vn']
start_urls = ['http://matkinh.com.vn']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow=['/[a-zA-Z0-9-]+-\d+\.html']), 'parse_item'),
    Rule(LinkExtractor(allow=['/san-pham/']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
