# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div[@class='wrap_content content']/div[@id='detail_product']/div/h1",
    'price' : "//div/p[@class='font18']/strong/span[@class='red']",
    'category' : "//div[@id='wrap']/div[@class='wrap_content content']/div[@id='location']/a",
    'description' : "//div[@class='wrap_content content']/div[@id='tab_info_detail']/div[@class='content_tab']/div[@id='baivietsanpham']",
    'images' : "//li/a[@class='img_thumb']/@href",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = 'mayanhvn.com'
allowed_domains = ['mayanhvn.com']
start_urls = ['http://mayanhvn.com']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow=['\.html']), 'parse_item'),
    Rule(LinkExtractor(allow=['/c+\d+\.html']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
