# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div[@class='title_code_pro']/font/h1",
    'price' : "//p[@class='price_km']",
    'category' : "//div[@class='navigater_pro']/div/a/span",
    'description' : "//div[@class='chi_tiet_san_pham']/div[@class='thong_tin']",
    'images' : "//div[@class='slide_product']/a/@href",
    'canonical' : "//link[@rel='canonical']/@href",
    'base_url' : "",
    'brand' : ""
}
name = 'maybomchinhhang.vn'
allowed_domains = ['maybomchinhhang.vn']
start_urls = ['http://maybomchinhhang.vn/']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow=['/chi-tiet-san-pham/']), 'parse_item'),
    Rule(LinkExtractor(allow=['/danh-muc-san-pham/']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
