# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//h1[@class='nameproduct text-uppercase']",
    'price' : "//div[@class='price']/span[@class='pricestyle1']",
    'category' : "//ol[@class='breadcrumb']/li/a",
    'description' : "//div[@class='col-md-9 col-sm-9 col-lg-9']/div[@class='detailproduct']",
    'images' : "//div[@class='simpleLens-gallery-container']/div[@class='simpleLens-thumbnails-container']/a/@data-big-image",
    'canonical' : "//link[@rel='canonical']/@href",
    'base_url' : "//base/@href",
    'brand' : "",
    'in_stock' : "",
    'guarantee' : "",
    'promotion' : ""
}
name = 'maylocnuocsmartviet.com'
allowed_domains = ['maylocnuocsmartviet.com']
start_urls = ['https://maylocnuocsmartviet.com/']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = ['']
rules = [
    Rule(LinkExtractor(allow=['/[a-zA-Z0-9-]+\.html$']), 'parse_item'),
    Rule(LinkExtractor(allow=['/[a-zA-Z0-9-]+-c-\d+$']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
