# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div[@class='center-wrap-content02']/table//tr/td/h2",
    'price' : "//div[@class='center-wrap-content02']/table//tr/td/p/strong[@class='pro-price']",
    'category' : "",
    'description' : "//div[@class='thongso-sp-conten']",
    'images' : "//div[@class='center-wrap-content02']/table//tr/td[@class='big-pro-pics']/img/@src",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = 'maytinhgiare.net.vn'
allowed_domains = ['maytinhgiare.net.vn']
start_urls = ['http://maytinhgiare.net.vn/']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow=['/product+_detail+\.php']), 'parse_item'),
    Rule(LinkExtractor(allow=['/products+\.php']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
