# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div[@class='product_detail vnz']/h1",
    'price' : "//span[@class='productPrice adv']",
    'category' : "//ol[@class='breadcrumb left']/li/a[@itemprop='url']/span[@itemprop='title']",
    'description' : "//div[@class='box-middle'][1]",
    'images' : "//div[@id='prod_medium']/img/@src",
    'canonical' : "",
    'base_url' : "",
    'brand' : "",
    'in_stock' : "",
    'guarantee' : ""
}
name = 'mayvanphongphuthinh.com'
allowed_domains = ['mayvanphongphuthinh.com']
start_urls = ['http://mayvanphongphuthinh.com/']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = ['']
rules = [
    Rule(LinkExtractor(allow=['_pid+\d+\.html'], deny=['( )']), 'parse_item'),
    Rule(LinkExtractor(allow=['_pcid+\d+\.html'], deny=['filter=']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
