# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div[@class='rdetail']/table//tr/td[@class='right']/div[@id='info-main']/h3",
    'price' : "//div[@id='info-main']/div[@class='info-list even  view-visit']",
    'category' : "//div[@class='breadcrum']/span/a",
    'description' : "//div[@id='description']/div[@class='box-header']",
    'images' : "//div[@class='rdetail']/table//tr/td[@class='left']/img[@class='thumbnail']/@src",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = 'mbook.com.vn'
allowed_domains = ['mbook.com.vn']
start_urls = ['http://mbook.com.vn']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow=['/chi-tiet/']), 'parse_item'),
    Rule(LinkExtractor(allow=['/chuyen-muc/']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
