# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div[@class='col-md-12'][1]/h5[@class=' nomargin']/a",
    'price' : "//div[@class='col-xs-12 col-md-5']/p/span[1]",
    'category' : "",
    'description' : "//div[@class='row']/div[@class='col-md-9']/div[@class='row']/div[@class='col-md-12'][1]",
    'images' : "//div[@class='carousel-inner']/div[@class='active item']/img/@src",
    'canonical' : "",
    'base_url' : "",
    'brand' : "//div[@class='col-md-12'][3]/div[@class='leftf'][1]/a",
    'in_stock' : "",
    'guarantee' : "//div[@class='col-md-12'][3]/div[@class='leftf'][3]/a",
    'promotion' : ""
}
name = 'melicare.com'
allowed_domains = ['melicare.com']
start_urls = ['http://melicare.com/']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = ['']
rules = [
    Rule(LinkExtractor(allow=['/[a-zA-Z0-9-]+-\d+-vpd\.html$']), 'parse_item'),
    Rule(LinkExtractor(allow=['/[a-zA-Z0-9-]+-\d+-lcat\.html($|\?p=\d+$)']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
