# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "/html/body/div[@id='main']/div[@class='main_space']/div[@class='column_center right']/div[@class='box_detail shadow cor']/div[@class='info_detail right']/div[@class='name_left left']/h1[@class='name']",
    'price' : "/html/body/div[@id='main']/div[@class='main_space']/div[@class='column_center right']/div[@class='box_detail shadow cor']/div[@class='info_detail right']/div[@class='price']/span",
    'category' : "/html/body/div[@id='main']/div[@class='main_space']/div[@class='column_center right']/div[@class='lead_sub']/div/a",
    'description' : "/html/body/div[@id='main']/div[@class='main_space']/div[@class='column_center right']/div[@class='box_detail shadow cor']/div[@class='info_detail right']/div[@class='summary']",
    'images' : "/html/body/div[@id='main']/div[@class='main_space']/div[@class='column_center right']/div[@class='box_detail shadow cor']/div[@class='image_detail cor left']/div[@class='zoomp']/a/@href",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = 'melopshop.com'
allowed_domains = ['melopshop.com']
start_urls = ['http://www.melopshop.com']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow=['/\d+-[a-zA-Z0-9-]+\.html']), 'parse_item'),
    Rule(LinkExtractor(allow=['/c+\d+/']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
