# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div[@class='prod-title']/h1",
    'price' : "//div[@class='info-prod info-price prod-price']/span[@class='info']",
    'category' : "//li[@class='breadcrum-item']/a",
    'description' : "//div[@class='prod-descp']/div[@class='col prod-descp-detail']",
    'images' : "//img[@class='prod-img']/@data-src",
    'canonical' : "",
    'base_url' : "",
    'brand' : "",
    'in_stock' : "",
    'guarantee' : ""
}
name = 'meta.vn'
allowed_domains = ['meta.vn']
start_urls = ['http://meta.vn/']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = ['']
rules = [
    Rule(LinkExtractor(allow=['/[a-zA-Z0-9-]+-p\d+$']), 'parse_item'),
    Rule(LinkExtractor(allow=['/[a-zA-Z0-9-]+-c\d+($|\?p=\d+)']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
