# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//h1[@class='name-pro-detail']",
    'price' : "//p[@class='price_block']/span[@class='pricePro specialPrice']",
    'category' : "//ul[@class='breadcrumb']/li/a[@itemprop='url']/span[@itemprop='title']",
    'description' : "//div[@id='view1']/div[@class='desPro']",
    'images' : "//div[@class='item']/img/@src",
    'canonical' : "//link[@rel='canonical']/@href",
    'base_url' : "",
    'brand' : "",
    'in_stock' : "",
    'guarantee' : "",
    'promotion' : ""
}
name = 'mia.vn'
allowed_domains = ['mia.vn']
start_urls = ['http://mia.vn/']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = ['']
rules = [
    Rule(LinkExtractor(allow=['/products/']), 'parse_item'),
    Rule(LinkExtractor(allow=['/[\w-]+($|\?page=\d+$)'], deny=['/products/']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
