# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//h1[@itemprop='name']",
    'price' : "//span[@class='sale_price']/span[@class='main_price']/span[@class='woocommerce-Price-amount amount']",
    'category' : "//div[@class='container']/nav[@itemprop='breadcrumb']/a",
    'description' : "//div[@class='col-md-9']/div[@class='woocommerce-tabs wc-tabs-wrapper']/div[@class='woocommerce-Tabs-panel woocommerce-Tabs-panel--description panel entry-content wc-tab']",
    'images' : "//meta[@property='og:image']/@content",
    'canonical' : "//link[@rel='canonical']/@href",
    'base_url' : "",
    'brand' : "",
    'in_stock' : "",
    'guarantee' : "",
    'promotion' : ""
}
name = 'mihaza.com'
allowed_domains = ['mihaza.com']
start_urls = ['http://mihaza.com/']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = ['']
rules = [
    Rule(LinkExtractor(allow=['/san-pham/[a-zA-Z0-9-/]+/$']), 'parse_item'),
    Rule(LinkExtractor(allow=['/danh-muc/[a-zA-Z0-9-/]+/$']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
