# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div[@class='product-name']/h1",
    'price' : "//div[@class='prices']/div[@class='product-price']/span",
    'category' : "//div[@class='breadcrumb']/a[@class='item']",
    'description' : "//div[@class='box-content']/div[@class='spec-content']",
    'images' : "//div[@class='product-picture']/div[@class='picture']/a/@href | //ul[@id='mycarousel']/li/a/@href",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = 'mobimart.com.vn'
allowed_domains = ['mobimart.com.vn']
start_urls = ['http://mobimart.com.vn/']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow=['/[a-zA-Z0-9-]+$']), 'parse_item'),
    Rule(LinkExtractor(allow=['\?specs=+\d+$']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
