# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div[@id='content']/div[@id='_productWrap']/div[@id='_exclusiveText']/span[@class='bold']",
    'price' : "//div[@class='jsFormContent']/div[@class='productPriceContainer']/div/span[@class='price3']",
    'category' : "//div[@id='ja-pathway']/ul[@class='breadcrumbs']/li/a",
    'description' : "//div[@class='drawerBox overviewPrint']/div[@class='drawerBoxBorder jsDrawer']/div[@id='collapseOne']/div[@class='panel-body']",
    'images' : "//div[@class='row']/div[@class='image col-lg-5 col-md-5 col-sm-5 col-xs-12']/div[@class='show-img']/img/@src",
    'canonical' : "//link[@rel='canonical']/@href",
    'base_url' : "",
    'brand' : ""
}
name = 'modernlife.vn'
allowed_domains = ['modernlife.vn']
start_urls = ['http://www.modernlife.vn']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow=['/[a-zA-Z0-9-]+-\d+\.html']), 'parse_item'),
    Rule(LinkExtractor(allow=['/[a-zA-Z0-9-]+\.html']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
