# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div[@class='ten_detail']/h1",
    'price' : "//div[@class='value box-price']/span[@class='price']",
    'category' : "//ul[@class='nav-path-page']/li/a",
    'description' : "//div[@class='mid_mota']/div[@class='sum-detail']",
    'images' : "//div[@class='img-product-thumb_list']/ul[@id='img_thumb']/li/a/@href | //div[@class='img-product-detail']/div[@id='img_large']//a/@href | //div[@class='img-product-detail']/div[@id='img_large']//img/@src",
    'canonical' : "//link[@rel='canonical']/@href",
    'base_url' : "",
    'brand' : ""
}
name = 'mrbaby.com.vn'
allowed_domains = ['mrbaby.com.vn']
start_urls = ['http://mrbaby.com.vn']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow = ['/p+\d+\.html']), 'parse_item'),
    Rule(LinkExtractor(allow = ['/c+\d+\.html']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
