# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//h1[@id='page-title']/text()[2]",
    'price' : "//div[@id='deal_info']/div[@class='ribbon']/div[@class='buyit']/strong/em",
    'category' : "//h1[@id='page-title']/a",
    'description' : "//div[@class='field-item even']/div",
    'images' : "//div[@id='deal_title_pic']/div[@class='highslide-gallery']/a/@href",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = 'muaban.bluestar-vn.com'
allowed_domains = ['muaban.bluestar-vn.com']
start_urls = ['http://muaban.bluestar-vn.com/']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    #Rule(LinkExtractor(), 'parse_item'),
    #Rule(LinkExtractor(), 'parse'),
    Rule(LinkExtractor(allow=['/[a-zA-Z0-9-]+\.html']), 'parse_item_and_links'),
]
