# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div[@id='content']/div[@id='content_top']/div[@class='overview']/h1[@class='name']",
    'price' : "//div[@id='content_top']/div[@class='overview']/p/b[@class='red price']",
    'category' : "//div[@class='wrap_content']/div[@id='content']/div[@class='location']/a",
    'description' : "//div[@class='tabs']/div[@class='content_tab']/div[@id='ThongSoKyThuat']",
    'images' : "//div[@id='content']/div[@id='content_top']/div[@class='img_product_detail']/ul/li/a/@href | //div[@class='img_product_detail']/div[@class='img_large']/a/@href",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = 'muagiagoc.vn'
allowed_domains = ['muagiagoc.vn']
start_urls = ['http://muagiagoc.vn']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow=['/\d+-[a-zA-Z0-9-]+\.html']), 'parse_item'),
    Rule(LinkExtractor(allow=['/c+\d+/'], deny=['filter=','min=','max=']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
