# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div[@class='tt_product_detail']/h1/a",
    'price' : "//div[@class='bt_price_detail']",
    'category' : "",
    'description' : "//div[@class='box_product_detail box_product_description'][2]/div[@class='text_info_detail']",
    'images' : "//div[@class='show_image']/a/@href",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = 'muahangvip.vn'
allowed_domains = ['muahangvip.vn']
start_urls = ['http://muahangvip.vn/']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow = ['/[a-z0-9-]+.[A-Z0-9]+.html']), 'parse_item'),
    Rule(LinkExtractor(allow = ['/[a-z0-9-]+.html'], deny = ['thong-tin', 'gio-hang', 'dang-ky', 'dang-nhap', 'san-pham-ghi-nho']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
