# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div[@class='rc_title']",
    'price' : "//div[@class='price_goc']",
    'category' : "",
    'description' : "//div[@class='gtc_diemnoibat']/ul",
    'images' : "//div[@id='slider']/img/@src",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = 'muarieng.vn'
allowed_domains = ['muarieng.vn']
start_urls = ['http://muarieng.vn/']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow = ['/chi-tiet-san-pham/']), 'parse_item'),
    Rule(LinkExtractor(allow = ['/danh-muc/']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
