# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//title",
    'price' : "//div[@id='price-info-down']/span[@class='damua']",
    'category' : "",
    'description' : "//div[@id='cleft-2']/div[@id='cinfo']/ul/li",
    'images' : "//div[@id='img-inc']/div[@id='featured']/img/@src",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = 'muatichluy.com'
allowed_domains = ['muatichluy.com']
start_urls = ['http://www.muatichluy.com/']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow=['/deal/']), 'parse_item'),
    Rule(LinkExtractor(allow=['/homnay/']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
