# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div[@id='myTitle']",
    'price' : "//td/p[@class='price']",
    'category' : "//div[@id='headerNav']/a[2]",
    'description' : "//div[@class='infoTabDetail']",
    'images' : "//div[@id='preview']/p/a/@href",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = 'mykingdom.com.vn'
allowed_domains = ['mykingdom.com.vn']
start_urls = ['http://www.mykingdom.com.vn/']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow = ['/[0-9/]+/[a-z0-9-]+.html']), 'parse_item'),
    Rule(LinkExtractor(allow = ['/[a-z-]+.[0-9-.]+.html'], deny= ['thong-tin']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
