# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div[@class='product-option']/h1",
    'price' : "//li[@class='price-sale']//span[@id='Price-mymall']",
    'category' : "//ol[@class='breadcrumb']/li/a",
    'description' : "//div[@class='description']/span[@id='mo-ta-san-pham']|//div[@class='col-md-12']/div[@class='tab-content']",
    'images' : "//div[@class='thumbs']//a/@data-image|//div[@class='slider-control']/ul/li/a/@data-image",
    'canonical' : "//link[@rel='canonical']/@href",
    'base_url' : "//base/@href",
    'brand' : "",
    'in_stock' : "",
    'guarantee' : "",
    'promotion' : ""
}
name = 'mymall.vn'
allowed_domains = ['mymall.vn']
start_urls = ['https://mymall.vn']
tracking_url = 'http://click.accesstrade.vn/adv.php?rk=0001240000uw&url='
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = ['']
rules = [
    Rule(LinkExtractor(allow=['/[a-zA-Z0-9-]+-\d+\.html$']), 'parse_item'),
    Rule(LinkExtractor(allow=['/[a-zA-Z0-9-/]+/$']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
