# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div[@id='page']/div[2]/table/tbody/tr/td[3]/table[1]/tbody/tr[2]/td[2]/table/tbody/tr/td[2]/h1",
    'price' : "//div[@id='page']/div[2]/table/tbody/tr/td[3]/table[@class='psub'][2]/tbody/tr[2]/td[3]/strong/font",
    'category' : "//div[@class='address']/a[7]",
    'description' : "//tbody/tr[2]/td[2]/table/tbody/tr/td[2]",
    'images' : "//td[@class='psub']/div[1]/a[@class='thickbox']/img/@src",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = 'myphamsach.com.vn'
allowed_domains = ['myphamsach.com.vn']
start_urls = ['http://myphamsach.com.vn/']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow = ['/[a-zA-Z0-9-]+_product_\d+_\d+.html']), 'parse_item'),
    Rule(LinkExtractor(allow = ['/[a-zA-Z0-9-]+_product_\d+.html']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
