# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//h1[@itemprop='name']",
    'price' : "//div[@class='summary entry-summary']/div[@itemprop='description']/p[1]/span/strong",
    'category' : "",
    'description' : "//div[@class='single-product-summary']/div[@class='woocommerce-tabs']/div[@class='panel entry-content']",
    'images' : "//div[@class='images']/div[@class='thumbnails columns-3']/a/@href",
    'canonical' : "//link[@rel='canonical']/@href",
    'base_url' : "",
    'brand' : "",
    'in_stock' : "",
    'guarantee' : "",
    'promotion' : ""
}
name = 'myviengialai.com'
allowed_domains = ['myviengialai.com']
start_urls = ['http://myviengialai.com/']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = ['']
rules = [
    Rule(LinkExtractor(allow=['/khuyen-mai/[a-zA-Z0-9-]+$']), 'parse_item'),
    Rule(LinkExtractor(allow=['/duoc-my-pham-cuskin']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
