# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//h1[@id='phagia_id']",
    'price' : "//div[@class='price']/span[@class='price_sale bold']",
    'category' : "//ul[@class='breadcrumbs-view']/li/a",
    'description' : "//div[@id='content_tab_one']/div[@class='hightlight']",
    'images' : "//ul[@class='list']/li[@class='fl']/a/img/@src",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = 'namanhplaza.vn'
allowed_domains = ['namanhplaza.vn']
start_urls = ['http://namanhplaza.vn/']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow=['/p\d+/']), 'parse_item'),
    Rule(LinkExtractor(allow=['/c\d+/']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
