# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div/div[@id='product-page']/div[@class='span4 product_description_mainblock productcol summary']/h1[@class='product_title entry-title']",
    'price' : "//div[@class='span4 product_description_mainblock productcol summary']/div[@class='main-info product_meta']/div[@class='price-block']/span[@class='amount']",
    'category' : "//div[@class='row']/div[@class='span12 breadcrumbs']/nav[@class='woocommerce-breadcrumb']/a",
    'description' : "//div[@class='tabs']/div[@id='content_tab_1']/p",
    'images' : "//div[@class='images']//a/@href",
    'canonical' : "//link[@rel='canonical']/@href",
    'base_url' : "",
    'brand' : ""
}
name = 'namlonggroup.vn'
allowed_domains = ['namlonggroup.vn']
start_urls = ['http://namlonggroup.vn']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow=['/san-pham/']), 'parse_item'),
    Rule(LinkExtractor(allow=['/danh-muc/']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
