# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//h1[@class='product-name']/span",
    'price' : "//div[@id='product-info']/p[@class='product-price']/span[@class='price new']",
    'category' : "//div[@id='top-breadcrumb']/span/a/span",
    'description' : "//div[@id='tabs_content_container']",
    'images' : "//div[@id='product-image']/a[@class='preview']/img/@src",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = 'nanakids.vn'
allowed_domains = ['nanakids.vn']
start_urls = ['http://www.nanakids.vn']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow=['\.html']), 'parse_item'),
    Rule(LinkExtractor(), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
