# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div[@class='content_center']/h1",
    'price' : "//div[@class='khungcart']/span[@class='giabande']",
    'category' : "//div[@class='content_title']/div[@class='contentit_trai']/span/a",
    'description' : "//td[@class='licachti']/div/div/div/div",
    'images' : "//div[@id='contentbb']//a/img/@src",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = 'ndsgauto.com'
allowed_domains = ['ndsgauto.com']
start_urls = ['http://ndsgauto.com/']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow=['/san-pham/','-sp+\d+\.html']), 'parse_item'),
    Rule(LinkExtractor(allow=['-dm+\d+\.html']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
