# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//span[@id='product_title']",
    'price' : "//span[@id='product_price']",
    'category' : "//div[@class='title-news menunav margintop']/ul/li/a",
    'description' : "",
    'images' : "//div[@class='detail-images']/div/div/a/@data-image",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = 'nefertiti.com.vn'
allowed_domains = ['nefertiti.com.vn']
start_urls = ['http://nefertiti.com.vn/danh-muc-san-pham/san-pham-130.html']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow=['/san-pham/[a-zA-Z0-9-]+-\d+\.html$']), 'parse_item'),
    Rule(LinkExtractor(allow=['/danh-muc-san-pham/[a-zA-Z0-9-]+-\d+\.html($|/page:\d+)']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
