# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//h1[@class='product_title entry-title']",
    'price' : "//div[@class='prices clearfix']/span[@class='amount']",
    'category' : "//ul[@class='mc-breadcrumb']/li/span",
    'description' : "//div[@class='tab-content']",
    'images' : "//div[@class='images']//div/a/@href|//div[@class='images']/a/@href",
    'canonical' : "//link[@rel='canonical']/@href",
    'base_url' : "",
    'brand' : ""
}
name = 'newcentury.vn'
allowed_domains = ['newcentury.vn']
start_urls = ['http://www.newcentury.vn/?page_id=6']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow=['\?product=']), 'parse_item'),
    Rule(LinkExtractor(allow=['\?product_cat=']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
