# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div[@class='product-shop']/h1[@class='product-name']",
    'price' : "//div[@class='product-shop']/div[@class='price-box']/span[@class='price']/b",
    'category' : "//div[@class='breadcrum-container']/ul/li",
    'description' : "//div[@class='main']/section[@class='product-collateral']/div[@id='pro-detail']",
    'images' : "//p[@class='product-image-zoom']/a/@href",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = 'newphone.vn'
allowed_domains = ['newphone.vn']
start_urls = ['http://newphone.vn/']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow=['/product-\d+/']), 'parse_item'),
    Rule(LinkExtractor(allow=['/catalog-\d+/']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
