# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div[@class='overview']/h1[@class='name']",
    'price' : "//div[@class='overview']/p/b[@class='red price']",
    'category' : "//div[@class='location']/a",
    'description' : "//div[@class='tabs']/div[@class='content_tab']",
    'images' : "//div[@class='img_product_detail']/div[@class='img_large']/a/@href",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = 'nguyenduc.com.vn'
allowed_domains = ['nguyenduc.com.vn']
start_urls = ['http://nguyenduc.com.vn']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow=['/[a-zA-Z0-9-]+\.html']), 'parse_item'),
    Rule(LinkExtractor(allow=['/c+\d+/[a-zA-Z0-9-]+\.html']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
