# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div[@class='info-pro']/div[@class='title-1 pagetit']/h1",
    'price' : "//div[@class='info-pro']/ul/li/b",
    'category' : "//div[@class='breadcrumbs']/span/a",
    'description' : "//div[@id='usual1']/div[@id='tab1']",
    'images' : "//div[@id='product-image']/a/img/@src",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = 'nguyenvuaudio.com.vn'
allowed_domains = ['nguyenvuaudio.com.vn']
start_urls = ['http://nguyenvuaudio.com.vn']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow=['/[a-zA-Z0-9-]+\.html']), 'parse_item'),
    Rule(LinkExtractor(allow=['/[a-zA-Z0-9-]+$']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
