# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div[@id='product-info-main']/div[@class='product-info']/div[@class='product-title']/h1",
    'price' : "//div[@class='price']/span/span/span",
    'category' : "//div[@class='helper-container']/div[@id='main-container']/div[@id='breadcrumb']/a",
    'description' : "//section[@id='noi-dung']/div[@class='wysiwyg']/p",
    'images' : "//div[@class='mainbox-body']/div/div[@class='product-wrap']/div//img/@src",
    'canonical' : "",
    'base_url' : "//base/@href",
    'brand' : ""
}
name = 'nhasachphuongnam.com'
allowed_domains = ['nhasachphuongnam.com']
start_urls = ['http://nhasachphuongnam.com']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow=['-p\d+\.html']), 'parse_item'),
    Rule(LinkExtractor(allow=['-c\d+\.html']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
