# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div[@class='product-name']/h1",
    'price' : "//div[@class='product-shop']//span[@class='price']",
    'category' : "//li[@class='product']/a",
    'description' : "//div[@id='ja-tab-products']/div[@class='ja-tab-content']",
    'images' : "//img[@id='image']/@src",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = 'nhasachthaiha.vn'
allowed_domains = ['nhasachthaiha.vn']
start_urls = ['http://nhasachthaiha.vn/']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow=['/chi-tiet/']), 'parse_item'),
    Rule(LinkExtractor(allow=['/category/']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
