# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div[@id='ctl00_pnDefault']/div[@class='maincol']/div[@id='ctl00_cpMainpage_Main1_ctl00_pnBox']/h1",
    'price' : "//div[@class='maincol']/div[@id='ctl00_cpMainpage_Main1_ctl00_pnBox']/div[@class='contentbox']/div[@class='productprice']",
    'category' : "//div[@class='topcol']/div[@class='path']/a/span",
    'description' : "//div[@id='ctl00_cpMainpage_Main1_ctl00_pnBox']/div[@class='contentbox']/div[@class='content']/p",
    'images' : "//div[@class='common']/a/img/@src",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = 'nhauthaicuuuc.com.vn'
allowed_domains = ['nhauthaicuuuc.com.vn']
start_urls = ['http://nhauthaicuuuc.com.vn']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow=['/p/']), 'parse_item'),
    Rule(LinkExtractor(allow=['/c/']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
