# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div[@id='chitietsp']//h1",
    'price' : "//div[@class='info']/div[@class='left']/div[@class='right']/p/span",
    'category' : "//p[@class='breadcrumb']/a",
    'description' : "//div[@id='more_info_block']/div[@id='description']",
    'images' : "//div[@class='bigimg']/div[@class='image-block']/img/@src",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = 'nhomdinhduong.vn'
allowed_domains = ['nhomdinhduong.vn']
start_urls = ['http://nhomdinhduong.vn']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(), 'parse_item'),
    Rule(LinkExtractor(), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
