# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//h1",
    'price' : "//div[@class='prices']/span[@class='productboxPrice']",
    'category' : "//div[@class='rightmenu_active']/a",
    'description' : "",
    'images' : "//div[@class='imagebox']/a/@href",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = 'ninomaxx.com.vn'
allowed_domains = ['ninomaxx.com.vn']
start_urls = ['http://www.ninomaxx.com.vn/zoneproduct/261-nam.aspx','http://www.ninomaxx.com.vn/zoneproduct/262-nu.aspx']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = ['']
rules = [
    Rule(LinkExtractor(allow=['/zone/\d+/product/[a-zA-Z0-9-]+-\d+\.aspx$']), 'parse_item'),
    Rule(LinkExtractor(allow=['/zoneproduct/\d+-[a-zA-Z0-9-]+\.aspx$']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
