# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div[@class='thread-details']/div[@class='clearfix']/div[@class='lf f50']/h1[@class='thread-details-title']",
    'price' : "//div[@class='cf thread-details-gia']/div[@class='lf f62']/div/font[@class='bold']",
    'category' : "//div[@id='oi_main']/div[@id='rME']/div[@class='thread-details thread-details-tohome']/a",
    'description' : "//div[@class='clearfix']/div[@class='lf']/div[@id='uiThreadDetails']/div[@class='thread-details']",
    'images' : "//div[@class='clearfix']/div[@class='lf f50']/div/div[@class='thread-details-avt']//img/@src",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = 'nipponshop.vn'
allowed_domains = ['nipponshop.vn']
start_urls = ['http://nipponshop.vn']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow=['/muanhom+-\d+/']), 'parse_item'),
    Rule(LinkExtractor(allow=['/sid+-\d+/']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
