# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div[@class='product-name']/h1",
    'price' : "//span[@class='regular-price']/span[@class='price']",
    'category' : "//div[@class='breadcrumbs']/ul/li/a",
    'description' : "//div[@class='std']/p",
    'images' : "//div[@class='product-img-box']//ul/li/a/@href",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = 'nkxlock.com'
allowed_domains = ['nkxlock.com']
start_urls = ['http://www.nkxlock.com/']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow=['/new-arrival/','/chainlocks/','/padlocks/']), 'parse_item'),
    Rule(LinkExtractor(deny=['/.*']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
