# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div[@class='container-fluid']/div[@class='row']/div[@class='col-lg-10 box-info-sp-rv']/h1",
    'price' : "//div[@class='row']/div[@class='col-lg-10 box-info-sp-rv']/p/span[@class='cl_do']",
    'category' : "//div/ol[@class='breadcrumb']/li/a",
    'description' : "//article/div[@class='container-fluid']/div[@class='row']/div[@class='col-lg-40 tongquan detail-element']",
    'images' : "//div[@class='zoomPad']/div[@class='zoomPup']/img/@src | //div[@class='col-lg-15 text-center img-sp-view']/a/@href | //div[@class='zoomPad']/img[@class='img-room-big']/@src",
    'canonical' : "//link[@rel='canonical']/@href",
    'base_url' : "",
    'brand' : ""
}
name = 'noithatphuongdong.vn'
allowed_domains = ['noithatphuongdong.vn']
start_urls = ['http://noithatphuongdong.vn']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow=['/p+/\d+/']), 'parse_item'),
    Rule(LinkExtractor(allow=['/d/','/m/','/t/']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
