# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//table[@class='bg-4']/tbody/tr[1]/td[2]",
    'price' : "//span[@id='ctl00_ctl00_ctl00_ContentPlaceHolder1_Master2ColHolder_Master3ColHolder_lv_Products_ctrl0_Label1']",
    'category' : "//div[@id='ParentDiv']/div[@class='title']/a",
    'description' : "//div[@id='tab1']",
    'images' : "//img[@id='ctl00_ctl00_ctl00_ContentPlaceHolder1_Master2ColHolder_Master3ColHolder_lv_Products_ctrl0_imagez']/@src",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = 'nova.com.vn'
allowed_domains = ['nova.com.vn']
start_urls = ['http://nova.com.vn/']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow = ['product-detail.aspx']), 'parse_item'),
    Rule(LinkExtractor(allow = ['sanpham.aspx', 'products.aspx']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
