# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div[@class='proTitle']/h1",
    'price' : "//strong/span[@class='price']",
    'category' : "//div[@id='breadcrumb']/div[@id='breadcrumb']/a",
    'description' : "//div[@id='detailProduct']/div[@class='wrap']/div[@class='wrap']/section[@class='wrap'][1]/div[@class='wrap']",
    'images' : "//div[@class='proImg']/div[@class='wrap']/a/@href",
    'canonical' : "//link[@rel='canonical']/@href",
    'base_url' : "//base/@href",
    'brand' : ""
}
name = 'okbuy.vn'
allowed_domains = ['okbuy.vn']
start_urls = ['http://okbuy.vn/']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = ['']
rules = [
    #Rule(LinkExtractor(), 'parse_item'),
    #Rule(LinkExtractor(), 'parse'),
    Rule(LinkExtractor(allow=['/[a-zA-Z0-9-]+-\d+(\.html$|/\d+$)']), 'parse_item_and_links'),
]
