# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//title",
    'price' : "//div[@class='price']/div[@class='price-gruop']/span[@class='price-new']",
    'category' : "//ol[@class='breadcrumb']/li/a/span",
    'description' : "//div[@class='tab-content']/div[@class='product_detail']",
    'images' : "//div[@class='image-additional clearfix']/a/@href",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = 'phohangda.com'
allowed_domains = ['phohangda.com']
start_urls = ['http://phohangda.com/']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow=['/san-pham/']), 'parse_item'),
    Rule(LinkExtractor(allow=['/danh-muc/']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
