# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div[@class='content'][1]/b",
    'price' : "//div[2]/div[@class='content'][2]/font",
    'category' : "//font[@class='btitle']",
    'description' : "",
    'images' : "//div[@class='text']/div[@class='text']/a/img/@src",
    'canonical' : "",
    'base_url' : "",
    'brand' : "",
    'in_stock' : "",
    'guarantee' : ""
}
name = 'phukienxinh.net'
allowed_domains = ['phukienxinh.net']
start_urls = ['http://phukienxinh.net/']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = ['']
rules = [
    Rule(LinkExtractor(allow=['/chi-tiet-san-pham/']), 'parse_item'),
    Rule(LinkExtractor(allow=['/san-pham/']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
