# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div[@id='box_product'][1]/div[@id='box_product_center']/div[1]",
    'price' : "//div[@class='view_event']/b",
    'category' : "//div[@id='box_product'][1]/div[@id='box_product_top']/a",
    'description' : "//div[@id='box_product']/div[3]/div[@id='tabs']/div/table",
    'images' : "//div[@id='box_product_center']/div/div/a[@class='lightbox']/@href",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = 'phuthai.com.vn'
allowed_domains = ['phuthai.com.vn']
start_urls = ['http://phuthai.com.vn']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow=['/sanpham+/\d+/[a-zA-Z0-9-]+\.html']), 'parse_item'),
    Rule(LinkExtractor(allow=['/nhomsanpham/'], deny=['']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
