# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div[@class='product-info']/div[@class='row-fluid']/div[@class='span6 product-img-box image-container']/h2",
    'price' : "//div[@class='price']/span[@class='price-new'] | //div[@class='row-fluid']/div[@class='span6 product-shop']/div[@class='price']/span",
    'category' : "//div[@class='container']/div[@class='row-fluid']/div[@class='breadcrumb']/a",
    'description' : "//div[@id='content']/div[@class='wrap-product']/div[@class='wrap-tabs']/div[@id='tab-description']",
    'images' : "//div[@class='product-info']/div[@class='row-fluid']/div[@class='span6 product-img-box image-container']/div[@class='image']//a/@href",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = 'plstore.vn'
allowed_domains = ['plstore.vn']
start_urls = ['http://plstore.vn']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow=['/[a-zA-Z0-9-]+\.html']), 'parse_item'),
    Rule(LinkExtractor(allow=['/[a-zA-Z0-9-]+/+$']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
