# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div[@class='item-detail']/h3",
    'price' : "//p[@class='item-price-p']/span[@class='detail-title blue']",
    'category' : "",
    'description' : "//div[@class='item-detail']/p[@class='item-size-p']",
    'images' : "//div[@class='item-left']/p/img/@src",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = 'ponagar.vn'
allowed_domains = ['ponagar.vn']
start_urls = ['http://ponagar.vn']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(), 'parse_item'),
    Rule(LinkExtractor(), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
