# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div[@id='content']/div[@class='top']/div[@class='center']/h1",
    'price' : "//div[@class='middle']/div[1]/table//tr/td[2]/table//tr[1]/td[2]",
    'category' : "",
    'description' : "//div[@id='container']/div[@id='content']/div[@class='middle']/div[@id='tab_description']",
    'images' : "//img[@id='image']/@src",
    'canonical' : "//link[@rel='canonical']/@href",
    'base_url' : "//base/@href",
    'brand' : ""
}
name = 'quanaoredep.com'
allowed_domains = ['quanaoredep.com']
start_urls = ['http://quanaoredep.com']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow=['/[a-zA-Z0-9-]+/[a-zA-Z0-9-]+$']), 'parse_item'),
    Rule(LinkExtractor(allow=['/[a-zA-Z-]+$']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
