# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div[@id='product-title']",
    'price' : "//div[@class='product-price ']",
    'category' : "",
    'description' : "//div[@id='spec']/div[@class='inner-tabify']",
    'images' : "//div[@id='product-image-carousel-placeholder']/a/@href",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = 'quaxinh.com'
allowed_domains = ['quaxinh.com']
start_urls = ['http://quaxinh.com/']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow = ['productdetail']), 'parse_item'),
    Rule(LinkExtractor(allow = ['browse_normal_recipient']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
