# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div[@class='product-info-item']/h1",
    'price' : "//div[@class='price-info']/div[@class='price']//span[@class='price-new']",
    'category' : "//div[@id='breadcrumb']/ul/li/a/span",
    'description' : "//div[@class='tabs-group']/div[@class='tab-content']",
    'images' : "//div[@class='carousel-inner']/div/a/@href",
    'canonical' : "//link[@rel='canonical']/@href",
    'base_url' : "//base/@href",
    'brand' : ""
}
name = 'rakuza.vn'
allowed_domains = ['rakuza.vn']
start_urls = ['http://rakuza.vn/']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow=['/[\w\d-]+-p\d+(c\d+)+\.html$']), 'parse_item'),
    Rule(LinkExtractor(allow=['/[\w\d-]+-(c\d+)+\.html($|\?page=\d+)']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
