# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div[@class='main-product-title']/h1[@class='mainbox-title']",
    'price' : "//div[@class='gia']/p[2]",
    'category' : "",
    'description' : "//div[@class='product-description product-box']/div[@class='full-description']",
    'images' : "//img[@id='ctl00_ContentPlaceHolder1_ImgDeal']/@src",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = 'redeal.vn'
allowed_domains = ['redeal.vn']
start_urls = ['http://redeal.vn/']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow = ['/[a-z-]+/[a-z-0-9]+/\d+.htm'], deny = ['/1.htm']), 'parse_item'),
    Rule(LinkExtractor(allow = ['/[a-z-]+/[a-z-0-9]+-\d+/\d+.htm']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
