# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//h1[@class='product-name']",
    'price' : "//p[@class='product-price price-box']/label/span[@class='price product-price']",
    'category' : "//ul[@class='breadcrumb']/li",
    'description' : "//p[@class='product_description']",
    'images' : "//div[@class='content-product-image']/div/img/@src",
    'canonical' : "//link[@rel='canonical']/@href",
    'base_url' : "",
    'brand' : "",
    'in_stock' : "",
    'guarantee' : "",
    'promotion' : ""
}
name = 'sachbanchay.vn'
allowed_domains = ['sachbanchay.vn']
start_urls = ['https://sachbanchay.vn/']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = ['']
rules = [
    Rule(LinkExtractor(deny=['/collections/[\w-]+($|\?page=\d+$)']), 'parse_item'),
    Rule(LinkExtractor(allow=['/collections/[\w-]+($|\?page=\d+$)']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
