# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div[@id='wrap-sanpham']/div[@class='gia']/div[@class='price']/p[@class='h']",
    'price' : "//div[@id='wrap-sanpham']/div[@class='gia']/div[@class='thongtin']/p[@class='giaban']",
    'category' : "//div[@id='content']/div[@id='main']/div[@class='pathway']/a",
    'description' : "//div[@id='thongso']/div[@class='wrap-ts']/div[@class='tabs']/div[@id='first']",
    'images' : "//div[@class='img']/div[@id='product-thumbs']/a/@href",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = 'sachvina.com'
allowed_domains = ['sachvina.com']
start_urls = ['http://www.sachvina.com']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow=['/[a-zA-Z0-9-_]+-p+\d+\.html']), 'parse_item'),
    Rule(LinkExtractor(allow=['-c+\d+\.html','-c+\d+-','-c+\d+-l+\d+\.html']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
