# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//h1[@class='mainbox-title']",
    'price' : "//p[@class='actual-price']//span[@class='price']/span[@class='price-num']",
    'category' : "//div[@class='breadcrumbs clearfix']/a",
    'description' : "//div[@class='product-main-info']/div[@class='cm-tabs-content tabs-content clearfix']",
    'images' : "//div[@class='border-image-wrap cm-preview-wrapper']/a/@href",
    'canonical' : "",
    'base_url' : "//base/@href",
    'brand' : ""
}
name = 'sachcoffee.vn'
allowed_domains = ['sachcoffee.vn']
start_urls = ['http://www.sachcoffee.vn/']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow=['/[a-zA-Z0-9-]+\.html$']), 'parse_item'),
    Rule(LinkExtractor(allow=['/[a-zA-Z0-9-]+/$']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
