# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//tr/td[@class='viewinfo']/div[@class='title']/text()",
    'price' : "//td[@class='viewinfo']/div[@class='left_price']/div[@class='productprice']/span",
    'category' : "//tr/td/div[@class='pagepathway']/a",
    'description' : "//tr/td/div[@class='intro']",
    'images' : "//tr/td[@class='viewimage']/div[@class='mainimage']//img/@src",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = 'sachvang.vn'
allowed_domains = ['sachvang.vn']
start_urls = ['http://sachvang.vn']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow=['/products/view/']), 'parse_item'),
    Rule(LinkExtractor(allow=['/products/category/']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
