# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//h1[@id='product_name']",
    'price' : "//div[@id='detail_price']/strong[@class='pricesell']",
    'category' : "//div[@id='breadcrumb']/div/a/span",
    'description' : "//div[@class='article']/div[@itemprop='description']",
    'images' : "//a[@itemprop='image']/@href",
    'canonical' : "//link[@rel='canonical']/@href",
    'base_url' : "",
    'brand' : ""
}
name = 'sanhangtot.com'
allowed_domains = ['sanhangtot.com']
start_urls = ['http://sanhangtot.com/']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    #Rule(LinkExtractor(), 'parse_item'),
    #Rule(LinkExtractor(), 'parse'),
    Rule(LinkExtractor(allow=['/[a-zA-Z0-9-]+\.html']), 'parse_item_and_links'),
]
