# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div[@class='block-img-attr']/div[@class='block-pro-attr']/div[@class='box-name item']/h1|//div[@class='name_product shop_color_hover']/h1/a/span",
    'price' : "//div[@class='price']/div[@class='current_price']/span|//div[@class='box-price']/div[@class='cur-price']/span[2]",
    'category' : "//div[@class='breadcrumb_detail util-clearfix']/div/a|//div[@class='breadcrumb-shop']/div/a",
    'description' : "//div[@class='content_tab active']|//div[@class='tab-product-detail']",
    'images' : "//img[@itemprop ='image']/@src",
    'canonical' : "//link[@rel='canonical']/@href",
    'base_url' : "",
    'brand' : "",
    'in_stock' : "",
    'guarantee' : "",
    'promotion' : ""
}
name = 'sendo.vn'
allowed_domains = ['sendo.vn']
start_urls = ['https://www.sendo.vn/']
tracking_url = 'http://go.masoffer.net/v1/D0zn-pHRAE4DaFgNxmZGX1K74P6vTGNwQdO2hmOXHjg/?url=,utm_source=masoffer'
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = ['']
rules = [
    Rule(LinkExtractor(allow=['/san-pham/[a-zA-Z0-9-]+-\d+/']), 'parse_item'),
    Rule(LinkExtractor(allow=['/[a-zA-Z0-9-]+/($|\?category_id=\d+&sortType=vasup_desc&p=\d+)'], deny=['http://blog.sendo.vn/','/san-pham/[a-zA-Z0-9-]+-\d+/']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
