# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div[@id='bar2']/div[@class='brmain']/h1",
    'price' : "//div[@class='detail_pro']/div[@class='chitietsp']/div[2]/span",
    'category' : "",
    'description' : "//div[@class='detail_pro']/div[@class='chitietsp']/div[4]",
    'images' : "//div[@class='detail_pro']/div[@class='detail_proimg']/img/@src",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = 'serviceapple.vn'
allowed_domains = ['serviceapple.vn']
start_urls = ['http://serviceapple.vn']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow=['_dproduct-view-']), 'parse_item'),
    Rule(LinkExtractor(allow=['_mproduct-']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
