# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div[@class='product-description']/div[@class='pd-name']/h1",
    'price' : "//div[@class='pctemp chudam']/div/span[@class='sub1 txt_20 chudam']",
    'category' : "//div[@id='location_hunv']/div[1]/a",
    'description' : "//div[@class='pcdetails']/div/p",
    'images' : "//div[@class='framehb imgd11 pn_img']//a/@href | //div[@class='thumb-view']//a/@href",
    'canonical' : "//link[@rel='canonical']/@href",
    'base_url' : "",
    'brand' : ""
}
name = 'shopbevame.com'
allowed_domains = ['shopbevame.com']
start_urls = ['http://shopbevame.com/']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(), 'parse_item'),
    Rule(LinkExtractor(), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
