# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div[@class='product_info']/h1[@class='product-name']",
    'price' : "//div[@class='product_info']//span[@class='price']",
    'category' : "//div[@class='breadcrumbs']/a",
    'description' : "//div[@class='std']/p",
    'images' : "//img[@id='largeImage']/@src",
    'canonical' : "//link[@rel='canonical']/@href",
    'base_url' : "",
    'brand' : "",
    'in_stock' : "",
    'guarantee' : "",
    'promotion' : ""
}
name = 'shopping.pnj.com.vn'
allowed_domains = ['shopping.pnj.com.vn']
start_urls = ['https://shopping.pnj.com.vn/']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = ['']
rules = [
    Rule(LinkExtractor(allow=['/[a-zA-Z0-9-]+-\d+\.html$']), 'parse_item'),
    Rule(LinkExtractor(allow=['/[a-zA-Z0-9-]+\.html($|\?p=\d+)'], deny=['/[a-zA-Z0-9-]+-\d+\.html$']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
