# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div[@class='row product-content-columns']/div[@class='col-sm-7 col-lg-5 product_page-right']/div[@class='general_info product-info']/h1[@class='product-title']",
    'price' : "//div[@class='col-sm-7 col-lg-5 product_page-right']/div[@class='general_info product-info']/div[@class='price-section']/span[@class='price-new']",
    'category' : "//div[@class='container']/ul[@class='breadcrumb']/li/a",
    'description' : "//div[@class='container']/div[@class='row']/div[@id='content']/div[@id='tab-description']",
    'images' : "//div[@class='row']/div[@id='content']/div[@class='row product-content-columns']/div[@class='col-sm-5 col-lg-7 product_page-left']//img/@src",
    'canonical' : "//link[@rel='canonical']/@href",
    'base_url' : "//base/@href",
    'brand' : ""
}
name = 'shopphuongnguyen.com'
allowed_domains = ['shopphuongnguyen.com']
start_urls = ['http://shopphuongnguyen.com']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow=['/[a-z0-9]+$']), 'parse_item'),
    Rule(LinkExtractor(allow=['/\.*']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
