# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//form[@id='ECS_FORMBUY']/div[@class='clearfix']/h1[@class='f_l']",
    'price' : "//li[@class='clearfix']/dd[@class='ddL']/font[@id='ECS_SHOPPRICE']",
    'category' : "//div[@class='block box']/div[@id='ur_here']/a",
    'description' : "//div[@class='box']/div[@class='box_1']/div[@id='com_v']",
    'images' : "//div[@class='imgInfo']/img/@src",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = 'shoptihon.com'
allowed_domains = ['shoptihon.com']
start_urls = ['http://shoptihon.com']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow=['/\d+-[a-zA-Z0-9-]+\.html']), 'parse_item'),
    Rule(LinkExtractor(allow=['/danh-muc+-[a-zA-Z0-9-]+\.html']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
