# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//h1[@class='field-title-field']",
    'price' : "//div[@class='field-commerce-price inline']",
    'category' : "//div[@class='content-page col-sm-12']/ol[@class='breadcrumb']/li/a",
    'description' : "//div/div[@class='row']/div[@class='node-content col-sm-12']/div[@class='product-field']",
    'images' : "//div[@class='region region-content']/div/div[@class='row']/div[@class='col-md-6 node-left']//img/@src",
    'canonical' : "//link[@rel='canonical']/@href",
    'base_url' : "",
    'brand' : ""
}
name = 'shopyeucon.com'
allowed_domains = ['shopyeucon.com']
start_urls = ['http://shopyeucon.com']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow=['/\d+$']), 'parse_item'),
    Rule(LinkExtractor(allow=['/san-pham/']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
