# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "/html/body/div[@class='sp-wrap main-bg clearfix'][2]/div[@class='clearfix']/div/div/div[@class='sp-inner clearfix']/div[@class='productdetails-view'][2]/div/div/div/h1",
    'price' : "/html/body/div[@class='sp-wrap main-bg clearfix'][2]/div[@class='clearfix']/div/div/div[@class='sp-inner clearfix']/div[@class='productdetails-view'][2]/div/div/div[@class='spacer-buy-area'][3]/div/div[@class='PricesalesPrice'][2]/span[@class='PricesalesPrice']",
    'category' : "/html/body/div[@class='sp-wrap top-main clearfix']/div/span[@class='breadcrumbs']/a[3]",
    'description' : "/html/body/div[@class='sp-wrap main-bg clearfix'][2]/div[@class='clearfix']/div/div/div[@class='sp-inner clearfix']/div[@class='productdetails-view'][2]/div[@class='product-description'][2]",
    'images' : "/html/body/div[@class='sp-wrap main-bg clearfix'][2]/div[@class='clearfix']/div/div/div[@class='sp-inner clearfix']/div[@class='productdetails-view'][2]/div/div/div[@class='floatleft product_images']/div[@class='main-image']/a/img/@src",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = 'shop79.vn'
allowed_domains = ['shop79.vn']
start_urls = ['http://shop79.vn']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow=['/[a-zA-Z0-9-]+-detail+$']), 'parse_item'),
    Rule(LinkExtractor(allow=['/[a-zA-Z0-9-]+$']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
