# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div[@class='pr_info']/h4",
    'price' : "//p/span[@class='regular-price']",
    'category' : "//div[@class='breadcrumb']/a",
    'description' : "//div[@class='detail']",
    'images' : "//div[@class='zoomPad']/img[@class='defaultImage']/@src",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = 'sieuthicafe.vn'
allowed_domains = ['sieuthicafe.vn']
start_urls = ['http://sieuthicafe.vn/vn/']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow=['/vn/[a-zA-Z0-9-]+\.html$']), 'parse_item'),
    Rule(LinkExtractor(allow=['/vn/[a-zA-Z0-9-]+($|\?p=\d+)']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
