# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//span[@class='titlelink']/h3",
    'price' : "//p[@class='price']",
    'category' : "//h2/span[@id='ctl13_ctl00_lblCategoryname']",
    'description' : "//div[@class='divproduct']/div[3]",
    'images' : "//img[@class='imgproductdetail']/@src",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = 'sieuthitrangsuc.vn'
allowed_domains = ['sieuthitrangsuc.vn']
start_urls = ['http://www.sieuthitrangsuc.vn']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow = ['/[a-z-]+-\d+/']), 'parse_item'),
    Rule(LinkExtractor(allow = ['\.vn/[a-z0-9-]+.html'], deny = ['gioithieu.html', 'tintuc.html','huongdan.html','thanhtoan.html','lienhe.html']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
