# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div[@class='product-info']/h2[@class='title']",
    'price' : "//span[@class='price']",
    'category' : "//div[@class='br']/a",
    'description' : "//div[@id='description']/p",
    'images' : "//a[@class='z-fea']/img/@src",
    'canonical' : "//link[@rel='canonical']/@href",
    'base_url' : "",
    'brand' : ""
}
name = 'sieuthiyte.com.vn'
allowed_domains = ['sieuthiyte.com.vn']
start_urls = ['http://sieuthiyte.com.vn/']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow=['http://sieuthiyte.com.vn/[a-zA-Z0-9-]+-\d+\.html']), 'parse_item'),
    Rule(LinkExtractor(allow=['/[a-zA-Z0-9-]+/$']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
