# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div[@class='row-fluid']/div[@class='span6']/div/h1",
    'price' : "//div[@class='divPrice']/div/p[@class='s-price s-promo txtOrange']/span",
    'category' : "//h2[@class='breadcrumb']/ul[@id='breadcrumbMobile']/li/a",
    'description' : "//div[@class='i-Contents']",
    'images' : "//div[@id='itmBig']/a[@class='imgCenterD gallerythumb']/img/@src",
    'canonical' : "//link[@rel='canonical']/@href",
    'base_url' : "",
    'brand' : ""
}
name = 'sieuthidienmaychinhhang.vn'
allowed_domains = ['sieuthidienmaychinhhang.vn']
start_urls = ['http://sieuthidienmaychinhhang.vn']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow=['/san-pham/[a-zA-Z0-9-]+-\d+.html$']), 'parse_item'),
    Rule(LinkExtractor(allow=['/danh-muc/[a-zA-Z0-9-]+-\d+.html']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
