# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//table//tr[3]/td[1]/table//tr/td/table//tr/td/table//tr/td/table//tr/td/font/b",
    'price' : "//table//tr[3]/td/table/tbody/tr[1]/td/table//tr/td[2]/table//tr/td/table//tr/td/font",
    'category' : "//table//tr/td[@class='black']/a[@class='B']",
    'description' : "//table//tr[@id='menu_cat1']/td",
    'images' : "//table/tbody/tr[3]/td/table/tbody/tr[1]/td/table/tbody/tr/td[1]/img/@src",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = 'sieuthithe.vn'
allowed_domains = ['sieuthithe.vn']
start_urls = ['http://www.sieuthithe.vn/']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow=['/\?+frame=product']), 'parse_item'),
    Rule(LinkExtractor(allow=['/\?+frame=category']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
