# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div[@class=' tensanpham clearfix']",
    'price' : "//li[@class='clearfix'][6]/dd/font[@class='shop']",
    'category' : "//div[@id='ur_here']/a",
    'description' : "//div[@class='AreaR']/div[@class='box']",
    'images' : "//div[@class='picture']/a/@href",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = 'sieuthitainha.com.vn'
allowed_domains = ['sieuthitainha.com.vn']
start_urls = ['http://sieuthitainha.com.vn/']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow=['/\d+-[a-zA-Z0-9-]+\.html$']), 'parse_item'),
    Rule(LinkExtractor(allow=['/danh-muc-\d+-[a-zA-Z0-9-_]+\.html$']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
