# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div[@class='product-name']/h1",
    'price' : "//div[@class='price-box-detail']/span",
    'category' : "//li[@class='home']/a[@class='level-top']/span",
    'description' : "//div[@id='tab-gioithieu']/div/div/div[@class='content']",
    'images' : "//div[@class='box-img']/a[@id='zoom1']/@href | //div[@id='image-show']/div/ul/li/a/@href",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = 'siki.vn'
allowed_domains = ['siki.vn']
start_urls = ['http://siki.vn/']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow=['/san-pham/']), 'parse_item'),
    Rule(LinkExtractor(allow=['/danh-muc/'], deny=['seem=']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
