# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div[@class='product-info']/p[@id='p-name']",
    'price' : "//div[@class='product-info']/p/span[@id='p-price']",
    'category' : "//p[@class='navi']/a",
    'description' : "//div[@id='product-tabs']/div[@id='features']//p[@class='MsoNormal']",
    'images' : "//div[@id='image-okmen']/div[@class='slides_control']/a/img/@src",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = 'so8mobile.com'
allowed_domains = ['so8mobile.com']
start_urls = ['http://so8mobile.com/']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow=['san-pham']), 'parse_item'),
    Rule(LinkExtractor(allow=['danh-muc']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
