# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div[@class='header_layer_2']/h1[@class='header  headline']/span/label",
    'price' : "//div[@class='chitiet_sanpham_bangchia_cell_thongtin']/div[@class='div_gia']/span[@class='giavnd']/span",
    'category' : "",
    'description' : "//div[@class='boxgiua_lop1']/div[@class='boxgiua_lop2']/div[@class='bang_chi_tiet_san_pham']/div[@class='mo_ta_sanpham']",
    'images' : "//div[@class='div_anh']/div[@class='anh_khac_div']/a/@href",
    'canonical' : "",
    'base_url' : "//base/@href",
    'brand' : ""
}
name = 'solarv.vn'
allowed_domains = ['solarv.vn']
start_urls = ['http://solarv.vn']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow=['/\d+/[^(v=0)]+\.html$']), 'parse_item'),
    Rule(LinkExtractor(allow=['/\d+/v=0/']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
