# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div[@class='info']//h1",
    'price' : "//div[@id='price_ref']/span[contains(@id,'value_price')]",
    'category' : "",
    'description' : "//div[@id='technique_param_product']//p",
    'images' : "//ul[@class='ad-thumb-list']/li/a/img/@class",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = 'solo.vn'
allowed_domains = ['solo.vn']
start_urls = ['http://solo.vn/']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow = ['/[a-z0-9-]+-p\d+.html']), 'parse_item'),
    Rule(LinkExtractor(allow = ['/[a-z0-9-\/]+.html'], deny = ['sitemap.html', 'khoi-phuc-mat-khau.html', 'dangkywebsite', 'tim-kiem.html']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
