# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div[@class='header_4']",
    'price' : "//div[@class='container']/div/p/span[@class='price_detail']",
    'category' : "//div[@class='boxProduct']/div[2]/b/a",
    'description' : "//div[@id='tabs-1']",
    'images' : "//div[@class='container']/img/@src",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = 'songhuong.vn'
allowed_domains = ['songhuong.vn']
start_urls = ['http://songhuong.vn']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow = ['/file,detail/.*']), 'parse_item'),
    Rule(LinkExtractor(allow = ['/catAlias.*']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
