# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div[@class='infodetailpd-product']/h1",
    'price' : "//div[@class='ifdetails']/span[@class='bredprice']",
    'category' : "",
    'description' : "//div[@class='descdetails-product']/div[@class='tab-content']",
    'images' : "//div[@class='polaroid']/div[@class='inner']/img/@src",
    'canonical' : "//link[@rel='canonical']/@href",
    'base_url' : "//base/@href",
    'brand' : "//div[@class='infodetailpd-product']/div[@class='ifdetails']/b[2]/a",
    'in_stock' : "//div[@class='infodetailpd-product']/div[@class='ifdetails']/span[3]",
    'guarantee' : "",
    'promotion' : ""
}
name = 'spro.vn'
allowed_domains = ['spro.vn']
start_urls = ['http://spro.vn/']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = ['']
rules = [
    Rule(LinkExtractor(allow=['/[a-zA-Z0-9-]+\.html$']), 'parse_item'),
    Rule(LinkExtractor(allow=['/[a-zA-Z0-9-]+($|\?page=\d+$)']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
