# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//form[@id='product']/h3",
    'price' : "//div[@class='product_detail_description']/h3[@class='newprice detail_price']",
    'category' : "//ol[@class='breadcrumb']/a",
    'description' : "//div[@class='tab_descrition_wp']//p",
    'images' : "//ul[@class='slides']/li[1]/a[@class='fancybox']/img/@src",
    'canonical' : "//link[@rel='canonical']/@href",
    'base_url' : "//base/@href",
    'brand' : ""
}
name = 'studionoithat.com'
allowed_domains = ['studionoithat.com']
start_urls = ['http://studionoithat.com/']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow=['/[\w\d-]+\.html$']), 'parse_item'),
    Rule(LinkExtractor(allow=['/[\w\d-]+$']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
