# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//h1/strong|//article[@class='page-l l-74']/h2/strong",
    'price' : "//div[@class='price-sell']/p/strong",
    'category' : "//section[@class='linkway']/a",
    'description' : "//div[@class='product-detail boxbor']/p",
    'images' : "//div[@class='img-view']//img/@src",
    'canonical' : "//link[@rel='canonical']/@href",
    'base_url' : "",
    'brand' : "",
    'in_stock' : "",
    'guarantee' : "",
    'promotion' : ""
}
name = 'subin.vn'
allowed_domains = ['subin.vn']
start_urls = ['https://subin.vn']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = ['']
rules = [
    Rule(LinkExtractor(allow=['/[a-zA-Z0-9-]+\.html']), 'parse_item'),
    Rule(LinkExtractor(allow=['/[a-zA-Z0-9-]+-c+\d+/']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
