# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div[@class='idx-prod']/div/div[@id='image']/h1",
    'price' : "//div[@class='idx-prod']/div/div[@id='image']/font/b",
    'category' : "//div[@class='idx-prod']/h3/a",
    'description' : "//div[@id='image']/div[@id='detail']/p",
    'images' : "//div[@id='detail']/div[@id='item-image']/a/@href",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = 'superbuy.vn'
allowed_domains = ['superbuy.vn']
start_urls = ['http://www.superbuy.vn']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow=['/i+\d+\.*']), 'parse_item'),
    Rule(LinkExtractor(allow=['/c+\d+\.*']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
