# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div[@class='product_left']/div[@class='product_detail_right']/h3",
    'price' : "//div[@class='product_price']/span[@class='price_km']",
    'category' : "//div[@class='Content_banner']/div[@id='navigator']/div/a/span",
    'description' : "//div[@class='thong_tin_san_pham']/div[@class='tabs_content_container']",
    'images' : "//div[@class='slide_product']/div[@class='jqzoom_bg']/a/@href",
    'canonical' : "",
    'base_url' : "",
    'brand' : "",
    'in_stock' : "",
    'guarantee' : "",
    'promotion' : ""
}
name = 'synstyle.com.vn'
allowed_domains = ['synstyle.com.vn']
start_urls = ['http://synstyle.com.vn/']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = ['']
rules = [
    Rule(LinkExtractor(allow=['/xem-chi-tiet/']), 'parse_item'),
    Rule(LinkExtractor(allow=['/danh-muc/','/category/']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
