# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div[@id='overview_info']/h1",
    'price' : "//div[@id='overview_info']/div[@id='price_detail']",
    'category' : "//div[@id='location']/a",
    'description' : "//div[@id='content_detail_info']/div[@id='motachitiet']/p | //div[@id='overview_info']/div[@id='summary_detail']",
    'images' : "//div[@id='img_large']/div[@class='zoomp']/a/@href",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = 'tanthaibinh.vn'
allowed_domains = ['tanthaibinh.vn']
start_urls = ['http://tanthaibinh.vn']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow=['_id+\d+\.html']), 'parse_item'),
    Rule(LinkExtractor(allow=['_dm+\d+\.html'], deny=['filter=']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
