# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div[@class='ProductMain']/div[@class='product-title']/h1",
    'price' : "//div[@class='Value']/em | //div[@class='Row Price']/div[@class='ProductPrice VariationProductPrice']",
    'category' : "//div[@id='Breadcrumb']/ul/li/a",
    'description' : "//div[@class='ProductDescriptionContainer']/table//tr",
    'images' : "//div[@class='ProductThumbImage']/a/@href ",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = 'techmartvn.vn'
allowed_domains = ['techmartvn.vn']
start_urls = ['http://techmartvn.vn']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow=['/[a-zA-Z0-9-]+-\d+\.html']), 'parse_item'),
    Rule(LinkExtractor(allow=['/\d+\.html']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
