# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div[@id='wrapper']/div[@class='ptitle']/h1",
    'price' : "//div[@class='pi_content']/div[@class='pprice']/span[@class='price']",
    'category' : "//div[@id='breadcrumb']/ul/li[@class='bc_next']/a/span",
    'description' : "//div[@id='content']/div[@id='tab_description']",
    'images' : "//div[@id='tabI_slider']/img/@src | //div[@class='oneByOne_item']/img/@src",
    'canonical' : "",
    'base_url' : "//base/@href",
    'brand' : "",
    'in_stock' : "",
    'guarantee' : ""
}
name = 'techone.vn'
allowed_domains = ['techone.vn']
start_urls = ['http://www.techone.vn/']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = ['']
rules = [
    Rule(LinkExtractor(allow=['techone\.vn/[a-zA-Z0-9-]+-\d+\.html']), 'parse_item'),
    Rule(LinkExtractor(allow=['/[a-zA-Z0-9-]+/($|&page=\d+$)'], deny=['/news/']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
