# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//li[@class='ttDeal']/h2",
    'price' : "//ul[@class='boxLastDeal']/li/h2/b",
    'category' : "",
    'description' : "//div[@class='special']",
    'images' : "//div[@class='jcarousel-clip jcarousel-clip-horizontal']/ul/li/div[@class='floatLeft']/a/img/@src",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = 'tell.vn'
allowed_domains = ['tell.vn']
start_urls = ['http://tell.vn/']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(), 'parse_item'),
    Rule(LinkExtractor(), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
