# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div[@class='content_left']/div[@class='product_detail_right']/div/h1[@class='title']",
    'price' : "//span/div/div[@class='price']/span",
    'category' : "//div[@class='fix_width_1200']/div[@class='content_left']/h3[@class='product_breadcrumb']/a",
    'description' : "//div[@class='fix_width_1200']/div[@class='content_left']/div[@id='tab_0']",
    'images' : "//div[@class='product_detail_picture']/div[@class='picture_container']/a/@href",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = 'thaihamobile.vn'
allowed_domains = ['thaihamobile.vn']
start_urls = ['http://thaihamobile.vn']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = ['']
rules = [
    #Rule(LinkExtractor(), 'parse_item'),
    #Rule(LinkExtractor(), 'parse'),
    Rule(LinkExtractor(allow=['\.html($|\?page=\d+$)']), 'parse_item_and_links'),
]
