# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div[@id='product-info']/h1",
    'price' : "//div[@class='price-buy']/div[@class='price']/span/span[@class='new-price']",
    'category' : "",
    'description' : "//div[@class='pfr-l']/div[@class='pr-l-snv']/div[@class='pr-l-snv-i']",
    'images' : "//div[@class='image-large']/div/a/@href",
    'canonical' : "",
    'base_url' : "",
    'brand' : "",
    'in_stock' : "",
    'guarantee' : "",
    'promotion' : ""
}
name = 'thanhcongmart.com'
allowed_domains = ['thanhcongmart.com']
start_urls = ['http://thanhcongmart.com/']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = ['']
rules = [
    Rule(LinkExtractor(allow=['/san-pham/']), 'parse_item'),
    Rule(LinkExtractor(allow=['/p_category/[a-zA-Z0-9-/]+\.html($|\?page=\d+$)']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
