# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//td/span[@class='name']",
    'price' : "//div[@class='productInfo fr']/table//td/span[@class='price']",
    'category' : "//div[@class='column-left fl']/div[@class='content clearfix']/div[@class='section-headline clearfix']/a",
    'description' : "//div[@class='content clearfix']/div[@class='productDetail clearfix']/div[@class='productDetail']/h3",
    'images' : "//div[@class='productImg fl']/a[@class='fancybox-effects-a']/@href",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = 'thegioimay.vn'
allowed_domains = ['thegioimay.vn']
start_urls = ['http://www.thegioimay.vn']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow=['vn/.*\d+.*\.html$'], deny=['/bai-viet/','/nhan-hieu/']), 'parse_item'),
    Rule(LinkExtractor(allow=['/san-pham/','page='], deny=['/nhan-hieu/']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
