# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//table[@class='catalog-detail'][2]//tr[1]/td[1]/span",
    'price' : "//div[@class='pro'][3]/span[@class='value']",
    'category' : "//ul[@class='breadcrumb-navigation']/li/a",
    'description' : "//table[@class='catalog-detail'][2]//tr[1]/td[1]",
    'images' : "//div[@id='catalog-detail-main-image']/a/@href",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = 'thegioigiay.vn'
allowed_domains = ['thegioigiay.vn']
start_urls = ['http://thegioigiay.vn']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow=['/products+/\d+/\d+/']), 'parse_item'),
    Rule(LinkExtractor(allow=['/products+/\d+/']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
