# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//section[@id='content']/div/div[@class='summary']/h1[@class='product_title entry-title']",
    'price' : "//div[@class='summary']/div/p[@class='price']/span[@class='amount']",
    'category' : "//div[@class='wrapper main-content row visible']/div[@class='breadcrumb breadcrumbs woo-breadcrumbs']/div[@class='breadcrumb-trail']/a",
    'description' : "//div/div[@class='summary']/div/p",
    'images' : "//div[@class='images']/div[@class='thumbnails']/a/@href",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = 'thegioidodung.com'
allowed_domains = ['thegioidodung.com']
start_urls = ['http://thegioidodung.com']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow=['/[a-zA-Z0-9-]+/+$']), 'parse_item'),
    Rule(LinkExtractor(allow=['/[a-zA-Z0-9-]']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
