# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//form[@id='ECS_FORMBUY']/div[@class='clearfix']",
    'price' : "//font[@id='ECS_SHOPPRICE']",
    'category' : "//div[@id='ur_here']/a",
    'description' : "//div[@id='com_v']",
    'images' : "//div[@class='imgInfo']/a/@href",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = 'thegioicuabevn.com'
allowed_domains = ['thegioicuabevn.com']
start_urls = ['http://thegioicuabevn.com/']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow=['-cls\d+\.html$']), 'parse_item'),
    Rule(LinkExtractor(allow=['-cat\d+-']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
