# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div[@class='cols-right']/h1[@class='title']",
    'price' : "//b[@style='font-size: 18px; color: #CC0000;']",
    'category' : "//div[@id='breadcrumbs']/a",
    'description' : "//div[@id='product-tab']/div[@class='tab_container1']",
    'images' : "//div[@class='cols-left']/div[@class='img-main']/img/@src | //div[@class='cols-left']/div[@class='img-small']/a/@href",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = 'thegioidientudienlanh.com.vn'
allowed_domains = ['thegioidientudienlanh.com.vn']
start_urls = ['http://thegioidientudienlanh.com.vn/']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow=['/san-pham-']), 'parse_item'),
    Rule(LinkExtractor(allow=['/loai-hang-']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
