# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//h1[@class='page-header']",
    'price' : "//div[@class='content']/div/span[@class='uc-price']",
    'category' : "",
    'description' : "//div[@class='field-items']/div[@class='field-item even']",
    'images' : "//li[@class='gallery-slide']/a/@href",
    'canonical' : "//link[@rel='canonical']/@href",
    'base_url' : "",
    'brand' : ""
}
name = 'thienmoclinh.com.vn'
allowed_domains = ['thienmoclinh.com.vn']
start_urls = ['http://www.thienmoclinh.com.vn/san-pham']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow=['/products/']), 'parse_item'),
    Rule(LinkExtractor(allow=['/san-pham']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
