# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div[@class='kido_detailt']/h1",
    'price' : "//div[@class='prod_pricebox_price_final']/span|//div[@class='kido-giahomnay']/div[@class='kido-sale']/span",
    'category' : "//ul[@class='ls path']/li/h2/a/span|//ul[@class='breadcrumb']/li/h4/a",
    'description' : "//div[@id='p-introduct-news']/div[@class='p-news']",
    'images' : "//ul[@class='ls pro-image-list']/li/a/@href|//div[@class='pro-image']/a[@class='pro-image-large']/img/@src",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = 'thietbivesinh.com'
allowed_domains = ['thietbivesinh.com']
start_urls = ['http://thietbivesinh.com/']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow=['/[\w-]+\d+[\w-]+/']), 'parse_item'),
    Rule(LinkExtractor(allow=['/[a-zA-Z-]+/']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
