# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div[@class='title_Detail']/h4",
    'price' : "//div[@class='summary']/p[1]/span[@class='item_price']",
    'category' : "//div[@class='top_lst_left']/div//a",
    'description' : "//div[@id='tab1']",
    'images' : "//div[@class='detail']/img/@src",
    'canonical' : "//link[@rel='canonical']/@href",
    'base_url' : "",
    'brand' : ""
}
name = 'thietbivesinhvn.com.vn'
allowed_domains = ['thietbivesinhvn.com.vn']
start_urls = ['http://thietbivesinhvn.com.vn/trang-chu.htm']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow = ['/san-pham/\d+/\d+/\d+/[a-zA-Z0-9-]+\.htm']), 'parse_item'),
    Rule(LinkExtractor(allow = ['/san-pham/\d+/*?\d*/[a-zA-Z0-9-]+\.htm']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
