# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//tr/td/h1[@id='chitiet1']",
    'price' : "//table[@id='bochinh'][1]//tr[2]/td[2]/table//tr[2]/td/span[@id='gia']",
    'category' : "//td[@id='asanpham']/h2/a[@id='sanpham1']",
    'description' : "//fieldset[@id='bochinh']",
    'images' : "//td/a[@id='thumb1']/img/@src",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = 'thietbivesinh.net.vn'
allowed_domains = ['thietbivesinh.net.vn']
start_urls = ['http://thietbivesinh.net.vn']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow=['_c_']), 'parse_item'),
    Rule(LinkExtractor(allow=['_m_']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
