# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div[@class='noidung']/div[@class='tensp']",
    'price' : "//tr[@class='gia_km']",
    'category' : "",
    'description' : "",
    'images' : "//div[@class='pic_chitiet']/img/@src",
    'canonical' : "",
    'base_url' : "//base/@href",
    'brand' : ""
}
name = 'thoitranghanquoc24.vn'
allowed_domains = ['thoitranghanquoc24.vn']
start_urls = ['http://thoitranghanquoc24.vn/index.php']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow=['/vi/spct/id\d+/']), 'parse_item'),
    Rule(LinkExtractor(allow=['/index.php']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
