# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//h1[@class='product-title']",
    'price' : "//h3[@class='product-price ']",
    'category' : "//div[@class='navi']/a",
    'description' : "//div[@class='iTab'][1]",
    'images' : "//div[@class='iImg']/a[@class='jqZoom']/@href",
    'canonical' : "//link[@rel='canonical']/@href",
    'base_url' : "",
    'brand' : ""
}
name = 'thoitrangxuatkhau.com'
allowed_domains = ['thoitrangxuatkhau.com']
start_urls = ['http://thoitrangxuatkhau.com/']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow=['/[a-zA-Z0-9-]+-\d+\.html$'], deny=['tin-tuc']), 'parse_item'),
    Rule(LinkExtractor(allow=['/[a-zA-Z0-9-]+\.html'], deny=['-\d+\.html']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
