# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div[@class='product-title']/h1",
    'price' : "//div[@class='product-price']/span",
    'category' : "//ol[@class='breadcrumb breadcrumb-arrow hidden-sm hidden-xs']/li/a",
    'description' : "//div[@id='mota']//p",
    'images' : "//div[@class='owl-carousel owl-theme hidden-xs']//a/@data-image",
    'canonical' : "//link[@rel='canonical']/@href",
    'base_url' : "",
    'brand' : ""
}
name = 'thoitranglinda.com'
allowed_domains = ['thoitranglinda.com']
start_urls = ['http://thoitranglinda.com/']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow=['/products/[a-zA-Z0-9-]+']), 'parse_item'),
    Rule(LinkExtractor(allow=['/collections/[a-zA-Z0-9-]+($|\?page=\d+)']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
