# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div[@class='product-info']/h1[@class='title']",
    'price' : "//div[@class='clearfix']/span[@class='price-single']/span",
    'category' : "//div[@id='breadcrumbs']/a",
    'description' : "//div[@id='left-column']/div[@class='post clearfix']/p",
    'images' : "//div[@id='product-slides']/div[@class='item-slide']/a/@href",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = 'thucphamchucnangaz.vn'
allowed_domains = ['thucphamchucnangaz.vn']
start_urls = ['http://www.thucphamchucnangaz.vn']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow=['/[a-zA-Z0-9-]+\.html']), 'parse_item'),
    Rule(LinkExtractor(allow=['/[a-zA-Z0-9-]+$']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
