# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div[@class='summary entry-summary']/h1[@class='product_title entry-title']",
    'price' : "//p[@class='price']/ins/span[@class='amount']|//p[@class='price']/span[@class='amount']",
    'category' : "",
    'description' : "//div[@class='woocommerce-tabs']/div[@id='tab-description']|//article",
    'images' : "//div[@id='content-box']//div[@class='images']/a/@href",
    'canonical' : "//link[@rel='canonical']/@href",
    'base_url' : "",
    'brand' : ""
}
name = 'thucphamchucnangtot.com'
allowed_domains = ['thucphamchucnangtot.com']
start_urls = ['http://thucphamchucnangtot.com']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow=['/shop/']), 'parse_item'),
    Rule(LinkExtractor(allow=['/[a-zA-Z0-9-]+/+$']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
