# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//td[@class='product_bestSeller']/h1/span",
    'price' : "//table//tr/td/div[@class='product_price']",
    'category' : "//a[@class='NevigateURL']",
    'description' : "//div[@class='product_detail_content']/table | //div[@class='product_detail_content']/p[@class='MsoNormal']",
    'images' : "//table[@id='ctl22_img_datalist']//tr/td/div/div/a/@href | //img[@name='targetimage']/@src",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = 'tic.vn'
allowed_domains = ['tic.vn']
start_urls = ['http://tic.vn']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(), 'parse_item'),
    Rule(LinkExtractor(), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
