# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div[@class='itemHeader']/h2[@class='itemTitle']",
    'price' : "",
    'category' : "//div[@class='breadcrumbs']/a",
    'description' : "//div[@class='itemFullText']/p[1]/span",
    'images' : "//div[@class='itemIntroText']/p/img/@src",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = 'tienthanhcomputer.com.vn'
allowed_domains = ['tienthanhcomputer.com.vn']
start_urls = ['http://tienthanhcomputer.com.vn/']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow=['/item/']), 'parse_item'),
    Rule(LinkExtractor(allow=['/danh-muc-san-pham/']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
