# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div[@id='product_description']/h1",
    'price' : "//div[@id='product_cart']/span[@class='price']",
    'category' : "",
    'description' : "",
    'images' : "//div[@id='product_full']/div[@class='right']/a/@href",
    'canonical' : "//link[@rel='canonical']/@href",
    'base_url' : "",
    'brand' : ""
}
name = 'tinkerbell.com.vn'
allowed_domains = ['tinkerbell.com.vn']
start_urls = ['http://tinkerbell.com.vn/']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow=['/\?product=[a-zA-Z0-9-]+$']), 'parse_item'),
    Rule(LinkExtractor(allow=['/\?product_categories=[a-zA-Z0-9-]+($|&paged;=\d+$)']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
