# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div[@class='right_panel']/div[@class='newproduct_detail']/div[@class='header-bar']/h1[@class='pro_name']",
    'price' : "//div[@class='newproduct_detail']/div[@class='pro_info']/div[@class='price']/span[@class='price_value']",
    'category' : "",
    'description' : "//div[@class='main']/div[@class='wsp']/div[@class='right_panel']/div[@class='product_description']",
    'images' : "//div[@class='pro_image']/ul/li/a/@href",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = 'tinviettien.vn'
allowed_domains = ['tinviettien.vn']
start_urls = ['http://tinviettien.vn']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow=['/\d+_\d+/']), 'parse_item'),
    Rule(LinkExtractor(allow=['\.htm']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
