# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div[@class='col-md-9']/h1[@class='title-product']",
    'price' : "//div[@class='col-md-12']/div[@class='row']/div/p[@class='old-price']",
    'category' : "//ol[@class='breadcrumb']/li",
    'description' : "//div[@class='with-nav-tabs tabs-detail col-md-9']/div[@class='panel-body']",
    'images' : "//div[@class='bx-viewport']/div[@id='gal1']/a/img/@src | //div[@id='shopping_cart']/div[@class='col-md-3 col-xs-12']//a/img/@src",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = 'titishop.vn'
allowed_domains = ['titishop.vn']
start_urls = ['http://titishop.vn/']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow=['/[a-zA-Z0-9-]+\.html']), 'parse_item'),
    Rule(LinkExtractor(allow=['/[a-zA-Z0-9-]+$']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
