# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div[@class='product-name']/h1",
    'price' : "//div[@class='product-shop-inner']//span[@class='price']",
    'category' : "//div[@class='breadcrumbs']/ul[@class='breadcrumb']/li/a",
    'description' : "",
    'images' : "//div[@id='zoomer']/img/@src",
    'canonical' : "",
    'base_url' : "",
    'brand' : "",
    'in_stock' : "",
    'guarantee' : ""
}
name = 'totoshop.vn'
allowed_domains = ['totoshop.vn']
start_urls = ['http://totoshop.vn/']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = ['']
rules = [
    Rule(LinkExtractor(allow=['/p\d+/[\w-]+$']), 'parse_item'),
    Rule(LinkExtractor(allow=['/c\d+/[\w-]+($|\?page=\d+)']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
