# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div[@id='columns']/div[@class='center_column']/h2",
    'price' : "//span[@class='our_price_display']/span[@id='our_price_display']",
    'category' : "",
    'description' : "//div[@id='more_info_sheets']/div[@id='idTab1']/p",
    'images' : "//img[@id='bigpic']/@src",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = 'toyshouse.com.vn'
allowed_domains = ['toyshouse.com.vn']
start_urls = ['http://toyshouse.com.vn/']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow=['/product.php\?id_product=\d+']), 'parse_item'),
    Rule(LinkExtractor(allow=['/category.php\?id_category=\d+($|.p=\d+$)']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
