# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div[@class='detail-product']/h1",
    'price' : "//div[@class='detail-product']/div[@class='detail-price']/ul/li/strong",
    'category' : "//div[@class='link-bread']/ul/li/a",
    'description' : "//div[@class='detail-product']/div[@class='table-text']",
    'images' : "//a/img[@class='lazy']/@data-original",
    'canonical' : "",
    'base_url' : "",
    'brand' : "",
    'in_stock' : "",
    'guarantee' : "",
    'promotion' : ""
}
name = 'trangsuc.doji.vn'
allowed_domains = ['trangsuc.doji.vn']
start_urls = ['http://trangsuc.doji.vn/']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = ['']
rules = [
    #Rule(LinkExtractor(), 'parse_item'),
    #Rule(LinkExtractor(), 'parse'),
    Rule(LinkExtractor(allow=['/[a-zA-Z0-9-]+($|\?page=\d+$)']), 'parse_item_and_links'),
]
