# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//title",
    'price' : "//div[@class='thongtin']/div[@class='right_chitiet']/font[@id='price_km']",
    'category' : "",
    'description' : "//div[@class='noidung_chitiet']/div[@class='noidung_1']/p",
    'images' : "//div[@class='hinh']/div[@class='img']//a/@href",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = 'tranhdepminhngoc.com'
allowed_domains = ['tranhdepminhngoc.com']
start_urls = ['http://tranhdepminhngoc.com']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow=['/[a-zA-Z0-9-]+\.html']), 'parse_item'),
    Rule(LinkExtractor(allow=['/[a-zA-Z0-9-]+/']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
