# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div[@class='product-info']/h1[@class='mainbox-title']",
    'price' : "//span[contains(@id,'price_update')]/span[contains(@id,'line_discounted_price')]/span[contains(@id,'sec_discounted_price')]",
    'category' : "//div[@class='breadcrumbs']",
    'description' : "//div[@id='tabs_content']",
    'images' : "//a[conatins(@id,'detailed_href1')]/img[contains(@id,'det_img')]/@src",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = 'trituevietnam.com.vn'
allowed_domains = ['trituevietnam.com.vn']
start_urls = ['http://www.trituevietnam.com.vn/']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(), 'parse_item'),
    Rule(LinkExtractor(), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
