# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//h1[@class='productDetailName']",
    'price' : "//div[@class='proInfoDetail']/div[@class='priceDetail']",
    'category' : "//div[@class='crumb']/a",
    'description' : "//div[@class='ContentTab']/div[@class='contentproTab']",
    'images' : "//div[@class='proImageDetail']//a/@href",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = 'tuananh.vn'
allowed_domains = ['tuananh.vn']
start_urls = ['http://www.tuananh.vn/']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow=['/[a-zA-Z0-9-]+/[a-zA-Z0-9-]+-\d+\.html$']), 'parse_item'),
    Rule(LinkExtractor(allow=['/[a-zA-Z0-9-]+/($|page-\d+/)']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
