# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div[@class='detail_ar']/h2",
    'price' : "//div/label[@class='lb_price_article']",
    'category' : "",
    'description' : "//div[@class='DetailHotel']/div[@class='bd']",
    'images' : "//div[@id='description']/img/@src",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = 'tuntravel.com'
allowed_domains = ['tuntravel.com']
start_urls = ['http://www.tuntravel.com/']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(), 'parse_item'),
    Rule(LinkExtractor(), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
