# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//h1[@class='product-name']",
    'price' : "//div[@class='row']/div[@class='col-lg-6 col-md-6 col-sm-12 col-xs-12']/p[@class='product-price']",
    'category' : "//ul[@class='breadcrumb']/li/a",
    'description' : "//div[@class='tab-content']/div[@class='tab-pane active']",
    'images' : "//meta[@property='og:image'][1]/@content",
    'canonical' : "//link[@rel='canonical']/@href",
    'base_url' : "",
    'brand' : "",
    'in_stock' : "",
    'guarantee' : "",
    'promotion' : ""
}
name = 'tvdirect.vn'
allowed_domains = ['tvdirect.vn']
start_urls = ['http://www.tvdirect.vn/']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = ['']
rules = [
    Rule(LinkExtractor(allow=['/[a-zA-Z0-9-]+$'], deny=['/collections/']), 'parse_item'),
    Rule(LinkExtractor(allow=['/collections/all($|\?page=\d+$)']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
