# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div[@class='title-chitiet']/h4",
    'price' : "//div[@class='detail-col1']/div[@class='ttsanpham']/span[@id='showPrice']",
    'category' : "",
    'description' : "//div[@id='content-chitietsp']/div/div[@id='b_detail_product']",
    'images' : "//div[@id='gallery']/ul/li/a/@href",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = 'tvshopping.vn'
allowed_domains = ['tvshopping.vn']
start_urls = ['http://tvshopping.vn']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow=['/P/']), 'parse_item'),
    Rule(LinkExtractor(allow=['/C/']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
