# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//h1[@class='prd-seo']/div[@class='prd-brand']",
    'price' : "//div[@class='ui-price']/span[@class='prd-price']",
    'category' : "//ul[@class='breadcrumb']/li/a",
    'description' : "//div[@class='tab-content']/div[@id='tab1']",
    'images' : "//div[@id='jcarousel']/ul/li[@class='active']/a/@href | //div[@class='imgZoom']/div/div/div/ul/li/a/@href",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = 'ubaby.vn'
allowed_domains = ['ubaby.vn']
start_urls = ['http://ubaby.vn']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow=['/[a-zA-Z0-9-]+\.html']), 'parse_item'),
    Rule(LinkExtractor(allow=['/[a-zA-Z0-9-]+/+$'], deny=['\?']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
