# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//h1[@class='mr_none']",
    'price' : "//div[@class='clearfix pdTB5']/div/div/span",
    'category' : "//ol[@class='breadcrumb breadcrumb-arrow hidden-sm hidden-xs']/li/a",
    'description' : "//div[@class='clearfix content_text']//text()",
    'images' : "//div[@class='image']//img/@src",
    'canonical' : "//link[@rel='canonical']/@href",
    'base_url' : "",
    'brand' : ""
}
name = 'ula.vn'
allowed_domains = ['ula.vn']
start_urls = ['http://ula.vn/']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow=['/products/[a-zA-Z0-9-]+$']), 'parse_item'),
    Rule(LinkExtractor(allow=['/collections/[a-zA-Z0-9-]+($|\?page=\d+)']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
