# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div[@class='row tour-summary']/div[@class='col-md-12']/h2[@class='title']",
    'price' : "//div[@class='row tour-summary']//div[@class='col-md-7 price sell-price']",
    'category' : "//div[@class='breakcrumb']//a",
    'description' : "//div[@id='tabs-1']",
    'images' : "//div[@id='bigPic']/img/@src",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = 'unigolf.vn'
allowed_domains = ['unigolf.vn']
start_urls = ['http://unigolf.vn/']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow=['GianHangGolf/Detail/\d+']), 'parse_item'),
    Rule(LinkExtractor(allow=['/gian-hang-golf/']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
