# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//span[@id='ctl00_ContentPlaceHolder1_LabelTieuDeSP']/h1",
    'price' : "//p[@class='productGiaBan-BG']/span[@class='productGiaTien3']",
    'category' : "//span[@id='ctl00_ContentPlaceHolder1_LabelTieuDe']/a",
    'description' : "//table//tr/td/div[@class='productLabel']",
    'images' : "//td[@class='Image-none']/a/@href",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = 'usstore.com.vn'
allowed_domains = ['usstore.com.vn']
start_urls = ['http://usstore.com.vn']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow=['/v/']), 'parse_item'),
    Rule(LinkExtractor(allow=['/store/']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
