# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div[@class='info-sp']/h1",
    'price' : "//form[@id='add_to_cart_form']/li[2]/span[@class='font-size-25']",
    'category' : "//ul[@class='breadcrumbs clearfix group']/li/a/span",
    'description' : "//div[@class='info-sp']/div[@class='intro-sp']",
    'images' : "//div[@class='zoom-sp']/a/@href",
    'canonical' : "",
    'base_url' : "",
    'brand' : "",
    'in_stock' : "",
    'guarantee' : "",
    'promotion' : ""
}
name = 'vanlang.vn'
allowed_domains = ['vanlang.vn']
start_urls = ['http://vanlang.vn/']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = ['']
rules = [
    Rule(LinkExtractor(allow=['san-pham/[a-zA-Z0-9-]+\.html$']), 'parse_item'),
    Rule(LinkExtractor(allow=['danh-muc/[a-zA-Z0-9-]+\.html($|\?product_per_page=\d+.product_page=\d+$)']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
