# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//title",
    'price' : "//div[@class='sampo-product']/div[@class='price']/h1",
    'category' : "//div[@class='brescums']/p/a",
    'description' : "//div[@class='sampo-product']/ul[@class='thongso']/li",
    'images' : "//div[@class='picture-view']/div//a/@href",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = 'vanphuc.com.vn'
allowed_domains = ['vanphuc.com.vn']
start_urls = ['http://vanphuc.com.vn/']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow=['/[a-zA-Z0-9]+\.html']), 'parse_item'),
    Rule(LinkExtractor(allow=['/[a-zA-Z0-9-]+$','/Product/'], deny=['/tin-tuc/']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
