# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div[@class='name']",
    'price' : "//div[@class='chiTiet']/div[@class='valuesTH']",
    'category' : "//div[@id='CommonWebsiteMapPath']/a",
    'description' : "//div[@class='contentChiTiet'][1]",
    'images' : "//a[@class='thumb']/@href",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = 'vanphongpham123.com'
allowed_domains = ['vanphongpham123.com']
start_urls = ['http://vanphongpham123.com/']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow=['/san-pham/[a-zA-Z0-9-]+\.htm']), 'parse_item'),
    Rule(LinkExtractor(allow=['/[a-zA-Z0-9-]+\.htm$']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
