# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div[@id='content']/header/a/h1",
    'price' : "//div[@class='product-info']/p[@class='product-price']/span[1]",
    'category' : "//p[@id='breadcrumbs']/span/span/a",
    'description' : "//div[@class='post-info']/p",
    'images' : "//div[@class='product-thumb']/img/@src",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = 'vaycongsoshop.com'
allowed_domains = ['vaycongsoshop.com']
start_urls = ['http://vaycongsoshop.com']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow=['/san-pham/']), 'parse_item'),
    Rule(LinkExtractor(allow=['/[a-zA-Z0-9-]+/+$']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
