# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//h2[@class='text-uppercase text-darkblue mtop0 fs19 mfwb']",
    'price' : "//div[@class='col-md-4 info']/p[@class='fs20 mtop30 mbottom30 mfwb']",
    'category' : "//div[@class='breadcrums mhide']/span/a",
    'description' : "//div[@class='tab-pane active']",
    'images' : "//div[@class='col-md-8 text-center']/img/@data-src",
    'canonical' : "//link[@rel='canonical']/@href",
    'base_url' : "//base/@href",
    'brand' : "",
    'in_stock' : "",
    'guarantee' : "",
    'promotion' : ""
}
name = 'vichy.com.vn'
allowed_domains = ['vichy.com.vn']
start_urls = ['http://www.vichy.com.vn/']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = ['']
rules = [
    #Rule(LinkExtractor(), 'parse_item'),
    #Rule(LinkExtractor(), 'parse'),
    Rule(LinkExtractor(allow=['/san-pham/']), 'parse_item_and_links'),
]
