# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div[@class='box_attr_product']/div[@class='name_product']/h1",
    'price' : "//div[@class='price']/div[@class='current_price']/span/span/span",
    'category' : "//div[@class='breadcrumb']/ul/li/a",
    'description' : "//div[@id='content_description']/p",
    'images' : "//div[@id='content_description']//img/@src | //div[@class='box_img_attr']//img/@src",
    'canonical' : "",
    'base_url' : "//base/@href",
    'brand' : ""
}
name = 'viendongshop.vn'
allowed_domains = ['viendongshop.vn']
start_urls = ['http://viendongshop.vn/']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow=['\.html']), 'parse_item'),
    Rule(LinkExtractor(allow=['/[a-zA-Z0-9-]+/'], deny=['features_hash=','items_per_page=','sort_by=','sort_order=','subcats=']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
