# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div[@class='detail-right']/h1[@class='bgtt2']",
    'price' : "//div[@class='m3-detail']/div[@class='detail-right']/p/b",
    'category' : "//div[@class='site_map']/div[@class='href']",
    'description' : "//div[@class='dt']/p",
    'images' : "//div[@class='m3-detail']/div[@class='detail-left']//a/@href",
    'canonical' : "",
    'base_url' : "//base/@href",
    'brand' : ""
}
name = 'vienthongthanhpho.vn'
allowed_domains = ['vienthongthanhpho.vn']
start_urls = ['http://vienthongthanhpho.vn/']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow=['/detail/']), 'parse_item'),
    Rule(LinkExtractor(allow=['/[a-zA-Z0-9-]+-\d+\.html']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
