# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div[@id='module_29']/div[@class='khung_29']/h3[@class='tieude_29']/a[@class='lienket_29']",
    'price' : "//div[@id='module_29']/div[@class='khung_29']/div[@class='gia_29']/span[@class='giatri_29']",
    'category' : "//tr/td/div[@class='noidung_76']",
    'description' : "//ul[@id='featured1']/p/span",
    'images' : "//div[@class='anh_29']/a/img/@src",
    'canonical' : "//link[@rel='canonical']/@href",
    'base_url' : "//base/@href",
    'brand' : ""
}
name = 'viethungepc.com'
allowed_domains = ['viethungepc.com']
start_urls = ['http://viethungepc.com']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow=['/spct/']), 'parse_item'),
    Rule(LinkExtractor(allow=['/spds/']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
