# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//section[@class='sleft']/div[@id='ecombox']/h1",
    'price' : "//div/strong[@class='pricesell']",
    'category' : "//div[@class='breadcrumb']/div/a/span",
    'description' : "//section[@class='sleft']/div[@class='article']",
    'images' : "//div[@class='gallery']/div[@class='ftrm']/img/@src",
    'canonical' : "//link[@rel='canonical']/@href",
    'base_url' : "",
    'brand' : ""
}
name = 'viettronimexdanang.com.vn'
allowed_domains = ['viettronimexdanang.com.vn']
start_urls = ['http://viettronimexdanang.com.vn']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow=['/san-pham/']), 'parse_item'),
    Rule(LinkExtractor(allow=['/danh-muc'], deny=['thong-tin-viettronimex','/gioi-thieu-ve-viettronimex/']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
