# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div[@class='homebox']/div[@id='chitietsp']/div[@class='right']/h1",
    'price' : "//div[@class='right']/ul/li/b",
    'category' : "//div[@class='left']/div[@class='homebox']/div[@id='bre']/a",
    'description' : "//div[@class='left']/div[@class='homebox']/div[@id='more_info_block']/div[@id='description']",
    'images' : "//div[@id='chitietsp']/div[@class='left']/div/img/@src",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = 'violetspa.vn'
allowed_domains = ['violetspa.vn']
start_urls = ['http://violetspa.vn']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow=['']), 'parse_item'),
    Rule(LinkExtractor(allow=['']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
