# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div[@class='entry-summary-content']/h1[@itemprop='name']",
    'price' : "//p[@class='price']/span[@class='woocommerce-Price-amount amount']",
    'category' : "",
    'description' : "",
    'images' : "//div[@id='product-thumbnails']/a/@href",
    'canonical' : "//link[@rel='canonical']/@href",
    'base_url' : "",
    'brand' : "",
    'in_stock' : "",
    'guarantee' : "",
    'promotion' : ""
}
name = 'vitaminsea.vn'
allowed_domains = ['vitaminsea.vn']
start_urls = ['https://www.vitaminsea.vn/shop/']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = ['']
rules = [
    Rule(LinkExtractor(allow=['/shop/[a-zA-Z0-9-]+/$']), 'parse_item'),
    Rule(LinkExtractor(allow=['/shop/$']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
