# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div[@class='chitietsp']/h1",
    'price' : "//div[@class='chitietsp']/ul/li[@class='giasp']",
    'category' : "//div[@class='breadcrumb']/ul/li/a",
    'description' : "//div[@class='thongtinsp']/p",
    'images' : "//div[@class='chitietsp']/p/img/@src",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = 'vitinhphongvu.com'
allowed_domains = ['vitinhphongvu.com']
start_urls = ['http://vitinhphongvu.com']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow=['/[a-z0-9-]+\.html']), 'parse_item'),
    Rule(LinkExtractor(allow=['/[a-zA-Z0-9-]+-\d+c+\.html']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
