# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div[@class='product-name']/h1",
    'price' : "//div[@class='product-shop']/div[@class='price-box']/span[contains(@id,'product-price')]/span[@class='price']",
    'category' : "//div[@class='breadcrumbs']/ul/li/a",
    'description' : "//div[@class='product-collateral']",
    'images' : "//img[@id='image']/@src",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = 'vnmay.vn'
allowed_domains = ['vnmay.vn']
start_urls = ['http://vnmay.vn/']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(), 'parse_item'),
    Rule(LinkExtractor(), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
