# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div[@class='bold_gray']/strong",
    'price' : "//table[@class='goods_base']//span",
    'category' : "",
    'description' : "//table[@id='tbContent']/tbody/tr/td",
    'images' : "//img[@id='mainImg']/@src",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = 'vnwiz.com'
allowed_domains = ['vnwiz.com']
start_urls = ['http://www.vnwiz.com']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(), 'parse_item'),
    Rule(LinkExtractor(), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
