# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//h1[@class='name']",
    'price' : "//div[@class='price-buy']/div[@class='price']//span[@class='new-price']",
    'category' : "//div[@id='breadcrumb']/a",
    'description' : "//div[@class='tab_content']/div[@class='tab-content-main']",
    'images' : "//div[@class='simpleLens-big-image-container']/a/@data-lens-image",
    'canonical' : "",
    'base_url' : "",
    'brand' : "",
    'in_stock' : "",
    'guarantee' : "",
    'promotion' : ""
}
name = 'vuabanle.vn'
allowed_domains = ['vuabanle.vn']
start_urls = ['https://vuabanle.vn/']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = ['']
rules = [
    Rule(LinkExtractor(allow=['/[a-zA-Z0-9-]+-p\d+\.html$']), 'parse_item'),
    Rule(LinkExtractor(allow=['/[a-zA-Z0-9-]+-c\d+']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
