# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div[@class='title_newsok']/div[@class='abcc']/a/h1",
    'price' : "//ul[@class='details']/li/p/strong[@class='redHightLight']",
    'category' : "//div[@id='content']/div[@class='title_newsok']/div[@class='abcc']/a",
    'description' : "//div[@class='TabbedPanelsContentGroup']/div[@class='TabbedPanelsContent TabbedPanelsContentVisible']/div[@class='format']/p",
    'images' : "//div[@class='highslide-gallery']/a[@class='highslide']/img/@src",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = 'vuhoangsecurity.com'
allowed_domains = ['vuhoangsecurity.com']
start_urls = ['http://vuhoangsecurity.com']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow=['/chi-tietsp-']), 'parse_item'),
    Rule(LinkExtractor(allow=['/san-pham-']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
