# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div[@id='vmMainPage']/table/tbody/tr[1]/td[1]/div/h1",
    'price' : "//div[@id='vmMainPage']/table/tbody/tr[6]/td",
    'category' : "//div[@id='ja-pathway']",
    'description' : "//div[@id='vmMainPage']/table/tbody/tr[9]/td",
    'images' : "//a/img/@src",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = 'webtongdai.com'
allowed_domains = ['webtongdai.com']
start_urls = ['http://webtongdai.com/']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(), 'parse_item'),
    Rule(LinkExtractor(), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
