# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div[@class='detail-mainInfo']/h1[@class='product-name']",
    'price' : "//div[@class='price_display']/span[@class='uc-price']",
    'category' : "//div[@id='breadcrumb']/div[@class='inner']/span/a",
    'description' : "//div[@class='productBody']/div[@class='detail_product']",
    'images' : "//div[@class='image_product']/div[@id='images_preview']/a/@href",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = 'wheystore.vn'
allowed_domains = ['wheystore.vn']
start_urls = ['http://www.wheystore.vn/']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow=['/[a-zA-Z0-9-]+-\d+\.html']), 'parse_item'),
    Rule(LinkExtractor(allow=['/c+\d+/[a-zA-Z0-9-]+($|\?page=\d+)']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
