# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div[@class='product-info']/div[@class='teaser fr']/h1[@class='df blue']",
    'price' : "//div[@class='teaser fr']/div/span[@class='price bold']",
    'category' : "//div[@class='content-title']/h4[@class='df fl']/a[@class='text fl']",
    'description' : "//div[@id='content']/div[@id='detail-product']/div[@id='pro-detail']",
    'images' : "//div[@class='thumb fl']/img/@src",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = '2day.com.vn'
allowed_domains = ['2day.com.vn']
start_urls = ['http://2day.com.vn']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow=['']), 'parse_item'),
    Rule(LinkExtractor(allow=['']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
