# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//h1[@class='title product_title entry-title']",
    'price' : "//span[@class='price']/ins/span[@class='amount'] | //div[@class='summary']/span[@class='price']/span[@class='amount']",
    'category' : "//div[@id='breadcrumb']/a",
    'description' : "//div[@id='tab-description']",
    'images' : "//div[@class='panel']/ul/li/a/@href",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = '25h.vn'
allowed_domains = ['25h.vn']
start_urls = ['http://25h.vn']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow=['/cua-hang/']), 'parse_item'),
    Rule(LinkExtractor(allow=['/.*/$']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
