# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//h1[@class='title']",
    'price' : "//td[@class='product_price']",
    'category' : "",
    'description' : "//div[@class='middle']/div[@id='product_content']",
    'images' : "//div[@class='images']/div[@id='tb-product']/div[@class='thumb']/a/@href",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = '68deal.vn'
allowed_domains = ['68deal.vn']
start_urls = ['http://68deal.vn/']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow=['/san-pham/[a-zA-Z0-9-]+-\d+.html']), 'parse_item'),
    Rule(LinkExtractor(allow=['/danh-muc/[a-zA-Z0-9-]+(\./html$|/trang/\d+)']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
