# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//section[@id='primary']/div[@id='content']/header/a/h1",
    'price' : "//div[@class='product-info']/p[@class='product-price']",
    'category' : "//p[@id='breadcrumbs']/span/span/a",
    'description' : "//div[@id='content']/div[@class='social-ring']",
    'images' : "//div[@class='post-info']/p/a/@href",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = '88shop.vn'
allowed_domains = ['88shop.vn']
start_urls = ['http://88shop.vn']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow=['/san-pham/']), 'parse_item'),
    Rule(LinkExtractor(allow=['/[a-zA-Z0-9-]+/($|page/\d+/$)']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
