# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div[@class='pfull basic-info']/div[@class='sname']/h1",
    'price' : "//div[@class='name-price']/span[@class='xprice']/span[@class='price ']",
    'category' : "//ol[@class='breadcrumb clearfix']/li/a",
    'description' : "//div[@class='pfixfull deal-des']|//div[@class='x-box-content x-box-noweight xList']|//div[@class='content-more all']",
    'images' : "//meta[@property='og:image']/@content | //div[@id='deal-detail-container']/p/img/@src | //div[@class='x-box-content']/p/img/@data-original | //li/img/@src",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = 'xdeal.vn'
allowed_domains = ['xdeal.vn']
start_urls = ['http://xdeal.vn/']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow = ['/thong-tin-deal/']), 'parse_item'),
    Rule(LinkExtractor(allow = ['/hot-deal+/\d+/']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
