# Auto generated by generator.py. Delete this line if you make modification.
from scrapy.spiders import Rule
from scrapy.linkextractors import LinkExtractor

XPATH = {
    'name' : "//div[@class='info_pname']/h2",
    'price' : "//div[@id='block_product_price']/span[@class='price']",
    'category' : "",
    'description' : "//div[@class='block_item'][1]/div[@class='block_content']",
    'images' : "//div[@class='product_primaryImage']//a/@href",
    'canonical' : "",
    'base_url' : "",
    'brand' : ""
}
name = 'xinhxinh.vn'
allowed_domains = ['xinhxinh.vn']
start_urls = ['http://xinhxinh.vn']
tracking_url = ''
sitemap_urls = ['']
sitemap_rules = [('', 'parse_item')]
sitemap_follow = []
rules = [
    Rule(LinkExtractor(allow=['/sanpham/']), 'parse_item'),
    Rule(LinkExtractor(allow=['/thoitrang/','/mevabe/','/giatotmoingay.html']), 'parse'),
    #Rule(LinkExtractor(), 'parse_item_and_links'),
]
